nodejs/undici

README.md, lib/client.js, lib/pool.js, test/promises.js
As titled!
Should we state somewhere that if you want to achieve the maximum performances, and you are running multiple requests in parallel you should not *await* the result of every request, but handle them in separate functions, as we are doing here:
https://github.com/mcollina/undici/blob/dadb4c3caafd02a6be9c86c314cd9222fbf13da1/test/promises.js#L178-L180
=> Promises support

lib/client.js, test/client.js
=> Support multiple headers with the same key

.gitignore, README.md, lib/client.js, test/client.js
- allow consumers to specify custom host header
- add tests:
- for default host header
- for custom host header
=> allow custom host header

lib/client.js, package.json
Inlining is both simpler and faster.
=> fix: remove syncthrough

lib/client.js
setImmediate kind of works but is brittle to future changes in socket.destroy behavior use a safer variant based on eos.
=> fix: use eos instead of setImmediate

lib/client.js, test/client-errors.js, test/client.js
Fixes: https://github.com/mcollina/undici/issues/20
=> fix: close should gracefully wait for all queued requests

lib/client.js, package.json, test/pool.js
Fixes: https://github.com/mcollina/undici/issues/17
=> feat: allow overriding stream implementation

lib/request.js
Refs: https://github.com/mcollina/undici/issues/35
=> fix: removed TODO

lib/client.js, test/client-errors.js
sanity check for implementation
=> fix: assert on invalid request body

lib/client.js
Assertion logic was wrong. Should never happen but it does
sometimes while developing so having a correct assertion is
helpful.
=> fix: request assertion logic

lib/client.js, package.json
Fixes: https://github.com/mcollina/undici/issues/58
=> fix: use native socket timeout

lib/client.js, test/client-errors.js
I believe this is a simpler, faster and more correct way of doing this, maybe?
Fixes: https://github.com/mcollina/undici/issues/50
=> fix: simplify reading

lib/client.js, test/client-errors.js
Fixes: https://github.com/mcollina/undici/issues/62
=> fix: handle parser error

lib/client.js
Fixes: https://github.com/mcollina/undici/issues/11
This is a rather simple backoff implementaiton. We could make it more advanced with more options. However, I think this should be good enough and adding more options will just confuse and make things more complicated.
=> fix: add simple reconnect backoff

README.md, lib/client.js, lib/request.js, test/client-errors.js, test/client.js
Fixes: https://github.com/mcollina/undici/issues/77
Fixes: #81
=> fix: pipelining corresponds to number of active requests

README.md, lib/client.js, test/client.js
Fixes: https://github.com/mcollina/undici/issues/15
=> fix: close connection on aborted response

lib/client.js, test/client-errors.js, test/client.js
some minor fixes, simplifications and additional tests
=> fixes and tests

lib/client.js, package.json, test/client-errors.js, test/client-pipelining.js, test/close-and-destroy.js, test/pool.js
Fixes: https://github.com/mcollina/undici/issues/99
=> fix: use core streams

lib/client.js, test/client-errors.js
Was just hiding another bug caused by a missing pause.
=> fix: remove unnecssary reset logic

lib/client.js, package.json, test/client-errors.js
This replaces the fastq + inflight array with a single array + 2 indices.
Using the pattern moving things around is simply a matter of updating the indices to a buffer, with an amortized max limit on the buffer size.
undici benchmark
This PR: 2908.378ms
master: 6487.863ms
=> perf: optimize queue

lib/client.js
Refs: https://github.com/mcollina/undici/issues/116
=> cleanup, assert & comment

lib/client.js, test/client-errors.js
Fixes: https://github.com/mcollina/undici/issues/127
Refs: https://github.com/mcollina/undici/issues/116
=> fix: destroy() should not error

README.md, lib/client.js, lib/request.js, test/client-stream.js
Fixes: https://github.com/mcollina/undici/issues/140
=> feat: add opaque to request.stream

lib/client.js, test/client-pipeline.js, test/client-stream.js
Fixes: https://github.com/mcollina/undici/issues/154
=> fix: avoid throw

lib/client.js, test/client-abort.js, test/client-errors.js, test/client-pipeline.js, test/client-stream.js, test/client.js, test/pool.js
```bash
-------------|----------|----------|----------|----------|-------------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------|----------|----------|----------|----------|-------------------|
All files    |    98.34 |    93.88 |    92.86 |    98.68 |                   |
undici      |      100 |      100 |      100 |      100 |                   |
index.js   |      100 |      100 |      100 |      100 |                   |
undici/lib  |    98.31 |    93.88 |    92.78 |    98.66 |                   |
client.js  |    99.76 |    95.44 |    98.53 |    99.76 |               163 |
errors.js  |      100 |    83.33 |      100 |      100 |             26,66 |
pool.js    |    81.82 |    77.78 |    66.67 |    84.21 | 30,31,32,33,38,42 |
request.js …
```
=> test: improve coverage

lib/client.js, lib/request.js, test/client-errors.js
I need to land this before sorting out close.
=> refactor: cleanup request callback logic

lib/client.js, test/client-errors.js, test/client-pipelining.js
https://github.com/mcollina/undici/issues/175
=> fix: close semantics

README.md, lib/client.js, test/client.js
Fixes: https://github.com/mcollina/undici/issues/188
=> fix: lowercase response header keys

lib/client.js, test/client-reconnect.js
Avoid delay during first retry. Also add test for multiple retries.
=> fix: retry delay

.github/workflows/nodejs.yml, .taprc, package.json
Makes `npm run test` more than twice as fast.
=> perf: faster test run

README.md
Fixes: https://github.com/mcollina/undici/issues/200
Fixes: https://github.com/mcollina/undici/issues/79
=> doc: document spec non-compliance

lib/client-base.js, lib/request.js, lib/symbols.js, test/tls.js
Fixes: https://github.com/mcollina/undici/issues/217
=> fix: set tls servername

README.md, lib/client.js, test/client-pipeline.js
Fixes: https://github.com/mcollina/undici/issues/221
=> feat: add support for object stream in pipeline

benchmarks/index.js, benchmarks/server.js, lib/client-base.js
Seems to provide some performance improvement but there is too much variance in my results to say for sure. From what I can read it is recommended to disable Nagle's, at least when using pipelining.
=> perf: socket noDelay

README.md, lib/client-base.js, lib/pool.js, test/client-pipelining.js, test/client.js, test/close-and-destroy.js, test/pool.js
Fixes: https://github.com/mcollina/undici/issues/231
=> feat: add busy property

README.md, lib/client-base.js, lib/errors.js, lib/symbols.js, test/client-errors.js, test/client-pipelining.js, test/headers-timeout.js
Unfortunately haven't been able to make it actually trigger the timeout on a test.
=> feat: headersTimeout

README.md, lib/client-base.js, lib/symbols.js, test/unix.js
=> fix: move socketPath to options object

lib/client-base.js, test/content-length.js
Fixes: https://github.com/mcollina/undici/issues/253
=> fix: fail on content-length mismatch

lib/client.js, test/client-pipelining.js, test/get-head-body.js
Fixes: https://github.com/mcollina/undici/issues/258
=> fix: always reset connection after HEAD

lib/pool.js, test/unix.js
=> fix: pass socketPath in pool

README.md, lib/client-connect.js, lib/client-pipeline.js, lib/client-request.js, lib/client-stream.js, lib/client-upgrade.js, lib/client.js, lib/pool.js, lib/request.js, test/client-connect.js, test/client-pipeline.js, test/client-stream.js, test/client-upgrade.js
```js
client.upgrade({
path: '/',
method: 'GET',
protocol: 'Websocket'
}, (err, data) => {
const { headers, socket } = data
})
```
```js
client.connect({
path: '/'
}, (err, data) => {
const { statusCode, headers, socket } = data
})
```
=> feat: upgrade support

README.md
I've mostly made this up on the fly so if you have better suggestions please let me know!
=> docs: improve docs with more type info

benchmarks/index.js, lib/client-pipeline.js, lib/client-request.js, lib/client-stream.js, lib/client.js, lib/request.js, lib/symbols.js, test/client-stream.js, test/pipeline-pipelining.js
This just updates the internal API. I'll open a separate PR for exposing this as a public API.
Refs: https://github.com/mcollina/undici/issues/293
Fixes: https://github.com/mcollina/undici/issues/296
=> refactor: update internal API

README.md, lib/client.js, lib/request.js, test/client-errors.js, test/client.js
This makes the client a bit more ergonomic to use.
=> fix: prepend client url pathname

README.md
just a fun FYI, seems we have some further perf improvements pending for the next release 🎉
=> update bench results

README.md, lib/client.js, lib/request.js
`net.isIP` is slow. Avoid it when possible.
=> perf: try to avoid slow net.isIP

lib/client.js
=> perf: avoid deep call stack in sync 'drain'

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
See: https://github.com/nodejs/admin/issues/541
Fixes #312.
=> Add Node.js meta documents

lib/core/client.js, lib/core/node/fixed-queue.js, lib/core/node/http-parser.js, lib/pool.js, test/fixed-queue.js
I assume the node FixedQueue is the faster implementation.
=> refactor: use node FixedQueue

README.md
Fixes: https://github.com/nodejs/undici/issues/364
=> doc: document pool ordering

lib/client-pipeline.js, lib/core/client.js, test/client-dispatch.js, test/client-errors.js, test/pool.js, test/validations.js
Fixes: https://github.com/nodejs/undici/issues/371
=> fix: unhandled exception

lib/core/client.js, lib/core/request.js
A step towards trying to avoid dependency on `Client` inside `Request`.
=> refactor: move logic out from Request

lib/client-connect.js, lib/client-pipeline.js, lib/client-request.js, lib/client-stream.js, lib/client-upgrade.js, lib/core/request.js, lib/core/util.js, test/abort-controller.js, test/abort-event-emitter.js, test/client-connect.js, test/client-pipeline.js, test/client-pipelining.js, test/client-request.js, test/client-upgrade.js, test/pool.js
Fixes: https://github.com/nodejs/undici/issues/350
Fixes: https://github.com/nodejs/undici/issues/356
Fixes: https://github.com/nodejs/undici/issues/370
=> fix: pool queued

lib/pool.js, test/pool.js
Fixes: https://github.com/nodejs/undici/issues/373
=> fix: Pool.close

lib/core/client.js, lib/pool.js, test/pool.js
Fixes: https://github.com/nodejs/undici/issues/390
Fixes: https://github.com/nodejs/undici/issues/393
=> fix: Pool.destroy + queued requests

README.md
Fixes: https://github.com/nodejs/undici/issues/389
Fixes: https://github.com/nodejs/undici/issues/381
=> docs: document 'drain' and body

lib/core/client.js
=> perf: avoid indirect access

lib/core/client.js
=> perf: reduce string ops

lib/core/client.js, test/client-errors.js
If body is an object stream don't crash the process. Error the request.
=> fix: catch invalid arg type body

lib/abort-signal.js, lib/client-connect.js, lib/client-pipeline.js, lib/client-request.js, lib/client-stream.js, lib/client-upgrade.js, lib/core/util.js, test/client-connect.js, test/client-pipeline.js, test/client-request.js, test/client-stream.js, test/client-upgrade.js, test/client.js
Fixes: https://github.com/nodejs/undici/issues/411
=> fix: cleanup abort signal listeners

README.md, lib/core/request.js, test/headers-as-array.js
=> add array support for request headers

lib/core/client.js
Fixes: https://github.com/nodejs/undici/issues/394
=> fix: always resume in next tick

lib/core/client.js, test/client-write-max-listeners.js
Fixes: https://github.com/nodejs/undici/issues/430
=> fix: don't leak socket listener

README.md, lib/core/client.js, lib/core/errors.js, lib/core/util.js, test/client-stream.js, test/trailers.js
Fixes: https://github.com/nodejs/undici/issues/432
=> fix: verify trailers

lib/core/client.js, lib/core/util.js
Not sure how/when these could actually error but I guess it's appropriate to handle.
=> fix: handle socket handle errors

lib/core/client.js, lib/core/request.js, test/client-upgrade.js
Fixes: https://github.com/nodejs/undici/issues/437
=> fix: bad upgrade header 

package.json, test/esm-wrapper.js
Also adds ESM test to the CI tests.
=> test: skip ESM test when ESM support not available

README.md, lib/core/client.js, test/client-errors.js, test/client-keep-alive.js
=> fix: rename idleTimeout option to keepAliveTimeout

benchmarks/index.js, benchmarks/server.js
I've made a few changes, lmk what you think.
=> make benchmarks parametric

lib/core/request.js, test/client.js, test/validations.js
=> fix: accept absolute urls as path

lib/core/util.js, test/client-keep-alive.js
Fixes: https://github.com/nodejs/undici/issues/476
=> fix: keep-alive postfix optional

lib/client-connect.js, lib/client-upgrade.js, lib/core/client.js, lib/core/request.js, lib/pool.js, test/client-dispatch.js, test/pool.js
=> add args checks for dispatch handler

README.md
=> docs: fix abort request

test/gc.js
Fixes: https://github.com/nodejs/undici/issues/515
=>  test: re-enable gc test on darwin 

README.md, lib/pool.js, test/pool.js
=> fix(pool): forward error on disconnect event

lib/pool.js, test/pool.js
Needed these semi-urgently. Missing tests.
=> Various Pool improvements

lib/agent.js, lib/core/symbols.js, lib/core/util.js, test/agent.js
=> add close and destroy methods to Agent class

README.md
adds missing docs from my previous pr #521
=> add close and destroy method to docs

README.md
Pool implements same API as Client. Avoid duplicate docs.
=> docs: Simplify Pool docs

test/types/errors.test-d.ts, types/errors.d.ts
Add BodyTimeoutError to error types
=> Add BodyTimeoutError to error types

docsify/sidebar.md
quick fix for the sidebar didn't notice until I started working on the `Agent.md` file 😉 (coming soon)
=> fix docsify sidebar

lib/agent-redirect.js, test/esm-wrapper.js, test/redirect-pipeline.js, test/redirect-request.js, test/redirect-stream.js, test/utils/esm-wrapper.mjs, test/utils/redirecting-servers.js, test/utils/stream.js
=> test: Added tests for RedirectAgent.

index.js, lib/agent/index.js, lib/agent/redirect.js, lib/client-pool.js, lib/core/client.js, lib/core/request.js, lib/core/util.js, lib/node/http-parser.js, package.json, test/agent.js, test/client-dispatch.js, test/client.js, test/pool.js, test/redirect-request.js, test/redirect-stream.js, test/utils/redirecting-servers.js
This PR provides mainly two things:
1. Make sure it is possible to connect to IPv6 IPs. @mcollina @ronag Please double check this. I randomly found this while bringing coverage up.
2. Bring coverage above 95% (now it is around 98%).
=> Bring test coverage above 95%

lib/agent/index.js, lib/client-pool.js, lib/core/client.js, test/pool.js
Pulled out some of the minor stuff from https://github.com/nodejs/undici/pull/620
=> Minor fixes

.dockerignore
Refs: https://github.com/nodejs/undici/issues/638
=> fix: dockerignore

README.md
@nodejs/undici should do the same ❤️
=> Add self to readme

lib/agent/index.js
Guard against user mutation options after construction.
=> fix: agent deep copy options

build/Dockerfile
This addresses https://github.com/nodejs/undici/issues/638#issuecomment-810003787
=> build: use 'npm i' in dockerfile

MAINTAINERS.md, README.md
some might have noticed i've been pruning the issue and pr list with some new labels. This document details some of my thinking for the new organization. Is also a great space to detail other maintainer processes
=> docs for maintainers

lib/agent.js, lib/compat/weakref-provider.js, lib/mock/mock-agent.js, test/weakref-provider.js
Related to https://github.com/nodejs/undici/issues/438
This is my first contribution. Improved coverage a bit by removing code duplication (moving WeakRef/CompatWeakRef logic to separate file) and covering it with tests.
=> test: improve coverage on CompatWeakRef

lib/client.js, test/client-connect.js, test/client-pipeline.js, test/client-pipelining.js, test/client-stream.js, test/client-write-max-listeners.js, test/client.js, test/content-length.js, test/get-head-body.js, test/pipeline-pipelining.js, test/tls.js
Fixes: https://github.com/nodejs/undici/issues/660
=> fix: emit disconnect after destroy() 

lib/client.js, lib/llhttp/parser.js
Refs: https://github.com/nodejs/undici/issues/682
Refs: https://github.com/nodejs/undici/issues/659
=> fix: use separate web assembly instance for every Client

README.md
GitHub action was not poiting to the Node org repo.
Codecov was not pointing to the `main` branch.
=> docs(readme): fix badges

test/client.js
I apologize, I forgot to remove it.
=> Remove 'only' from test

test/client.js, test/http-100.js
Refs: 
* #438 
* https://github.com/nodejs/undici/issues/438#issuecomment-815833168
=> A bit more coverage

lib/client.js
Fixes: https://github.com/nodejs/undici/issues/725
=> fix: use single wasm instance

lib/client.js, test/parser-issues.js
Fixes: https://github.com/nodejs/undici/issues/737
=> fix: parsing of headers split between multiple data buffers

examples/proxy/proxy.js, lib/client.js, lib/core/request.js, lib/handler/redirect.js
npm run bench this branch
[1] http - no agent  x 711 ops/sec ±0.86% (84 runs sampled)
[1] http - keepalive x 760 ops/sec ±0.64% (78 runs sampled)
[1] http - keepalive - multiple sockets x 4,732 ops/sec ±1.70% (84 runs sampled)
[1] undici - pipeline x 5,531 ops/sec ±1.81% (84 runs sampled)
[1] undici - request x 5,656 ops/sec ±0.77% (83 runs sampled)
[1] undici - pool - request - multiple sockets x 5,720 ops/sec ±0.64% (86 runs sampled)
[1] undici - stream x 5,809 ops/sec ±0.60% (84 runs sampled)
[1] undici - dispatch x 5,986 ops/sec ±0.45% (88 runs sampled)
[1] undici - noop x 7,414 ops/sec ±0.34% (87 runs sampled)
npm run bench main branch
[1] http - no agent  x 719 ops/sec ±0.73% (84 runs sampled)
[1] http - keepalive x 747 ops/sec ±0.52% (79 runs sampled)
[1] http - keepalive - …
=> perf: loops optimization

index.html
Added favicon to index.html, so it would show up on https://undici.nodejs.org/
Issue: https://github.com/nodejs/undici/issues/657
=> Added favicon to index.html

benchmarks/benchmark.js
This PR adds a custom cronometro printer to output a Markdown ready table in benchmarks.
=> chore: Output a Markdown table in benchmarks.

test/esm-wrapper.mjs, wrapper.mjs
=> Add all properties is v3 esm wrapper

lib/api/api-connect.js, lib/api/api-request.js, lib/api/api-stream.js, lib/api/api-upgrade.js, lib/client.js
Ensure that we have proper ordering relative to promises. This only affects cold paths.
=> fix: ensure callbacks use micro task queue

README.md
History:
* index.js was replaced with two files: single-socket.js and multiple-sockets.js in https://github.com/nodejs/undici/pull/751
* Both the files were merged to benchmark.js in https://github.com/nodejs/undici/pull/752
=> fix: update benchmarks example code link

test/client.js
Adds test for if block on [Line 94](https://codecov.io/gh/nodejs/undici/src/main/lib/core/util.js) of `lib/core/util.js`
=> test: get with host header (IPv6)

lib/client.js, lib/core/errors.js, test/issue-810.js
Fixes: #810
Fixes: #807
It would be nice if we could make this an actual content length mismatch error but we can leave that as future work.
=> fix: complete message error

test/issue-583.js
=> Add tests for issue 583.

docs/api/Dispatcher.md
Im not really sure wether this only applies to the request method or if there is better place to put this (maybe at the top of Client.md).
=> doc: added response body handling advice

test/types/mock-agent.test-d.ts, types/mock-agent.d.ts, types/mock-client.d.ts, types/mock-interceptor.d.ts, types/mock-pool.d.ts
Fixes https://github.com/nodejs/undici/issues/824
=> Added an Interceptable type

docs/api/Errors.md
RequestContentLengthMismatchError -> ResponseContentLengthMismatchError.
=> doc: fix typo in Errors.md

test/client-abort.js, test/errors.js
This PR introduce some test cases to cover new feature.
It was intended to reach the 100% coverage but I was not able to find a scenario to cover the 'if' statement on line 739 in client.js.
Anyway, this PR can help the coverage increase and let you focus on that scenario.
=> added new tests for errors and client

test/types/dispatcher.test-d.ts, types/dispatcher.d.ts
PR to fix issue reported in #858
=> fix: add missing maxRedirections type definition

docs/api/Client.md, docs/api/Dispatcher.md, docs/api/Errors.md, docs/api/MockAgent.md, docs/api/MockClient.md, docs/api/MockErrors.md, docs/api/MockPool.md
Update docs examples from CommonJS to ES Modules
Related issue: https://github.com/nodejs/undici/issues/851
=> docs: updating docs examples to esm modules

lib/client.js
Refs: https://github.com/nodejs/undici/discussions/858
=> fix: don't send extra \r\n

lib/core/connect.js, test/client-unref.js
I have seen the close of my processes being severely delayed by this.
I'm not sure how to test this though.
=> always clear the connectTimeout

docs/api/Connector.md, examples/ca-fingerprint/index.js, test/ca-fingerprint.js
The `getIssuerCertificate` wasn't entirely correct, this version is :)
=> Improve getIssuerCertificate utility

test/types/client.test-d.ts, test/types/dispatcher.test-d.ts, test/types/pool.test-d.ts, types/client.d.ts, types/dispatcher.d.ts, types/pool.d.ts
=> Revert "Types: changes origin to be optional on Client and Pool"

test/types/dispatcher.test-d.ts, types/dispatcher.d.ts
=> add `BodyMixin` type

test/tls.js
=> test: fix flaky ci

lib/client.js, test/client-upgrade.js
Refs: https://github.com/nodejs/node/issues/39495
=> fix: avoid access internal socket state

lib/fetch/body.js, lib/fetch/index.js
Makes `httpNetworkFetch` more closely follow the spec.
=> fix: improve fetch spec compliance

package.json
=> Fix coverage reports

README.md
fix: https://github.com/nodejs/undici/issues/240
=> doc: add doc for url object

lib/client.js
Fixes: https://github.com/nodejs/undici/issues/988
=> fix: lazy load llhttp

lib/core/util.js, test/util.js
=> fix: servername calculation

README.md
Refs: https://github.com/nodejs/undici/issues/998
=> docs: add notes about gc spec compliance

lib/client.js, lib/core/request.js, test/redirect-request.js, test/redirect-stream.js
=> fix: prioritize host header

index.js
Improved the checks and conditionals by using the following:
• Make the split node version a constant so it can be used multiple times without doing the same operation.
• Improve readability by using the logical OR (`||`) operator where appropriate.
=> refactor: improve checks and conditionals

lib/handler/redirect.js
Improved the methods by changing up their loops and improved the readability by removing redundant code and with the help of loop changes.
=> refactor: improve methods and readability

test/fetch/client-fetch.js
improve coverage of `lib/fetch/file.js`
=> fix(fetch): improve coverage of file.js

test/fetch/headers.js
Improve code coverage of `lib/fetch/headers.js`
=> test(fetch): improve code coverage of lib/fetch/headers.js

lib/client.js, test/issue-810.js
Simplify the code by removing a complicated workaround for
when server sends an invalid message. We
need a simpler solution.
Fixes: https://github.com/nodejs/undici/issues/1010
=> fix: simplify and fix assertion

docs/api/DiagnosticsChannel.md, lib/client.js, test/diagnostics-channel/connect-error.js, test/diagnostics-channel/get.js, test/diagnostics-channel/post-stream.js, test/diagnostics-channel/post.js
Trying to close https://github.com/nodejs/undici/issues/1032
=> Add more diagnostic channels

docs/best-practices/mocking-request.md, docsify/sidebar.md
=> add guide on mock request

lib/core/connect.js, test/https.js
Refs: https://github.com/nodejs/undici/issues/992#issuecomment-958358300
=> fix: support no servername

.github/workflows/bench.yml, .github/workflows/fuzz.yml, .github/workflows/nodejs.yml
Bump GitHub Actions to their latest major versions.
=> build(deps-dev): bump github actions

.github/workflows/bench.yml, .github/workflows/fuzz.yml, .github/workflows/nodejs.yml
=> Use pkgjs/action for CI matrix

examples/proxy-agent.js, lib/fetch/response.js, lib/proxy-agent.js, test/node-fetch/response.js, test/proxy-agent.js
Fixes #1094, ~but I'm not 100% sure if deleting the statusText is the nicest way to deal with this as we're mutating the input object.~ EDIT: made simpler and better now :)
=> Handle undefined `status` and `statusText` like Web fetch

lib/client.js, lib/core/util.js, lib/fetch/body.js, lib/fetch/file.js, lib/fetch/formdata.js, lib/fetch/headers.js, lib/fetch/util.js
Refs: https://github.com/nodejs/undici/pull/1109
=> fix: improve support for Blob and File like objects

lib/fetch/response.js, test/fetch/response.js
=> Fix Response.clone with null body

test/client-request.js
add test to https://github.com/nodejs/undici/pull/1129
=> add: request multi byte charactors with setEncoding

lib/fetch/request.js
Implements spec changes from https://github.com/whatwg/fetch/commit/8e4553bcc338fd6db98cc6ba60fc03cea48fad4c and also fixes a few spec divergences (I'll comment on each one to make it easier)
refs: #1141
=> update request.js to match new spec changes

lib/fetch/index.js, lib/mock/mock-utils.js, test/node-fetch/mock.js
=> fix(fetch): integration with MockAgent

lib/fetch/index.js, lib/fetch/util.js, test/fetch/about-uri.js, test/fetch/blob-uri.js
=> fetch: add data: & about: uri support

.github/workflows/nodejs.yml
Released a `v0.1.0` today - slowly inching [towards a `v1`](https://github.com/pkgjs/action/issues/38).
=> Use the tagged pkgjs/action

CONTRIBUTING.md
Refs: https://github.com/nodejs/undici/issues/951
=> docs: add test commands in CONTRIBUTING.md

README.md
Refs: https://github.com/nodejs/undici/issues/951
=> docs: link to fetch test coverage issue

test/types/mock-agent.test-d.ts, types/mock-interceptor.d.ts
=> fix interceptor type

test/client-errors.js
add client invalid  `maxRequestsPerClient` argument error test
=> test(fetch): add client maxRequestsPerClient error test

docs/api/Dispatcher.md
=> docs: add POST request example

lib/client.js, test/http-100.js
=> remove istanbule ignore and add test for bad upgrade

docs/api/Dispatcher.md
=> docs: document the behavior of consuming body twice

CONTRIBUTING.md
This PR updates CONTRIBUTING.md to document the lint command.
=> docs: document lint command

lib/mock/mock-interceptor.js
Unimportant, but found it during another thing 😅
=> chore: fix a typo

index-fetch.js
Noticed https://github.com/nodejs/undici/runs/6126814672?check_suite_focus=true
=> chore: fix lint

index-fetch.js
Refs: https://github.com/nodejs/undici/commit/3e267ece5f3a6b9b4cd6562f885a6884e3926937
=> fix: make index-fetch spec-compliant

package.json
Generated file doesn't change.
=> chore: update esbuild to 0.14.38

package.json
See https://github.com/nodejs/node/runs/6253304838?check_suite_focus=true
=> fix: add index-fetch.js to npm distribution

index.d.ts, test/types/diagnostics-channel.test-d.ts, types/diagnostics-channel.d.ts
=> feat: add diagnostics channel type defs

README.md
Fixed a bit code style of example in readme
=> fix: readme example codestyle

lib/fetch/index.js, test/fetch/client-fetch.js, test/fetch/request.js
Fixes #1509. This is my first PR here so I'm not sure if I did the tests correctly or if this is the right approach to this issue. If it isn't, please comment suggesting how I should do it and I'll gladly change it :)
=> fix(fetch): provide reason upon rejecting when redirected

docs/api/Dispatcher.md
=> docs: Improve documentation for dispatcher response

lib/api/api-request.js, lib/core/errors.js, test/client.js, types/errors.d.ts
Attempt to implement #1513 without leaking connections
=> feat(Errors): include error response body in status code errors (v2)

lib/api/readable.js, test/readable.test.js
=> avoid body reordering on really fast lines

lib/fetch/request.js
Similar to https://github.com/nodejs/undici/blob/main/lib/agent.js#L10=
=> fix: use FinalizationRegistry compat if global is missing

docs/api/Agent.md, docs/api/Client.md
=> Flag interceptors as experimental

lib/fetch/request.js, test/fetch/client-fetch.js, test/node-fetch/main.js, test/node-fetch/request.js, test/wpt/status/fetch.status.json, test/wpt/tests/fetch/api/abort/general.any.js
Refs: https://github.com/nodejs/undici/issues/1666#issuecomment-1267103481
Implements fix from: https://github.com/web-platform-tests/wpt/pull/36268
This test is also failing in every browser also: https://wpt.fyi/results/fetch/api/abort/general.any.html?label=experimental&label=master&aligned
=> fix(wpt): broken test

test/wpt/server/server.mjs, test/wpt/status/fetch.status.json, test/wpt/tests/LICENSE.md, test/wpt/tests/fetch/api/basic/accept-header.any.js, test/wpt/tests/fetch/api/basic/error-after-response.any.js, test/wpt/tests/fetch/api/basic/header-value-null-byte.any.js, test/wpt/tests/fetch/api/basic/historical.any.js, test/wpt/tests/fetch/api/basic/request-head.any.js, test/wpt/tests/fetch/api/basic/request-headers-nonascii.any.js, test/wpt/tests/fetch/api/basic/request-upload.any.js, test/wpt/tests/fetch/api/basic/response-null-body.any.js, test/wpt/tests/fetch/api/basic/scheme-data.any.js, test/wpt/tests/fetch/api/basic/stream-response.any.js, test/wpt/tests/fetch/api/basic/text-utf8.any.js
Also adds in the missing wpt repo license.
=> feat: add in fetch/api/basic WPTs

test/wpt/server/server.mjs, test/wpt/tests/fetch/api/abort/request.any.js, test/wpt/tests/fetch/content-encoding/bad-gzip-body.any.js
=> wpt: add two tests

test/wpt/status/fetch.status.json, test/wpt/tests/fetch/api/basic/scheme-blob.sub.any.js
Updates test from: https://github.com/web-platform-tests/wpt/commit/2d7b8179f353a4257e17e03bbc9a5250dcdad0c2
=> wpt: update scheme-blob.sub.any.js

lib/fetch/index.js
Implements https://github.com/whatwg/fetch/commit/6128ca355952c92992180a77a02acca3b7a15f9d
Basically only 1 step changed. Some comments were updated and some variables were renamed to match the spec better.
=> fetch: update spec

test/wpt/tests/fetch/api/response/response-static-error.any.js
Adds test from https://github.com/web-platform-tests/wpt/commit/4c41b4ec55b296eef7044a7bc0dbc5fc2a1eb50d
=> wpt: update `response-static-error.any.js`

test/types/proxy-agent.test-d.ts, types/proxy-agent.d.ts
Fix for https://github.com/nodejs/undici/issues/1800
=> [types] update ProxyAgent Options (timeout)

lib/fetch/body.js
Removed a redundant condition as per the issue
Fixes: https://github.com/nodejs/undici/issues/1813
=> fetch: removal of redundant condition

lib/websocket/receiver.js, test/websocket/receive.js
Refs: https://github.com/nodejs/undici/pull/1818#discussion_r1053575150
=> fix(websocket): validate payload length received

lib/fetch/request.js
Refs: https://github.com/nodejs/undici/issues/1823
=> fix(fetch): weaker refs

lib/fetch/body.js, test/wpt/tests/fetch/api/body/cloned-any.js
Adds test from https://github.com/web-platform-tests/wpt/commit/f293f22db4fc3802b7b92f2a28078a32847c2e1a
=> wpt: add test

test/jest/interceptor.test.js
This test failed on my machine on Node v16, so I fixed it.
=> Fix broken interceptor test

docs/api/Dispatcher.md
=> doc: fix anchor links dispatcher.stream

lib/client.js
=> Use FastBuffer

lib/fetch/headers.js, test/fetch/headers.js, test/types/fetch.test-d.ts, types/fetch.d.ts
Some pretty dumb mistakes on my part 😄
=> fix(headers): clone getSetCookie list & add getSetCookie type

lib/fetch/headers.js, test/fetch/headers.js
=> fix: copy cookies when cloning haders

.github/workflows/scorecard.yml
=> workflow: add scorecard.yml

lib/core/util.js, test/fetch/formdata.js
Fixes: https://github.com/nodejs/undici/issues/1952
=> fix: improve isFormDataLike compat

lib/timers.js
Fixes: https://github.com/nodejs/undici/issues/1950
=> fix: use normal timers for delays < 1s

lib/core/util.js
Strengthen condition checking in `isStream`
Fixes: https://github.com/nodejs/undici/issues/1825
=> fix: strengthen isStream condition checking

lib/client.js, test/types/client.test-d.ts, types/client.d.ts
TypeScript type fixes, for #1949.
=> TypeScript type fixes, for #1949

lib/websocket/connection.js, lib/websocket/symbols.js, lib/websocket/websocket.js
this is needed *if* we want to implement websocketstream, which i've kinda been working on for fun
=> websocket: separate connection logic from websocket

lib/fetch/index.js, test/fetch/redirect.js
=> fix(fetch): remove assertion on request.body.source on redirect (#2027)

lib/core/util.js
v8 11.3 just landed in node core so I was able to test this, everything seems to work.
=> util: replace util.toUSVString with String.prototype.toWellFormed

lib/fetch/headers.js, test/fetch/request.js
=> fix: clear set-cookie headers

lib/fetch/request.js
Fixes https://github.com/nodejs/node/issues/47449
There's already a test for this (test/fetch/issue-node-46525.js)
=> fix: use getMaxListeners when available

lib/core/request.js, test/issue-2065.js
=> fix: set content-length when using FormData body w/ request

lib/fetch/headers.js, lib/fetch/index.js, lib/fetch/symbols.js, test/issue-2078.js
=> fix: mock fetch headers shouldn't be an array 

docs/api/Errors.md
=> docs: updated Error documentation (fixes #2090)

test/types/errors.test-d.ts, types/errors.d.ts
This PR adds missing parts of typescript definitions to match with js implementation
=> fix: update error definitions

lib/fetch/request.js, test/fetch/request.js
Fixes https://github.com/nodejs/undici/issues/2124
=> fetch: set referrer properly

docs/api/ProxyAgent.md
fixes: https://github.com/nodejs/undici/issues/2192
- update docs for proxyAgent
=> docs: add proxy agent options docs

test/proxy-agent.js
refs: https://github.com/nodejs/undici/pull/2162#issuecomment-1690460627
=> fix failing test

index.js, test/fetch/issue-2242.js
=> fix: aborting request with non-object error

README.md
As titled, adding @KhafraDev to releasers
=> Add Khaf to releasers

lib/core/util.js, lib/fetch/global.js, test/client-errors.js
Reduced the number of checks for where we know the variable is an instance of `URL`.
=> perf: improve parse-url implementation

package.json, scripts/generate-pem.js
=> test: handle npm ignore-scripts settings

test/types/connector.test-d.ts, types/connector.d.ts
- #2333
- Fix missing definition allowH2 in BuildOptions
=> fix: 🏷️ add allowH2 to BuildOptions

lib/api/readable.js, test/client-request.js
=> fix request's arrayBuffer returning uint8 instead of arraybuffer

package.json, test/fetch/bundle.js
=> fix names with esbuild

test/fetch/bundle.js
refs: https://github.com/nodejs/node/issues/50263#issuecomment-1779670104
=> add regression test

lib/client.js, lib/core/request.js, lib/core/util.js
- Make sure stream body always has an error handler.
- Make sure not to leave dangling event listeners.
=> fix: stream body handling

scripts/generate-undici-types-package-json.js
closes #2383 
LICENSE text (MIT) missing in npm module for [undici-types](https://www.npmjs.com/package/undici-types?activeTab=code)
Copy `LICENSE` to `undici-types`
- [S] Review ready
=> docs: add license to undici-types

test/fetch/http2.js
=> add additional http2 test with fetch

lib/fetch/index.js, test/mock-agent.js
Fixes #2418 
If the mock agent is enabled and the body text is `ReadableStream`, the body text is not sent correctly.
N/A
#2418
N/A
=> fix(mock-agent): send stream body

types/dispatcher.d.ts
I noticed this while reading the documentation and code.
=> fix: `onHeaders` type declaration

lib/fetch/headers.js, test/fetch/request.js
Fixes #2445
See #2445
N/A
#2445
N/A
=> fix: set-cookie clone

lib/handler/RetryHandler.js
=> refactor: remove leftovers

lib/client.js, lib/core/request.js
=> fix: dispatch error handling

lib/core/connect.js
=> feat: print attempted addresses on ConnectTimeoutError

lib/api/readable.js
=> refactor: remove some node compat

index.js
This is useful for third-party implementers using dispatcher API.
=> feat: expose parseHeader

lib/agent.js
reverts https://github.com/nodejs/undici/commit/a1a8136797dac98e97b032725295ce9ef2032b2d
oops
=> revert a1a8136

docsify/sidebar.md
Added missing Util to sidebar.
=> docs: add Util to sidebar

test/tree.js
=> chore: update tst test

types/proxy-agent.d.ts
=> types: remove unused Client and Pool types

package.json, test/cookie/cookies.js, test/cookie/global-headers.js
https://github.com/nodejs/undici/issues/2267
Port cookie tests to node test runner
Remove tap and use node test runner for the cookie suite
=> feat: port cookies tests to node runner

package.json
Update `@matteo.collina/tspl` to 0.1.1 ( https://github.com/mcollina/tspl/releases/tag/v0.1.1 )
- [S] Tested
=> Update `@matteo.collina/tspl` to 0.1.1

test/wpt/status/fetch.status.json
this test has been failing for a while. Once my other PR lands all tests we run will pass.
=> mark wpt as failing

lib/api/abort-signal.js, test/issue-2349.js, test/issue-2590.js, test/jest/mock-scope.test.js, test/node-test/abort-controller.js
=> abort request with reason if one is provided

test/node-test/balanced-pool.js, test/node-test/ca-fingerprint.js, test/node-test/client-abort.js
https://github.com/nodejs/undici/issues/2267
=> feat: port `balanced-pool`, `ca-fingerprint`, `client-abort` tests to `node:test`

test/fixtures/undici.js, test/node-test/debug.js
=> test(#2600): Flaky debug test

lib/mock/mock-utils.js, test/mock-agent.js
=> fix(mock-agent): split set-cookie

package.json, test/connect-timeout.js
=> chore: remove atomic-sleep as dev dependency

package.json, test/node-fetch/main.js
=> chore: remove delay as dev dependency

test/request-timeout.js
=> chore: fix faketimer warning in test/request-timeout.js

lib/fetch/index.js, lib/fetch/util.js
=> fix: typo clampAndCoarsenConnectionTimingInfo

lib/eventsource/eventsource.js, lib/eventsource/util.js
Fixes https://github.com/nodejs/undici/issues/2664
=> remove timers/promises import

lib/agent.js
according to biome, we can avoid this agent variable
=> chore: remove this alias in agent.js

test/node-test/debug.js
Closes #2600
Will run this multiple times by force pushing to investigate the issue.
=> fix: flaky debug test

.github/workflows/nodejs.yml
trying to fix these warnings and errors
not sure if this PR will fix them
=> fix: ci pipeline warnings

test/node-test/debug.js
While investigating the code coverage issues, I got some strange error in the debug.js tests, as for some reason the stdout was containing colored output. This PR removes potential color in stdout, so that the tests wont fail because of that. 
Also in case the debug test is again flaky, the chunks should be now logged so we can maybe investigate further. 
=> test: more information from debug tests

index.html
Well... the favicon link is changed...
=> docs: fix favicon

package.json, test/no-strict-content-length.js
=> chore: remove sinon dev dependency

lib/web/fetch/index.js
=> processBody doesn't need to return a promise

.github/workflows/nodejs.yml
shame on me. this should fix the concurrency.
=> ci: fix concurrency

lib/dispatcher/client-h1.js, lib/dispatcher/client-h2.js, lib/dispatcher/client.js
=> fix: make pipelining limit work for h2

lib/dispatcher/client-h2.js
=> fix: http2 doesn't have pipelining queue

lib/core/util.js, lib/dispatcher/client.js, lib/dispatcher/pool-base.js
=> fix: prefer queueMicrotask

package.json, test/pool.js
=> chore: remove proxyquire

package.json, test/node-test/agent.js
=> chore: remove import-fresh as devDependency

.github/workflows/nodejs.yml
=> ci: only send codecov from ubuntu and node

test/node-test/balanced-pool.js, test/node-test/unix.js
skipping via option is better than skipping via if condition
removing  obsolete test case.
=> tests: improve skip for unix.js tests, remove skipped tests

lib/web/fetch/request.js
https://github.com/nodejs/undici/commit/95c82ab48758f5ec6aa566b2d8fb0adaa6e8430f#diff-a3765b1f356bee10fc89a5e224c8a83f131e9ffeafc7d99976499b31a99125b4R561
Fix small typo in isHistoryNavigation comments # lib/web/fetch/request.js
=> chore: fix typo in isHistoryNavigation comments

lib/dispatcher/proxy-agent.js
=> fix: don't assign kAgent twice

test/client-request.js
Refs: https://github.com/nodejs/undici/issues/2949
=> try to fix windows failure

lib/web/fetch/formdata-parser.js
10%~ performance improvement in form-data parser.
=> perf: optimize collectASequenceOfBytes

test/client.js
=> Do not fail test if streams support typed arrays

test/types/dispatcher.test-d.ts, types/dispatcher.d.ts
=> [fix #2982] use DispatcherInterceptor type for Dispatcher#Compose

docs/index.html
Adds support for searching docs
=> feat:  added search input

lib/core/connect.js
=> fix error message

lib/web/websocket/receiver.js, lib/web/websocket/util.js
This reverts commit 2091dcfa1a9864dab7675be7c6bff34dbde06051.
See
- https://github.com/nodejs/node/pull/52175#issuecomment-2020665559
- https://github.com/nodejs/undici/pull/2863#issuecomment-2020746531
=> Revert "perf: reuse TextDecoder instance (#2863)"

test/retry-handler.js
=> test: remove only

.github/workflows/nightly.yml, .github/workflows/test.yml
OpenSSF scorecard "Token-permissions" score zero - #3012 
=> fix(workflows): missing top-level content.read permissions

README.md
Closes #3000 
Links to the contributing guide directly from the README making it a little bit simpler for new contributors to get involved with the project.
Added a "How to get involved" section that links to the community forums and directs to the contributing guide for those looking to contribute.
N/A
N/A
N/A
=> enhancement: link to the contributing guide from the README

test/fetch/iterators.js
=> fix: broken test

types/dispatcher.d.ts
=> fix(types): onHeaders always takes headers as an array of buffer

test/cache/cache.js, test/cache/cachestorage.js
low hanging fruit for more test coverage
=> cache: improve test coverage

lib/api/abort-signal.js, lib/api/api-connect.js, lib/api/api-pipeline.js, lib/api/api-request.js, lib/api/api-stream.js, lib/api/api-upgrade.js, lib/mock/mock-utils.js
=> fix: signal handling

README.md, docs/examples/README.md
Resolves #2202 
As referenced in issue #2202, the documentation lacks examples illustrating the integration of file streams with FormData in undici. 
Both fetch and request already have workarounds; however, these should be described for comprehensive understanding.
* Add usage example to fetch.
* Add usage example to request.
N/A
=> Mention option to pass streams into FormData

test/types/event-source-d.ts, types/eventsource.d.ts
=> fix(types): The second parameter of EventSource is optional

types/dispatcher.d.ts
=> fix: onConnect types

lib/web/websocket/receiver.js, test/websocket/issue-3202.js
=> fix parsing when receiving empty body websocket

docs/docs/best-practices/proxy.md
Fixes a small typo in the docs — the constructor is `ProxyAgent`, not `AgentProxy`.
N/A
N/A
N/A
=> docs(proxy): fix typo

lib/dispatcher/client-h2.js
https://github.com/nodejs/undici/actions/runs/8983550935/job/24673564560
=> fix: pass abort function

lib/core/connect.js, lib/web/websocket/receiver.js, lib/web/websocket/websocket.js, test/util.js
=> fix some typos

test/wpt/status/fetch.status.json
It seems, that the test is passing. I looked and all the asserts are getting "hit".
=> fetch: enable wpt test request-referrer.any.js

test/fetch/fire-and-forget.js
fix flaky test
https://github.com/nodejs/undici/actions/runs/9011187514/job/24758432831
=> test: reduce the number of requests in `fire-and-forget.js`

.github/workflows/nodejs.yml, .github/workflows/test.yml
probably will be more annoying as some flaky tests will fail...
=> ci: add node 22 in ci test matrix, use 22 for coverage

lib/web/fetch/body.js
Refs: https://github.com/nodejs/undici/pull/3262#discussion_r1600720347
=> perf: avoid buffer cloning

.github/workflows/autobahn.yml
Reverts nodejs/undici#3259
@KhafraDev
=> Revert "websocket: autobahn workflow should fail on error"

lib/web/fetch/util.js, test/fetch/issue-3334.js
=> don't append empty origin

test/fetch/response.js
This adds a regression test for #3337.
=> Add regression test for broken body

package.json
=> Update esbuild to 0.19.10

CONTRIBUTING.md
Add missing closing bracket to `Benchmarks` link in the Table of Contents in `CONTRIBUTING.md`.
Fixes this:
Add missing closing bracket to `Benchmarks` link in the Table of
Contents in `CONTRIBUTING.md`.
N/A
N/A
N/A
=> docs: fix ToC in CONTRIBUTING.md

lib/core/request.js
=> fix: cast falsy servername to null to avoid falsy inequality

lib/web/fetch/util.js
=> fix: stripURLForReferrer jsdoc in fetch logic

lib/dispatcher/proxy-agent.js
probably an artifact, when we removed the intereptors in #3399 ?
=> fix: remove kInterceptors in ProxyAgent

lib/handler/retry-handler.js
=> fix: fix codesmells in retry-handler

lib/web/cookies/parse.js
=> fix: fix jsdoc in cookies/parse.js

lib/core/tree.js
=> fix: add jsdoc in tree.js, avoiding codesmells

.github/workflows/release-create-pr.yml, .github/workflows/update-wpt.yml
=> fix: workflow commit user

lib/web/fetch/symbols.js
=> remove unused symbol

docs/examples/proxy/index.js, docs/examples/proxy/websocket.js, lib/api/abort-signal.js, lib/api/util.js, lib/core/symbols.js, lib/dispatcher/pool-stats.js, scripts/generate-pem.js, scripts/generate-undici-types-package-json.js, scripts/verifyVersion.js, test/fixtures/fetch.js, test/fixtures/undici.js, test/fixtures/websocket.js, test/jest/mock-scope.test.js, test/node-fetch/utils/server.js
adds missing `use strict` thingies into the cjs files
=> chore: use 'use strict' in cjs files

lib/web/fetch/constants.js
=> jsdoc: add jsdoc to lib/web/fetch/constants.js

lib/web/fetch/index.js
I guess this means one less promise
=> fetch: pullAlgorithm passes the async resume function through

package.json
Attempts to fix CI problem when testing TS on v6.x branch
=> deps(dev): update @types/node

test/issue-2283.js
closes #2283 as it shows that the bug is non existent
=> test: add test to ensure full type when parsing multipart/form-data'

types/webidl.d.ts
=> types: fix return type of WebidlUtil.Type

test/http2.js
the error was changed between v22.9.0 and v22.10.0
@Uzlopak @metcoder95
=> fix http2 test

test/fetch/issue-3767.js
refs https://github.com/nodejs/undici/issues/3767
=> add unsafe-url referrerPolicy test

test/fetch/long-lived-abort-controller.js
=> disable failing test

lib/web/fetch/headers.js, lib/web/fetch/webidl.js, test/fetch/headers.js, test/webidl/errors.js
=> Headers webidl errors

docs/docs/api/Dispatcher.md
Update links so they don't 404 to the old URL.
Docs
The current links 404 to a non existent page.
Update URLs to the correct path.
N/A
N/A
N/A
=> Update Dispatch.md to Dispatcher.md

lib/dispatcher/client-h1.js
Super unlikely but technically possible...
=> fix: missing error handler

lib/interceptor/cache.js
=> fix: cache rm unused branch

README.md
This adds a support schedule aligned with the one of Node.js.
=> Add support schedule

lib/interceptor/cache.js
=> cache: do not set undefined etag

lib/interceptor/cache.js, test/interceptors/cache.js
This fixes a regression introduced in https://github.com/nodejs/undici/pull/3925.
=> correctly set if-none-match

benchmarks/server-http2.js
=> fix: bad response on h2 server

test/issue-3356.js
The tests seems to be quite flaky in CIGTM, still trying to figure out why
without much luck.
Skiping it for nw until we have a better understanding of the issue.
=> test: ignore test for CITGM

.github/workflows/update-cache-tests.yml
Re https://github.com/nodejs/undici/commit/b55476909055bf698cd8eeabe081daa1cc6d9d4c and https://github.com/nodejs/undici/actions/runs/12787090367/job/35645558849
=> Fix typo in update cache tests action

lib/web/fetch/body.js
apply recommended change in https://github.com/nodejs/undici/commit/c2d78cd19fe4f4c621424491e26ce299e65e934a#r151622070
by @siimots
=> fix: fetch body fallback random number generation

docs/index.html
This pull request add dark/light mode themes functionality
rel: #4037
=> feat(docs): button to switch dark and light mode

test/wpt/start-FileAPI.mjs, test/wpt/start-cacheStorage.mjs, test/wpt/start-eventsource.mjs, test/wpt/start-fetch.mjs, test/wpt/start-mimesniff.mjs, test/wpt/start-websockets.mjs
=> [v6.x] fix wpts on windows

lib/core/util.js, lib/mock/mock-utils.js, lib/web/websocket/util.js
Small PR that limits string splits to exit earlier
=> lib: limit string split length

.github/PULL_REQUEST_TEMPLATE.md
Linking to the certificate of origin in the pull request template.
Currently the "cert" link goes to the top of `CONTRIBUTING.md`, but it's possible to deep-link to the certificate of origin section.
Change link from top of `CONTRIBUTING.md` to the relevant section.
N/A
N/A
=> docs/PULL_REQUEST_TEMPLATE: deep-link to certificate of origin

lib/dispatcher/client-h2.js, test/http2.js
=> feat(h2): emit connectionerror upon GOAWAY frame

lib/cache/sqlite-cache-store.js
=> apply some sqlite pragma optimizations

lib/core/connect.js, lib/web/fetch/body.js, lib/web/fetch/dispatcher-weakref.js, test/fetch/fire-and-forget.js, test/fetch/long-lived-abort-controller.js
=> remove finalizationregistry workaround

test/types/index.test-d.ts, types/dispatcher.d.ts, types/handlers.d.ts
Fix RedirectHandler type #4229 
Missed in #1338 
=> Fixed RedirectHandler type

lib/web/fetch/util.js
=> fetch: add missing new operator on TypeError instantiation in readAllBytes

README.md
=> chore(doc): update undici vs fetch

lib/interceptor/dump.js, test/interceptors/dump-interceptor.js
Fix bug where `dump` interceptor does not handle eager network errors.
=> fix(inteceptor/dump): handle preemptive network errors

lib/interceptor/cache.js, lib/util/cache.js
Its more like a chore Pr. It feels unnatural, that we used here BE. Everywhere else we use AE
=> cache: change normaliseHeaders to normalizeHeaders

.github/workflows/nodejs-shared.yml
Refs: https://github.com/nodejs/undici/pull/4276
Refs: https://github.com/nodejs/node/issues/58865
Previous test failures should have been addressed by upstream Node.js fixes.
N/A
N/A
=> ci: reenable shared builtin CI tests

types/diagnostics-channel.d.ts
=> types: remove type Error = unknown for diagnostic-channels

test/fetch/long-lived-abort-controller.js
=> test: remove skip check for long-lived-abort-controller test (was flaky 10 months ago)

lib/web/eventsource/eventsource.js, lib/web/eventsource/util.js
Removes the only place in eventsource where I used a promise...
=> eventsource: remove promise for #reconnect method

lib/core/errors.js, lib/mock/mock-errors.js
=> Backport 4472 to v6.x

lib/dispatcher/dispatcher-base.js, lib/dispatcher/pool-base.js, test/pool.js
no constructor means afaik faster instantiation of the objects
=> chore: pool and dispatcherbase dont need constructor, use no array helper functions

lib/web/websocket/connection.js, lib/web/websocket/stream/websocketstream.js, lib/web/websocket/websocket.js, test/websocket/issue-4273.js, test/websocket/issue-4487.js
=> websocket: always emit error event

test/utils/redirecting-servers.js
we support node 20 and above. So this typecheck is unnecessary
=> test: remove node20 version check

test/connect-pre-shared-session.js, test/fetch/abort.js, test/fetch/headers.js, test/interceptors/retry.js
I detected this mismatches with a modified tspl https://github.com/mcollina/tspl/pull/13
=> test: fix plans

lib/core/util.js, lib/dispatcher/dispatcher-base.js, lib/dispatcher/pool-base.js, lib/interceptor/cache.js, lib/mock/mock-utils.js, lib/mock/snapshot-agent.js
=> fix: keep promise chains intact

docs/examples/README.md, test/node-test/unix.js
Adds some example documentation on unix domain sockets to partially address #2970
- [x ] Tested
=> docs: unix socket add-on
