nodejs/undici

lib/fetch/request.js
lib/fetch/util.js
test/fetch/request.js

perf: Improve `normalizeMethod`

---

lib/fetch/headers.js
lib/fetch/request.js

For performance improvement:
1. Do not call `Object.keys` more than once.
2. When copying the `headersList`, use `HeadersList` instead of `Headers`.
3. Avoid call `HeadersList` if init["headers"] is not undefined
4. When looping through headers, use `HeadersList` instead of `Headers`, which eliminates the sorting process and is faster.
```js
// bench.js
const { Request } = require(".");
const benchmark = require("benchmark");
const suite = new benchmark.Suite();
const headers = {
"Content-Type": "application/json",
"X-Content-Type": "application/json",
Date: "Wed, 01 Nov 2023 00:00:00 GMT",
"X-NodeJS-Version": "v21.1.0",
"Powered-By": "NodeJS",
"Content-Encoding": "gzip",
"Set-Cookie": "__Secure-ID=123; Secure; Domain=example.com",
"Content-Length": "150",
Vary: "Accept-Encoding, Accept, …
```

perf(request): optimize if headers are given

---

lib/agent.js
lib/api/readable.js
lib/client.js
lib/fetch/body.js
lib/fetch/index.js
lib/pool-base.js
lib/proxy-agent.js

Why do we use so much async await?

chore: less async await

---

test/types/fetch.test-d.ts
types/fetch.d.ts

Fixes #2448.
N/A
- Add the missing `null` type to the `signal` property in `RequestInit`

fix: Add `null` type to `signal` in `RequestInit`

---

lib/fetch/dataURL.js
test/fetch/data-uri.js

fix: correctly handle data URL with hashes.

---

lib/fetch/index.js
test/fetch/resource-timing.js

Fixes #2476 
Explained in #2476
Fix property, add test verifying fixed behavior
N/A
Performance entry now includes decodedBodySize, encodedBodySize and transferSize values

fix: check response for timinginfo allow flag

---

lib/fetch/request.js

If the integrity is null, it is safe to delete it because it will be converted to the string 'null' by `DOMString`.

refactor: better integrity check

---

lib/proxy-agent.js

Currently the following code fails with a non 200 status tunneling issue:
```
await fetch(url, {
dispatcher: new ProxyAgent(`http://<username>:<password>@myproxyurl.com:9000`)
})
```
This is because an inline username/password is ignored, and no auth header is created. This PR creates a Basic 'proxy-authorization' header if an inline username & password is provided.
`https-proxy-agent` implements this for node-fetch: https://github.com/TooTallNate/proxy-agents/blob/main/packages/http-proxy-agent/src/index.ts#L102
* Add proxy-authorization header when an inline username/password is provided (opts.token takes precedence)
* Improved the non 200 error message to include the `statusCode`
* Can now use inline URL auth
See above

fix: Added support for inline URL username:password proxy auth

---

benchmarks/benchmark-https.js
benchmarks/benchmark.js
docs/api/BalancedPool.md
lib/client.js
lib/fetch/dataURL.js
lib/fetch/index.js
lib/handler/RedirectHandler.js
test/balanced-pool.js
test/http2.js
test/pool.js

chore: fix typo

---

lib/handler/RetryHandler.js
test/retry-handler.js

N/A
`RetryHandler` works with requests that are both meant and not meant to be retried, as indicated in the `statusCodes` option. In its current state, any non-success HTTP status (statuses greater than 299) return a `RequestRetryError`.
Check user-provided status codes to see if `RetryHandler` should handle an HTTP error or pass down to next handler
N/A
When a response has a non-success status code, we check to see if this is a status code that the user wanted to retry. If it was, the handler aborts with a `RequestRetryError`. If the user was not retrying, the next handler is called.
The bug fix could be seen as a breaking change

Expose HTTP errors that are not meant to be retried

---

lib/api/readable.js
lib/client.js
test/readable.test.js

fix: stream error timings

---

lib/fetch/index.js

For performance improvement:
1. `HeadersList` directly to avoid object creation.
2. Avoid `String#toLowserCase` calls.

perf(fetch): optimize call `dispatch`

---

lib/core/errors.js

class, the `Error.captureStackTrace` is not necessary since the stack trace is automatically collected by the Error constructor.
source: https://github.com/v8/v8/blob/8d0ffc5559c0aabe6551096d3e52386feec0aea4/src/execution/messages.cc#L636-L645
Within the Error constructor, it is set to skip frames above the function specified in `new.target`. This is the same behavior as specifying a custom class name (AbortError) for `Error.captureStackTrace`.
source: https://github.com/v8/v8/blob/8d0ffc5559c0aabe6551096d3e52386feec0aea4/src/execution/messages.cc#L550-L556

refactor: remove Error.captureStackTrace

---

lib/client.js
lib/core/util.js
lib/fetch/body.js
lib/fetch/headers.js
lib/fetch/index.js
lib/fetch/response.js
lib/fetch/util.js

```js
import { fetch } from "./index.js";
const toLowerCase = String.prototype.toLowerCase
let call = 0
String.prototype.toLowerCase = function () {
++call
return toLowerCase.call(this)
}
await fetch("https://google.com")
// before -> 75
// after -> 4
console.log(call)
```

perf: reduce `String#toLowerCase` call

---

lib/api/readable.js

Closes #2505
use `Buffer.concat` length hints.

perf: optimize consumeEnd

---

lib/core/tree.js

```js
import { bench, group, run } from 'mitata'
import {
wellknownHeaderNames,
headerNameLowerCasedRecord
} from '../lib/core/constants.js'
import { TernarySearchTree } from '../lib/core/tree.js'
// copy new implementation
import { TernarySearchTree2 } from '../lib/core/tree2.js'
// avoid JIT bias
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
group('built', () => {
bench('current', () => {
const tst = new TernarySearchTree()
for (let i = 0; i < wellknownHeaderNames.length; ++i) {
const key = wellknownHeaderNames[i].toLowerCase()
tst.insert(Buffer.from(key), key)
}
})
bench('new', () => {
const tst = new TernarySearchTree2()
for (let i = 0; i < wellknownHeaderNames.length; ++i) {
const key = …
```

perf: reduce tst built time

---

build/wasm.js

This allows for the WASM artifacts to be built elsewhere than only in the alpine-based node container.
Pre-built WASM artifacts are often a no-go when creating packages for Linux distributions; they need to be rebuilt from source on trusted build system by the package maintainer. This PR allows me to easily tweak the build parameters and flags for the WASM build to do just that.
The `build/wasm.js` script now checks for presence and content of several related environment variables (`WASM_CC`, `WASM_CFLAGS`, `WASM_LDFLAGS`, and `WASM_LDLIBS`; the names mirror those traditionally used in C Makefiles). If present, content of these variables override some of the compilation flags that are directly dependent on the build environment (i.e. `--target` and `--sysroot`).
- [S] Benchmarked …

feat: allow customization of build environment

---

docs/api/Util.md
index.js
lib/core/util.js
test/types/util.test-d.ts
types/index.d.ts
types/util.d.ts

This is useful when processing header name.

feat: expose headerNameToString

---

lib/agent.js
lib/mock/mock-agent.js

Given https://github.com/nodejs/node/issues/49344 and https://github.com/nodejs/node/issues/47748, it's better to reconsider our usage of `FinalizationRegistry` in `Agent`.

Remove FinalizationRegistry from Agent

---

lib/agent.js

Followup from https://github.com/nodejs/undici/pull/2530

Clear all timeout on destroy and close

---

test/types/agent.test-d.ts
test/types/dispatcher.test-d.ts
types/balanced-pool.d.ts
types/client.d.ts
types/dispatcher.d.ts
types/pool.d.ts

[HTTP CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) requires host and port that already appear to be derived from the `origin` field. It's simply not declared in a type. Furthermore, `agent.connect()` currently fails without the `origin` field in [this line](https://github.com/nodejs/undici/blob/0c4c4504852c71dac1a6eb8dfae0f2411b6f2fc6/lib/agent.js#L90).
The `origin` field is being added to the `ConnectOptions`.
This should actually be a required field, but that would make the API non-backward compatible.
Fixes https://github.com/nodejs/undici/issues/2531

ConnectOptions should include 'origin' field

---

lib/fetch/index.js
lib/fetch/request.js

perf: avoid toLowerCase call

---

lib/compat/dispatcher-weakref.js
lib/fetch/request.js

Fix flaky CI test of `jsdom-abortcontroller-1910-1464495619.js`

fix: call explicitly unregister

---

lib/fetch/body.js
test/fetch/response.js

The Content-Type is not strictly checked.
If `multipart/form-data` or `application/x-www-form-urlencoded` is included, Error is not thrown.
```shell
> $ node
Welcome to Node.js v21.5.0.
Type ".help" for more information.
> [...await (new Response("x=y", { headers: { "content-type": "application/x-www-form-urlencoded_" } }).formData())]
[ [ 'x', 'y' ] ]
```

fix: check the content-type of invalid formData

---

README.md
examples/README.md
examples/request.js
test/examples.js

Help people to get started smoothly by adding some new examples of making basic sorts of requests using `undici.request()`.
Some examples of mistakes I have made at various times using undici that I'm aiming to help others to avoid with this:
* passing an object to `options.body`, instead of stringified JSON,
* using the incorrect case for http verbs,
* missing the necessary content-types for JSON and form POST requests.
* attempting to decode an empty body as JSON
Extended `examples/request.js` with additional examples, and added `test/examples.js` to test them.
n/a
n/a
n/adeprecations (removed features) here -->

Add request examples.

---

lib/fetch/index.js
test/fetch/redirect.js

https://github.com/nodejs/undici/issues/2543
N/A
Fixes https://github.com/nodejs/undici/issues/2543.
N/A

fix(fetch): do not abort fetch on redirect

---

lib/proxy-agent.js
test/proxy-agent.js

Fixes #2542 
FYI @pimterry I believe HttpToolkit isn't validating Host headers when accepting request instrumentation through proxy. 
According to the RFC, the Host header must be the same as the CONNECT one. If an invalid Host is provided, the proxy must return 400 (as happening the linked issue)

lib: fix Host header when CONNECT ProxyAgent

---

lib/fetch/dataURL.js

<details>
```js
import { bench, group, run } from "mitata";
// avoid JIT bias
bench("noop", () => {});
bench("noop", () => {});
bench("noop", () => {});
bench("noop", () => {});
bench("noop", () => {});
bench("noop", () => {});
/**
* @param {number} byte
*/
function isHexCharByte(byte) {
// 0-9 A-F a-f
return (
(byte >= 0x30 && byte <= 0x39) ||
(byte >= 0x41 && byte <= 0x46) ||
(byte >= 0x61 && byte <= 0x66)
);
}
/**
* @param {number} byte
*/
function hexByteToNumber(byte) {
return (
// 0-9
byte >= 0x30 && byte <= 0x39
? byte - 48
: // Convert to uppercase
// ((byte & 0xDF) - 65) + 10
(byte & 0xdf) - 55
);
}
function percentDecode(input) {
const length = input.length;
// 1. Let output be an empty byte sequence.
/** @type {Uint8Array} */
const output = …
```

perf: Improve percentDecode

---

lib/fetch/util.js
test/fetch/util.js

#2441 
`[A-z]` will also match `[\]^_` which are invalid base64 characters.
The current regex `[A-z0-9+/]{1}.*={0,2})` will match the initial valid characters in the hash group, even if the rest of the string contains an invalid Base64 string like **zifp5hE1Xl5LQQqQz[]Bq/iaq9Wb6jVb/** where the matched part is **zifp5hE1Xl5LQQqQz**
change the hash group to `(?<hash>[A-Za-z0-9+/]+={0,2}(?=\s|$))` where `[A-Za-z0-9+/]`+ are valid base64 chars and `(?=\s|$))` is a positive lookahead assertion.
`( +[!-~]*)` looks for a group of printable ASCII chars as documented in https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1

Fix parseHashWithOptions regex

---

package.json
test/diagnostics-channel/connect-error.js
test/diagnostics-channel/error.js
test/diagnostics-channel/get.js
test/diagnostics-channel/post-stream.js
test/diagnostics-channel/post.js

#2267
Port diagnostic-channel tests to node test runner
Remove tap and use node test runner for the diagnostic-channel suite
N/A
N/A
None

feat: port diagnostic-channel tests to node test runner

---

lib/fetch/dataURL.js

Fixes #2579 
fix was easier than I expected, I just reverted the changes here for the most part.

fix data url test

---

lib/fetch/request.js
lib/fetch/util.js

<details>
```js
import { bench, run } from 'mitata'
import { Request } from '../index.js'
// avoid JIT bias
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
const input = "https://localhost/post"
const method = "post"
bench('new Request(input, { method })', () => {
return new Request(input, { method })
})
await new Promise((resolve) => setTimeout(resolve, 7000))
await run()
```
</details>
- *main*
```
benchmark                           time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------------------- -----------------------------
new Request(input, { method })   12.47 µs/iter      (8.5 µs … …
```

perf: bypass method validation

---

lib/fetch/file.js
lib/fetch/response.js
lib/fetch/webidl.js
lib/websocket/websocket.js
test/fetch/file.js
test/webidl/converters.js
test/websocket/send.js

From [BufferSource]( https://webidl.spec.whatwg.org/#BufferSource) of webidl spec.
> Note: [[AllowShared](https://webidl.spec.whatwg.org/#AllowShared)] cannot be used with [BufferSource](https://webidl.spec.whatwg.org/#BufferSource) as [ArrayBuffer](https://webidl.spec.whatwg.org/#idl-ArrayBuffer) does not support it. Use [AllowSharedBufferSource](https://webidl.spec.whatwg.org/#AllowSharedBufferSource) instead.
BufferSource does not contain SharedArrayBuffer.

fix: use isArrayBuffer instead of isAnyArrayBuffer

---

lib/cache/cache.js
package.json
test/wpt/server/server.mjs
test/wpt/status/service-workers/cache-storage.status.json

CacheStorage is weird. All tests pass again.

cacheStorage: fix bugs make wpts pass

---

index-fetch.js
test/fetch/issue-2242.js

Fixes: https://github.com/nodejs/node/issues/49557.
Refs: #2243.

fix: non-object error in abort throws bad error

---

test/fetch/407-statuscode-window-null.js
test/fetch/abort.js
test/fetch/abort2.js
test/fetch/client-fetch.js
test/fetch/content-length.js
test/fetch/cookies.js
test/fetch/encoding.js
test/fetch/fetch-leak.js
test/fetch/fetch-timeouts.js
test/fetch/headers.js
test/fetch/http2.js
test/fetch/integrity.js
test/fetch/issue-2009.js
test/fetch/issue-2021.js
test/fetch/issue-2171.js
test/fetch/issue-2318.js
test/fetch/redirect.js
test/fetch/relative-url.js
test/fetch/resource-timing.js
test/fetch/user-agent.js
test/node-test/abort-controller.js
test/node-test/abort-event-emitter.js
test/node-test/agent.js
test/node-test/async_hooks.js
test/node-test/debug.js
test/utils/node-http.js

Context: https://github.com/nodejs/undici/pull/2591#discussion_r1443658866
fix calls callback-style `server.clos`e in`t.after` to return a `Promise`

fix: add test helper for closing server as promise

---

lib/cache/cache.js

The biggest benefit can be seen from Cache.match where we can now limit the number of responses fetched, instead of returning the entire list while match only requires the first.

cacheStorage: separate matchAll logic

---

index.js
lib/fetch/index.js

- crypto check is done directly in WebSocket now, it's not needed anymore
- I don't think we need to lazy load fetch anymore?
- default the second argument to `undefined` in fetch because we don't need it to be an object

cleanup index

---

.github/workflows/nodejs.yml

Not 100% sure if it was pinned deliberately earlier - there are several other things that are pinned to major only, and I think that's fine. When this is pinned, it might sometimes not receive new versions of Node.js (as the release dates are cached inside the action, as opposed to getting resolved each time).
For some reason, dependabot did not open a PR here 🤷

ci: unpin nodejs workflow version

---

lib/client.js
test/http2.js

fix: h2 hang issue with empty body

---

README.md
benchmarks/benchmark.js
package.json

This patch was passed by @Ethan-Arrowood ;).

Add more libraries to benchmarks

---

test/client-connect.js
test/client-errors.js
test/node-test/async_hooks.js
test/node-test/client-connect.js
test/node-test/client-dispatch.js
test/node-test/client-errors.js

https://github.com/nodejs/undici/issues/2267

feat: port `client-connect`, `client-dispatch`, `client-errors` test to `node:test`

---

test/wpt/runner/runner.mjs
test/wpt/runner/worker.mjs
test/wpt/status/fetch.status.json

exit with 1 if WPT runner has unexpected errors

---

test/wpt/runner/runner.mjs

It was confusing to see the serialized empty object. I was thinking, that I have put an console log somewhere and forgot to remove it.
before:
after:

fix: hide statusOutput if empty in handleRunnerCompletion

---

docs/api/Debug.md

There was a copy&paste error in the snippet for the `websocket` flag.

docs: Fix typo in Debug.md

---

lib/cache/cache.js
lib/cache/cachestorage.js
lib/fetch/request.js
test/fetch/request.js

fix(cache): set AbortSignal

---

lib/api/readable.js
test/node-test/large-body.js

fix: readable body

---

examples/proxy/index.js
examples/proxy/websocket.js

I have attached a websocket example

add webSocket example

---

package.json
test/http2.js

Removes semver as dev dependency

chore: remove semver as dev dependency

---

test/issue-2349.js

removing the console.log and rewriting using node core test runner.

chore: reduce noise in test-logs test/issue-2349.js

---

test/client-node-max-header-size.js

Does not print the output of the execSync call into the console. Also refactored to use node core test runner.

chore: reduce noise in test logs test/client-node-max-header-size.js

---

lib/cache/cache.js
lib/fetch/index.js
lib/fetch/request.js
lib/fetch/response.js
test/fetch/response.js

refactor: use fromInnerResponse

---

lib/fetch/index.js
lib/fetch/util.js
test/node-fetch/main.js

Closes #1091 
Closes #2128
Closes #2603 

fix: support deflate raw responses

---

lib/client.js
lib/core/request.js
lib/core/tree.js
lib/core/util.js
lib/eventsource/eventsource-stream.js
lib/fetch/body.js
lib/fetch/file.js
lib/fetch/index.js
lib/fetch/response.js
lib/handler/RetryHandler.js
lib/websocket/receiver.js
lib/websocket/util.js

solved various imho valid findings by biome

chore: fix various codesmells

---

lib/agent.js
lib/api/api-connect.js
lib/api/api-pipeline.js
lib/api/api-request.js
lib/api/api-stream.js
lib/api/api-upgrade.js
lib/balanced-pool.js
lib/client.js
lib/core/util.js
lib/fetch/response.js
lib/handler/RetryHandler.js
lib/mock/mock-agent.js
lib/pool.js
lib/proxy-agent.js
lib/timers.js

While experimenting with biome, I saw, that it is finding the places, where we can use optional chaining.

chore: use optional chaining

---

lib/fetch/index.js
lib/pool.js

as discussed in #2660 these two places were hot in the flamegraphs. 

chore: small perf improvements

---

lib/fetch/body.js
lib/fetch/dataURL.js
lib/fetch/index.js
lib/fetch/util.js

https://github.com/whatwg/fetch/commit/5eaaf662dc4fea196c5d32609cc5a13e6ea98bf2
yeah

implement spec changes from a while ago

---

lib/websocket/receiver.js
test/websocket/issue-2679.js

Fixes #2679 (an incredibly well-written issue that made this issue infinitely easier to fix, tysm)
The issue is (afaict, I haven't worked on websocket in a while...) is that the closing code is optional, but we would always allocate a 2-byte body, thereby sending a buffer containing (0x0, 0x0) which would then get interpreted as a 0 status code, which is invalid.

websocket: fix close when no closing code is received

---

test/client-keep-alive.js

the keep alive test suite is flaky.
I increased the timeout to 5 seconds. Before it was 3 seconds. On my machine, it sometimes takes 2 seconds. on a stressed github runner it fails because suddenly the 2 seconds become 3 seconds.

fix: make ci less flaky

---

lib/fetch/webidl.js
test/cookie/cookies.js

It is very strange, that in case of strict: false brandCheck would not throw, but in strict cases it would throw. 
We use the non strict brandCheck e.g.
https://github.com/nodejs/undici/blob/0808a721570baaa10e6386a9e50bd34278814afe/lib/cookies/index.js#L56
The non strict check is basically a no op, as nothing happens with the result. I assume this was just an oversight. 
I would actually recommend for performance reasons to implement a webidl.brandCheckLax (or something like that) and make webidl.brandCheck only handle strict cases.

fix: webidl.brandcheck non strict should throw

---

index-fetch.js

I would actually recommend to rename index-fetch.js to index-node.js as it is not only exposing fetch but also Websocket and now EventSource. 
But this would mean that we also have to patch the dependency updater for undici in nodejs
This is afaik blocking https://github.com/nodejs/node/pull/51575

fix: expose EventSource for nodejs

---

lib/fetch/index.js
test/fetch/pull-dont-push.js
test/wpt/runner/runner.mjs

Fixes https://github.com/nodejs/undici/issues/2697

Fix broken test on linux

---

lib/fetch/index.js

https://developer.mozilla.org/en-US/docs/Web/API/ReadableByteStreamController/desiredSize
> The value will be null if the stream has errored and 0 if it is closed.
<s>So when the stream was closed we tried to read again from it. </s>
<s>Well... at this point i dont know...</s>
I guess the problem was, that the readable stream can get suspended. So when the readable stream is unsuspended, and pull gets called a second time, than we  try to get again a reader. But you can have only one reader on the stream, thus it breaks. Now it gets the reader only once.

fix: fix the linux patch

---

lib/fetch/headers.js

<details>
```js
import { bench, run } from 'mitata'
import { Headers } from '../lib/fetch/headers.js'
import symbols from '../lib/core/symbols.js'
const headers = new Headers(
[
'Sec-CH-Prefers-Color-Scheme',
'Keep-Alive',
'TE',
'Sec-CH-UA-Arch',
'Max-Forwards',
'DPR',
'Expect',
'Tk',
'DNT',
'Link',
'Timing-Allow-Origin',
'Device-Memory',
'Alt-Svc',
'Authorization'
].map((v) => [v, ''])
)
const headersList = headers[symbols.kHeadersList]
const kHeadersSortedMap = Reflect.ownKeys(headersList).find(
(c) => String(c) === 'Symbol(headers map sorted)'
)
bench('Headers@@iterator', () => {
headersList[kHeadersSortedMap] = null
return [...headers]
})
await run()
```
</details>
- main
```
benchmark              time (avg)             (min … max)       p75 …
```

perf: use insertion sort algorithm

---

.github/workflows/nodejs.yml

@mcollina 
This change ensures that the node tests run when a pr gets merged into main.

fix: run node tests on merge

---

test/fetch/pull-dont-push.js

Because of the use of t.diagnostics the github overview for affected files in PRs is containing annotations. See screenshot

test: remove t.diagnostics() calls in push-dont-push.js test

---

lib/client.js
test/http2.js

- Closes #2704
- refactor: remove redundant checks
- fix: handle half-closed states

fix: HTTP2 tweaks

---

test/cookie/cookies.js

Check against the specific error to ensue te error is not thrown for another reason

test: improve cookie tests

---

test/fetch/fetch-url-after-redirect.js

Closes #2520 
The current behaviour is the one the issuer expected?!

test: response.url after redirect is set to target url

---

lib/core/util.js
lib/fetch/formdata.js

This step is duplicated because the webidl converter USVString has already converted it to a scalar value string.
Since we are doing the same thing, we will remove it and improve performance.
Script from #2560
```
Benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• append FormData
------------------------------------------------- -----------------------------
current     7,743 ns/iter   (5,500 ns … 1,875 µs)  7,000 ns   27.9 µs  158.7 µs
new        545.65 ns/iter  (457.76 ns … 1,452 ns) 553.71 ns  1,006 ns  1,452 ns
summary for append FormData
new
14.19x faster than current
• set FormData
------------------------------------------------- -----------------------------
current …
```

perf: remove redundant operation in FormData

---

lib/core/request.js
test/request.js

Resolves #2700 
Improve flexibility and user expirience by allowing directly passing iterable objects as headers to `undici.request`.  
It will add support for [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers), [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and custom objects with [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) that yields the key-value pairs.
* add for..of iterating in core/request.js
* Support for iterable object headers
N/A
N/A

Add support for passing iterable objects as headers

---

build/wasm.js
lib/fetch/index.js

When using the loader for external builtins, `esbuildDetection` is undefined. This commit defines `__UNDICI_IS_NODE__` on `globalThis` in the loader and deletes it after loading Undici. `esbuildDetection` has also been extracted as a variable at the top level of the module, to support deleting `__UNDICI_IS_NODE__` on `globalThis` to avoid polluting the global namespace.
Follow up of #2643.

chore: refine esbuild & node detection

---

test/client-connect.js
test/client-pipeline.js
test/client-request.js
test/client-stream.js
test/client-timeout.js
test/client-upgrade.js
test/client.js
test/close-and-destroy.js
test/connect-timeout.js
test/content-length.js
test/headers-as-array.js
test/http2.js
test/invalid-headers.js
test/issue-810.js
test/max-response-size.js
test/mock-agent.js
test/mock-client.js
test/mock-errors.js
test/mock-interceptor.js
test/mock-pool.js
test/mock-scope.js
test/parser-issues.js
test/pool.js
test/request-crlf.js
test/request-timeout.js
test/socket-timeout.js
test/utils/esm-wrapper.mjs
test/wpt/tests/resources/testharness.js

This PR replaces t.type with t.ok and instanceof calls, as node:assert and tspl does not have a type() check.

test: replace t.type with t.ok and instanceof

---

lib/fetch/index.js

ref: https://github.com/nodejs/undici/commit/87a48113f1f68f60aa09abb07276d7c35467c663#r138446550
If we set the strategy correctly as the second parameter, the test starts to fail.

remove useless options in web streams

---

docs/api/DiagnosticsChannel.md
docs/api/Dispatcher.md
docs/api/RedirectHandler.md
docs/api/RetryHandler.md
lib/client.js
lib/core/diagnostics.js
lib/core/request.js
lib/core/util.js
lib/fetch/index.js
lib/handler/DecoratorHandler.js
lib/handler/RedirectHandler.js
lib/handler/RetryHandler.js
test/http2.js
test/jest/interceptor.test.js
test/mock-agent.js
test/node-test/client-dispatch.js
test/node-test/diagnostics-channel/post-stream.js
test/node-test/diagnostics-channel/post.js
test/node-test/util.js
test/retry-handler.js
types/dispatcher.d.ts

onBodySent on onRequestSent are footguns that easily cause bugs
when implementing logic will send multiple requests, e.g. redirect
and retry.
To achieve similar functionality wrap body into a stream and listen
to 'data' and 'end' events.
Refs: https://github.com/nodejs/undici/issues/2722

remove anti-pattern dispatcher hooks

---

test/client-head-reset-override.js
test/client-post.js
test/client-reconnect.js
test/client-unref.js
test/client-write-max-listeners.js
test/connect-errconnect.js
test/fetch/issue-2294-patch-method.js
test/issue-1670.js
test/issue-2065.js

Is this correct transformed? 
In a follow up PR I will migrate all tests from tap to the native test runner ;).

chore: migrate a batch of tests to node test runner no. 1

---

test/client-connect.js
test/client-idempotent-body.js
test/client-keep-alive.js
test/dispatcher.js
test/errors.js
test/examples.js
test/headers-as-array.js
test/headers-crlf.js
test/http-100.js
test/inflight-and-close.js

a batch of tests migrated to the native test runner

chore: migrate a batch of tests to node test runner no. 2

---

test/client-pipeline.js
test/client-pipelining.js
test/client-timeout.js
test/client-upgrade.js
test/get-head-body.js
test/http2-alpn.js
test/http2.js
test/readable.test.js
test/request.js

chore: migrate a batch of tests to node test runner no. 8

---

lib/fetch/formdata.js
lib/fetch/headers.js
lib/fetch/util.js
lib/fetch/webidl.js
test/fetch/headers.js

Use the same prototype instead of generating a prototype each one.
Other implementations (browsers) use the same prototype.
Note: This benchmark is intended to measure the generation time of iterator.
<details>
```js
import { bench, run, group } from "mitata";
// new
import { Headers } from "../lib/fetch/headers.js";
// current
import { Headers as Headers2 } from "../lib/fetch/headers2.js";
import symbols from "../lib/core/symbols.js";
// new
import { FormData } from "../lib/fetch/formdata.js";
// current
import { FormData as FormData2 } from "../lib/fetch/formdata2.js";
group("Headers@@iterator", () => {
const newHeaders = new Headers();
const newHeadersList = newHeaders[symbols.kHeadersList];
const currentHeaders = new Headers2();
const …
```

perf: always use the same prototype Iterator

---

examples/proxy/proxy.js

Currently we have http-errors in the dependency tree because we use docsify. If we ever remove docsify, the proxy example would break.

chore: remove usage of http-errors in proxy example

---

.npmignore
package.json

.npmignore was useless, because package.json contained files attribute. Now .npmignore is source of truth.
before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ npm publish --dry-run 
npm notice 
npm notice 📦  undici@6.6.2
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                                   
npm notice 16.7kB README.md                                 
npm notice 2.8kB  docs/api/Agent.md                         
npm notice 8.3kB  docs/api/api-lifecycle.md                 
npm notice 2.8kB  docs/api/BalancedPool.md                  
npm notice 1.1kB  docs/api/CacheStorage.md                  
npm notice 10.8kB docs/api/Client.md                        
npm notice 3.5kB  docs/api/Connector.md                     
npm notice 1.1kB …
```

fix: dont ship wasm files of llhttp via npm

---

lib/core/tree.js

Reduce tree build time and improve module loading time.
Script from #2517
```
benchmark      time (avg)             (min … max)       p75       p99      p999
------------------------------------------------- -----------------------------
• built
------------------------------------------------- -----------------------------
current     76.94 µs/iter    (58.1 µs … 1,168 µs)   73.3 µs    279 µs  503.4 µs
new         59.77 µs/iter    (48.8 µs … 570.2 µs)   56.9 µs  197.8 µs    384 µs
summary for built
new
1.29x faster than current
```

perf(tree): avoid recursive calls

---

test/node-test/debug.js

As long https://github.com/nodejs/node/issues/51766 is not resolved we should skip the tests on node 21.6.2 and windows.
When this PR is merged, I should mention in the node issue, that they have to set skip to false to reproduce this issue when running the test (even though it should be obvious).

tests: skip test/node-test/debug on node 21.6.2 and windows

---

test/cookie/global-headers.js
test/fetch/http2.js
test/gc.js
test/node-test/autoselectfamily.js
test/node-test/diagnostics-channel/connect-error.js
test/node-test/diagnostics-channel/error.js
test/node-test/diagnostics-channel/get.js
test/node-test/diagnostics-channel/post-stream.js
test/node-test/diagnostics-channel/post.js

This is an opinionated change. I like to see in the test runner output if a test was skipped or not. So it is possible to see how many of the tests were skipped. If we just call skip and then process.exit() it does not show that we skipped 1 or 10 tests.
Also removed version check for node 16.

chore: improve usage of skip in tests

---

lib/mock/mock-utils.js
test/mock-agent.js
test/mock-utils.js

#1999
- Add information on `resolvedPath` to `getMockDispatch` error messages 
- Update `mock-utils.js` unit tests with the new `getMockDispatch` error messages
- Update `mock-agent.js` unit tests with the new `getMockDispatch` error messages
In `mock-utils.js>getMockDispatch`, there are a series of `matchedMockDispatches` checks. If the first check passes, we know we've matched `resolvedPath`. 
This PR adds `resolvedPath` to the `MockNotMatchedErrormessages` in subsequent checks so that it's easier to track down the `MockNotMatchedError` source.

feat: improve mock error breadcrumbs

---

index-fetch.js
index.js
test/websocket/messageevent.js

Fixes: #2769 
Tests were added from node core (including one for a bug fix that has not landed, and a bug that hasn't yet been reported) and all pass as expected. Error messages and codes do change, unfortunately, so this will end up being a semver-major change in core.

expose MessageEvent in fetch bundle

---

test/wpt/runner/runner.mjs

Updates the WPTRunner to always exit with 0 when running in https://github.com/nodejs/node/blob/main/.github/workflows/daily-wpt-fyi.yml
This is so that WPT failures don't block subsequent suites from running and being included in the WPT Report submitted to wpt.fyi.
Example of missing suites: https://wpt.fyi/results/?run_id=5181229028081664&run_id=5071266792341504&run_id=5183242763763712&run_id=5108285182574592

test: always exit with 0 when running in Node's Daily WPT Report CI job

---

benchmarks/parseRawHeaders.mjs
lib/core/util.js
test/node-test/util.js

before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/parseRawHeaders.mjs 
benchmark                             time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------------------------ -----------------------------
• parseRawHeaders
------------------------------------------------------------------------ -----------------------------
only strings                      43'233 ps/iter    (29'089 ps … 505 ns) 36'933 ps    150 ns    237 ns
only buffers                         536 ns/iter     (483 ns … 1'204 ns)    567 ns    773 ns  1'204 ns
mixed                                312 ns/iter       (280 ns … 384 ns)    325 ns …
```

perf: improve perf of parseRawHeaders

---

test/mock-agent.js

It seems that the modified test is failing sometimes. This makes the test slightly more resilient...

fix: make mock-agent.js test more resilient

---

lib/mock/mock-interceptor.js
test/mock-interceptor.js

if you would set responseOptions to null, it would pass but then it would throw an error in createMockScopeDispatchData because it would try to read headers attribute from null.
https://github.com/nodejs/undici/blob/fedae35f1b71999d2327ef6a28538f5845a71515/lib/mock/mock-interceptor.js#L96

mock: improve validateReplyParameters

---

benchmarks/TernarySearchTree.mjs
lib/core/tree.js
test/node-test/tree.js

before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/TernarySearchTree.mjs 
benchmark           time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------ -----------------------------
• tree.search
------------------------------------------------------ -----------------------------
content-length  35'297 ps/iter    (33'693 ps … 337 ns) 34'613 ps 40'718 ps    109 ns
CONTENT-LENGTH  35'353 ps/iter    (34'034 ps … 368 ns) 34'954 ps 40'991 ps 82'356 ps
Content-Length  34'016 ps/iter (32'977 ps … 71'478 ps) 33'795 ps 39'354 ps 60'906 ps
summary for tree.search
Content-Length
1.04x faster than content-length
1.04x faster than …
```

perf: improve TernarySearchTree

---

lib/fetch/headers.js
lib/fetch/webidl.js
test/fetch/headers.js
types/webidl.d.ts

fix: convert HeadersInit to sequence/dictionary correctly

---

README.md
benchmarks/benchmark-http2.js
benchmarks/benchmark-https.js
benchmarks/benchmark.js
benchmarks/server.js

Preparing some slides I noticed that our benchmarks where a bit off, and I discovered that we were making a mistake, specifically we were multiplying our results for the number of connections and not for the number of parallel requests.
I think the math makes sense now, but PTAL.

Use paralellelRequests instead of connections to calculate req/sec in benchmarks

---

lib/web/fetch/index.js
test/fetch/issue-1711.js

Actually fixes #1711
we could also probably have fetchParams stop relying on EventEmitter if we want to microoptimize 🤷

remove all fetchParam event handlers

---

lib/web/cache/cache.js
lib/web/eventsource/eventsource.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/fetch/symbols.js
lib/web/fetch/webidl.js
lib/web/websocket/connection.js
test/fetch/issue-2828.js

Fixes https://github.com/nodejs/undici/issues/2828
It also makes the dispatcher option in `fetching` optional

add dispatcher option to Request

---

lib/web/fetch/util.js
test/wpt/status/fetch.status.json

Number of bugs caused by the spec not realizing that objects might be passed by reference and therefore need to be cloned before modifying: 2

fix url referrer wpt

---

index-fetch.js
index.js
test/fetch/issue-2242.js

The aim of #2243 was to prevent the use of `Error.captureStackTrace` with non-objects, but unfortunately `null` is an object.
```shell
$ node
Welcome to Node.js v18.19.1.
Type ".help" for more information.
> const { fetch } = require('undici');
undefined
>  await fetch('http://localhost', { signal: AbortSignal.abort(null) });
Uncaught TypeError: invalid_argument
at Function.captureStackTrace (<anonymous>)
at fetch (/home/sol/src/solana-web3.js-git/node_modules/.pnpm/undici@6.6.2/node_modules/undici/index.js:103:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async REPL3:1:34
```
This PR prevents the use of `Error.captureStackTrace` with `null` as well.
Further fixes #2242.

fix(fetch): prevent crash when `fetch` is aborted with `null` as the `AbortSignal's` `reason`

---

lib/core/symbols.js
lib/dispatcher/client.js

Steps towards more clean separation between h1 and h2.
Refs: https://github.com/nodejs/undici/pull/2816

refactor: avoid http2 dynamic dispatch in socket handlers

---

lib/core/tree.js
test/node-test/tree.js

Reduce tree build time and improve module loading time.
<details>
```js
import { bench, group, run } from 'mitata'
import {
wellknownHeaderNames,
headerNameLowerCasedRecord
} from '../lib/core/constants.js'
import { TernarySearchTree } from '../lib/core/tree.js'
// copy new implementation
import { TernarySearchTree2 } from '../lib/core/tree2.js'
group('built', () => {
bench('current', () => {
const tst = new TernarySearchTree()
for (let i = 0; i < wellknownHeaderNames.length; ++i) {
const key = wellknownHeaderNames[i].toLowerCase()
tst.insert(Buffer.from(key), key)
}
})
bench('new', () => {
const tst = new TernarySearchTree2()
for (let i = 0; i < wellknownHeaderNames.length; ++i) {
const key = headerNameLowerCasedRecord[wellknownHeaderNames[i]] …
```

perf(tree): reduce overhead of build TernarySearchTree

---

lib/web/fetch/webidl.js

With node 20 we got access to the resizable ArrayBuffer proposal, so now these steps can be added.
Refs: https://github.com/tc39/proposal-resizablearraybuffer

webidl: implement resizable arraybuffer checks

---

lib/web/fetch/util.js
lib/web/websocket/connection.js
test/websocket/issue-2844.js
test/wpt/server/websocket.mjs

websocket server only needs to reply with a single subprotocol

---

lib/web/fetch/webidl.js
test/webidl/converters.js
test/websocket/messageevent.js
types/webidl.d.ts

Before:
```js
webidl.converters.BufferSource(Object.create(null))
// TypeError: Cannot convert object to primitive value
webidl.converters.BufferSource(Symbol('t'))
// TypeError: Cannot convert a Symbol value to a string
webidl.converters.BufferSource('')
// TypeError: Could not convert  to a BufferSource.
// convert what?
```
After:
```js
webidl.converters.BufferSource(Object.create(null))
// TypeError: Could not convert {} to a BufferSource.
webidl.converters.BufferSource(Symbol('t'))
// TypeError: Could not convert Symbol(t) to a BufferSource.
webidl.converters.BufferSource('')
// TypeError: Could not convert "" to a BufferSource.

unite webidl stringification

---

lib/dispatcher/client.js

fix: pipelining logic is not relevant for h2

---

benchmarks/websocketIsValidSubprotocol.mjs
lib/web/websocket/util.js
test/websocket/util.js

before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/websocketIsValidSubprotocol.mjs 
benchmark              time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------- -----------------------------
• isValidSubprotocol
--------------------------------------------------------- -----------------------------
valid: valid        47.78 ns/iter     (42.32 ns … 279 ns)  44.95 ns    153 ns    231 ns
invalid: invalid     64.4 ns/iter   (61.08 ns … 1'276 ns)  64.08 ns  79.02 ns    141 ns
```
after:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/websocketIsValidSubprotocol.mjs 
cpu: AMD Ryzen 7 …
```

perf: improve performance of isValidSubprotocol

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js

Was there a reason not to reuse the textdecoder instance?

perf: reuse TextDecoder instance

---

benchmarks/cache/get-field-values.mjs
benchmarks/cookies/Is-ctl-excluding-htab.mjs
benchmarks/core/parse-headers.mjs
benchmarks/core/parse-raw-headers.mjs
benchmarks/core/tree.mjs
benchmarks/fetch/headers-length32.mjs
benchmarks/fetch/headers.mjs
benchmarks/websocket/is-valid-subprotocol.mjs

this is just about restructuring the benchmarks folder, also use kebab-case for the file names

chore: restructure benchmarks, use kebab-case

---

benchmarks/cookies/to-imf-date.mjs
lib/web/cookies/util.js
test/cookie/to-imf-date.js

before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/cookies/to-imf-date.mjs 
benchmark                                                                          time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------------------------------------------------------------------- -----------------------------
• toIMFDate
--------------------------------------------------------------------------------------------------------------------- -----------------------------
toIMFDate: Wed Feb 28 2024 01:28:41 GMT+0100 (Central European Standard Time)     307 ns/iter     (237 ns … 1'868 ns)    295 ns    854 ns  1'868 ns
summary …
```

cookies: improve perf of toIMFDate

---

lib/web/cookies/util.js
test/cookie/validate-cookie-path.js

implement validateCookiePath according to the spec and allow space and disallow DEL

cookies: fix validateCookiePath

---

.gitignore
lib/core/symbols.js
lib/dispatcher/client-h1.js
lib/dispatcher/client-h2.js
lib/dispatcher/client.js

refactor: move out more h2 from core client

---

lib/mock/mock-utils.js
test/mock-agent.js
test/mock-utils.js

mock: improve test coverage of buildHeadersFromArray

---

lib/dispatcher/client-h1.js
lib/dispatcher/client-h2.js
lib/dispatcher/client.js

refactor: split out last h1 specific code from core

---

lib/dispatcher/client-h1.js
lib/dispatcher/client-h2.js
lib/dispatcher/client.js

fix: minor connect cleanup

---

docs/docs/api/Dispatcher.md
test/types/dispatcher.test-d.ts
types/dispatcher.d.ts

Resolves #2748 
In PR #2708, request headers were enhanced with iterable support, although the corresponding types and documentation mentions were inadvertently omitted. Current PR will fix it.
* add iterable to headers types in types/dispatcher.d.ts
* add type tests to iterable headers in test/types/dispatcher.test-d.ts
* add mention of iterables to documentation in docs/api/Dispatcher.md

Request headers types

---

.github/workflows/nodejs.yml

It seems, that codecov needs all commits. So we should remove the concurrency so that github pushes all commits to codecov.

ci: remove concurrency

---

benchmarks/cookies/validate-cookie-value.mjs
lib/web/cookies/util.js
test/cookie/cookies.js
test/cookie/validate-cookie-value.js

- fixes it to be conforming with the spec allowing wrapped values in double quotes
- improve performance
- fix error message
before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/cookies/validate-cookie-value.mjs 
benchmark         time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------- -----------------------------
• validateCookieValue
---------------------------------------------------- -----------------------------
valid: Cat     19.97 ns/iter     (18.45 ns … 656 ns)   19.4 ns  31.65 ns  38.36 ns
valid: "Cat"  error: Invalid header value
Error: Invalid header value
at validateCookieValue …
```

cookies: improve validateCookieValue

---

benchmarks/cookies/validate-cookie-name.mjs
lib/web/cookies/util.js
test/cookie/validate-cookie-name.js

- improve performance
- write tests
before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/cookies/validate-cookie-name.mjs 
benchmark       time (avg)             (min … max)       p75       p99      p999
-------------------------------------------------- -----------------------------
• validateCookieName
-------------------------------------------------- -----------------------------
valid: Cat   29.24 ns/iter     (25.81 ns … 854 ns)  26.67 ns  82.46 ns    107 ns
summary for validateCookieName
valid: Cat
```
after:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/cookies/validate-cookie-name.mjs 
runtime: node …
```

cookies: improve validateCookieName

---

lib/web/fetch/index.js
test/fetch/cookies.js

Fixes https://github.com/nodejs/undici/issues/2885

Properly parse set-cookie header using http2

---

benchmarks/core/is-valid-header-char.mjs
lib/core/request.js
lib/core/util.js

```
benchmark              time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------- -----------------------------
• isValidHeaderChar# text/html
--------------------------------------------------------- -----------------------------
regexp.test            34 ns/iter     (28.27 ns … 303 ns)  32.71 ns  72.85 ns    133 ns
regexp.exec         40.45 ns/iter     (34.18 ns … 218 ns)  41.16 ns  83.69 ns    135 ns
charCodeAt          30.31 ns/iter     (26.07 ns … 217 ns)   29.1 ns  61.91 ns    123 ns
isValidHeaderChar   35.55 ns/iter      (29.3 ns … 236 ns)  35.45 ns  86.28 ns    126 ns
summary for isValidHeaderChar# text/html
charCodeAt
1.12x faster than regexp.test
1.17x faster than isValidHeaderChar
1.33x faster than regexp.exec …
```

perf: optimize check invalid field-vchar

---

lib/web/fetch/body.js
lib/web/fetch/index.js
lib/web/fetch/request.js
test/fetch/issue-2898.js
test/wpt/status/fetch.status.json

This took me an hour to solve. Fuck me.
Fixes https://github.com/nodejs/undici/issues/2898

fix issue 2898

---

lib/web/fetch/util.js
lib/web/websocket/connection.js
lib/web/websocket/frame.js

Just ignore the catch block to improve test coverage

tests: ignore catch block when requiring crypto module

---

test/fetch/client-fetch.js
test/node-test/agent.js

when working on #2908 I realized that the tests are prematurely stopped because of the deleted lines. The lines were part of the tap to node builtin test runner. It seems that they are not necessary and worse they are disrupting the test flow.

fix: tests dont need process.exit

---

benchmarks/fetch/headers-length32.mjs
lib/web/fetch/headers.js
test/fetch/headers.js

**benchmarks/fetch/headers-length32.mjs**
- main
```
benchmark              time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------- -----------------------------
Headers@@iterator   5'731 ns/iter     (4'300 ns … 516 µs)  5'300 ns 11'600 ns    115 µs
```
- this patch
```
benchmark              time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------- -----------------------------
Headers@@iterator   5'151 ns/iter     (4'100 ns … 689 µs)  4'800 ns 11'100 ns    109 µs
```

perf(headers): a single set-cookie

---

lib/web/websocket/connection.js
lib/web/websocket/constants.js
lib/web/websocket/receiver.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js
test/websocket/close.js

Imho the close method was not right. I realized that after using isClosed and isClosing helper functions. thats why the last else black was dead code.

websocket: improve .close()

---

.github/workflows/bench.yml
benchmarks/package.json
benchmarks/post-benchmark.js

feat: add sending data benchmark

---

lib/web/fetch/file.js

we can use EOL of os-module, thus improving the code coverage if we merge #2914

fetch: use EOL of os-module

---

benchmarks/post-benchmark.js

before:
```
┌─────────┬───────────────────────┬─────────┬───────────────────┬────────────┬─────────────────────────┐
│ (index) │ Tests                 │ Samples │ Result            │ Tolerance  │ Difference with slowest │
├─────────┼───────────────────────┼─────────┼───────────────────┼────────────┼─────────────────────────┤
│ 0       │ 'got'                 │ 55      │ '1797.06 req/sec' │ '± 2.88 %' │ '-'                     │
│ 1       │ 'undici - fetch'      │ 35      │ '1828.63 req/sec' │ '± 2.73 %' │ '+ 1.76 %'              │
│ 2       │ 'node-fetch'          │ 10      │ '2295.80 req/sec' │ '± 2.44 %' │ '+ 27.75 %'             │
│ 3       │ 'http - no keepalive' │ 15      │ '2373.41 req/sec' │ '± 2.95 %' │ '+ 32.07 %'             │
│ 4       │ 'superagent'          │ 40      │ …
```

fix(benchmark): set body correctly

---

test/node-test/client-errors.js

adding some test cases
wondering if we actually should actually also check if hwm is a finite number so we can exclude NaN and Infinity as invalid cases.

chore: increase test coverage to 100% for /lib/api/api-request.js

---

docs/docs/api/ProxyAgent.md

#2841
- Update `ProxyAgent.md`
N/A
N/A
N/A
- [S] Tested

docs: clarify URI parsing behavior of ProxyAgent constructor

---

lib/web/fetch/body.js
lib/web/fetch/data-url.js
lib/web/fetch/formdata-parser.js
lib/web/fetch/formdata.js
lib/web/fetch/util.js
package.json
test/fetch/client-fetch.js
test/fetch/formdata.js
test/wpt/status/fetch.status.json

Fixes #2890 
Based on https://andreubotella.github.io/multipart-form-data/
```mjs
import { Request } from 'undici'
const request = new Request('http://localhost', {
method: 'POST',
headers: {
'Content-Type': 'multipart/form-data; boundary=----formdata-undici-0.6204674738279623'
},
body:
'------formdata-undici-0.6204674738279623\r\n' +
'Content-Disposition: form-data; name="fiŝo"\r\n' +
'\r\n' +
'value1\r\n' +
'------formdata-undici-0.6204674738279623--'
})
const fd = await request.formData()
// > FormData { [Symbol(state)]: [ { name: 'fiŝo', value: 'value1' } ] }
```

implement sync formdata parser

---

docs/README.md
docs/docsify/sidebar.md

Docs
Links should work
- Added examples to sidebar
- Fixed broken links on home page
N/A
N/A
N/A
- [S] Tested

Fix docs links and add examples to sidebar

---

docs/docs/api/DiagnosticsChannel.md

https://github.com/nodejs/undici/pull/2874
The type of `request.headers` changed from `string` to `string[]` as part of https://github.com/nodejs/undici/pull/2874
I've updated the `DiagnosticsChannel.md` doc to reflect this type change for `undici:request:create`.
I did double check the `undici:request:headers` and `undici:client:sendHeaders` channels and verified those are unchanged.

doc: update diagnostics channel request headers type change

---

benchmarks/_util/index.js
benchmarks/benchmark.js
benchmarks/post-benchmark.js
benchmarks/server.js
docs/README.md

What is unfair about the current benchmarks?
1. In got, the isStream option was not set and the body text was automatically parsed and converted into a string.
2. In request, the body was pipelined even though it had already been consumed.

fix(benchmark): make it fair

---

lib/web/fetch/headers.js
test/fetch/headers-inspect-custom.js

Issue: web specs better util.inspect output #2917
Issue Description:
The issue revolves around enhancing the util.inspect output for the Headers class. The current output exposes too many internal implementation details and does not provide much useful information. 
Solution:
I have improved the util.inspect output to better reflect the contents of the Headers object for enhanced clarity.

fetch: improve util.inspect output for web specifications

---

test/node-test/debug.js

Actually all the fixtures terminate the servers after the first request. So we just wont call child.kill() and it should not error anymore on windows.

ci: fix broken ci on windows and node v21 because of libuv bug

---

benchmarks/api/util.mjs
lib/api/util.js

I dont know how i can bench this in a meaningfull way. 
- Using queueMicrotask instead of process.nextTick
- avoid stacktrace generation if processing the payload throws an error (which would get ignored anyway)
- avoid use of `.startsWith()` as it is slower than provided fns
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/api/util.mjs 
runtime: node v21.7.1 (x64-linux)
benchmark                                                            time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------------------------------------------------------- -----------------------------
• isContentTypeText
------------------------------------------------------------------ …
```

perf: improve getResolveErrorBodyCallback

---

.github/workflows/nodejs.yml

CITGM is having macos-latet, but we dont.
https://github.com/nodejs/citgm/issues/1051#issuecomment-1993803240

ci: add macos-latest to test-matrix

---

.github/workflows/nodejs.yml

Ref: https://github.com/nodejs/security-wg/issues/1247
Note: I will work on `npmCommand not pinned ` in a separate PR, for [context](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/undici)

ci: pin versions of github actions

---

test/issue-803.js

will this reduce the flakyness in macos? we will see.
Improving he performance and increasing the timeout did the trick.

test: fix flakyness of issue-803 test

---

.github/workflows/nightly.yml
.github/workflows/nodejs.yml
.github/workflows/test.yml

https://github.com/nodejs/undici/issues/2932
In order to catch regressions either caused by or a result of upstream Node changes, add a workflow that is invoked on a daily basis to run the `main` branch's unit tests utilizing the most recent daily build.
In the event of test failure, create a new issue if needed, otherwise comment the most recent open "Nightly tests are failing" issue with the most recent failure.
1. Factor tests out of existing `Node CI` workflow
2. Add new `nightly` workflow, triggered on a daily schedule (or alternative, manually via workflow_dispatch to test changes in main without waiting for the next day's scheduled run.)
N/A
N/A
N/A

Chore: run tests daily against node nightly

---

test/types/dispatcher.test-d.ts
types/dispatcher.d.ts

Adding missing types for `Dispatcher#compose` and `ComposeDispatcher`

feat(TS): add types for composed dispatchers

---

docs/docs/api/RetryHandler.md
lib/handler/retry-handler.js
test/retry-handler.js
types/retry-handler.d.ts

fix: count for error response and network errors

---

lib/web/fetch/util.js
test/fetch/fetch-url-after-redirect.js

The fetch function behaves differently from major web browsers(chrome, safari, firefox etc), and even CURL (with `-L` option).
Here is a minimal reproducible URL I made: https://non-ascii-location-header.sys.workers.dev/redirect
<details>
<summary>Worker code</summary>
```ts
export default {
async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
try {
const url = new URL(request.url);
if (url.pathname === '/redirect') {
return new Response('', {
status: 302,
headers: {
Location: '/안녕',
},
});
}
return new Response(`pathname ${url.pathname}`);
} catch (e) {
return new Response(`error: ${(e as Error).message}`, { status: 500 });
}
},
};
```
</details>
By accessing the address at https://non-ascii-location-header.sys.workers.dev/redirect directly 
or …

fix(fetch): properly redirect non-ascii location header url

---

lib/web/cookies/index.js

Was perusing the code and spotted a double call to 'stringify' in setCookie
Didn't seem logical to run stringify multiple times on the same value as this might be an expensive operation behind the scenes.
Removed the additional call to stringify
N/A
N/A
N/A

perf: Remove double-stringify in setCookie

---

lib/web/eventsource/eventsource.js
test/eventsource/eventsource-properties.js

Makes Eventsource properties enumerable
- https://github.com/nodejs/undici/issues/2948
Sets eventsource class fields to be enumerable
N/A
Eventsource properties are not 
https://github.com/nodejs/undici/issues/2948
N/A

fix: make EventSource properties enumerable

---

README.md

Fixed the broken links for benchmarks.js and post-benchmark.js

docs: ✏️ fixed benchmark links

---

lib/handler/retry-handler.js
test/retry-handler.js

Closes #2986 
- **fix: bad start check**
- **refactor: remove unnecessary checks**

fix(#2986): bad start check

---

lib/dispatcher/client-h2.js
lib/web/fetch/index.js

https://github.com/nodejs/undici/issues/2808
Sporadically when doing massive h2 requests for a certain period of time a breaking assertion is triggered "assert(!this.aborted)" in onHeaders Method [undici/lib/core/request.js] causing application crash
- lib/dispatcher/client-h2.js
N/A
- Sometimes happens that H2 Stream "data" event is triggered some milliseconds before the "response" event, this leads to an uninitialized body. To avoid this breaking error if the onData is called before onHeaders, return false so the stream is paused in client-h2.js
[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md #

fix(H2 Client): bind stream 'data' listener only after received 'response' event

---

lib/web/fetch/headers.js
test/fetch/headers-inspect-custom.js
test/fetch/request-inspect-custom.js
test/fetch/response-inspect-custom.js

@anonrig after your suggestion, I updated these
https://github.com/nodejs/undici/pull/2938#discussion_r1529551347

fix: node:util instead of util

---

.github/workflows/nightly.yml

- https://github.com/nodejs/undici/issues/3017#issuecomment-2027514900
In the four nightly failures so far, 3 were not undici's fault and only one platform failed. In the one true positive error, all three platforms failed tests, therefore only create/comment issue if all three platform fail.
1. All platforms succeed: https://github.com/mweberxyz/nodejs-undici/actions/runs/8491820300
No issue created
2. Single platform fails: https://github.com/mweberxyz/nodejs-undici/actions/runs/8491975740
No issue created
3. All platforms fail: https://github.com/mweberxyz/nodejs-undici/actions/runs/8491957840
Issue created: https://github.com/mweberxyz/nodejs-undici/issues/8
.github/workflows/nightly.yml:
- remove matrix to give each platform a stable id
- only run `report-failure`if all three …

chore(workflows/nightly.yml): create issue only on all platforms fail

---

.github/workflows/nodejs.yml

fixes #3012 
The `actions` permissions is not required by [fastify/github-action-merge-dependabot](https://github.com/fastify/github-action-merge-dependabot) documentation. Just to be sure I tested it myself [here](https://github.com/fraxken/test_dependabot) and everything seems ok to me.

chore(automerge): remove unnecessary actions:write permission

---

lib/core/util.js
lib/dispatcher/client-h2.js
lib/web/fetch/index.js
test/fetch/http2.js
test/http2.js

refactor(#3023): Pass headers as array instead

---

lib/web/fetch/data-url.js

```shell
> require("undici").parseMIMEType("text/plain; |charset=UTF-16; charset=UTF-8"); // before
{
type: 'text',
subtype: 'plain',
parameters: Map(1) { 'charset' => 'UTF-16' },
essence: 'text/plain'
}
> require("undici").parseMIMEType("text/plain; |charset=UTF-16; charset=UTF-8"); // after
{
type: 'text',
subtype: 'plain',
parameters: Map(2) { '|charset' => 'UTF-16', 'charset' => 'UTF-8' },
essence: 'text/plain'
}
```

fix: regexp pattern

---

docs/docs/api/DiagnosticsChannel.md
lib/core/request.js
lib/dispatcher/client-h1.js
test/node-test/diagnostics-channel/get.js
test/node-test/diagnostics-channel/post-stream.js
test/node-test/diagnostics-channel/post.js

Revert "fix: don't leak internal class (#3024)"

---

lib/dispatcher/proxy-agent.js
test/proxy-agent.js

Closes https://github.com/nodejs/undici/issues/3019

fix: ProxyAgent causes request.headers.host to be forcibly reset

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js

fallback to Buffer.isUtf8 on platforms without icu

---

lib/dispatcher/client-h1.js
lib/dispatcher/client-h2.js

fix: request abort

---

lib/mock/mock-interceptor.js
test/mock-interceptor.js

I actually wanted to improve the test coverage. I could have just removed the data field. but actually passing objects is better.
wdyt?

mock: improve mock interceptor

---

lib/dispatcher/client.js
test/node-test/client-dispatch.js

Fixes: https://github.com/nodejs/undici/issues/3065

fix: bad client destroy on servername change

---

benchmarks/core/is-blob-like.mjs
lib/core/util.js
test/util.js

before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node benchmarks/core/is-blob-like.mjs 
runtime: node v21.7.1 (x64-linux)
benchmark                time (avg)             (min … max)       p75       p99      p999
----------------------------------------------------------- -----------------------------
• isBlobLike
----------------------------------------------------------- -----------------------------
blob                    744 ps/iter       (409 ps … 164 ns)    716 ps   1.16 ns   5.35 ns
file                    728 ps/iter       (409 ps … 153 ns)    716 ps    955 ps   5.29 ns
blobLikeStream        18.79 ns/iter     (16.51 ns … 213 ns)  17.73 ns  29.29 ns    143 ns
fileLikeStream        18.66 ns/iter     (15.99 ns … 187 ns) …
```

perf: improve isBlobLike

---

lib/api/readable.js
test/request-timeout.js

fix: defer errors with setImmediate

---

lib/handler/decorator-handler.js
test/decorator-handler.js

I think this will make the DecoratorHandler more resilient. 
- Added typecheck for the provided handler
- added onResponseStarted
- made handler attribute private

improve DecoratorHandler

---

benchmarks/fetch/is-valid-encoded-url.mjs
lib/web/fetch/util.js

before:
```sh
runtime: node v21.7.1 (x64-linux)
benchmark                      time (avg)             (min … max)       p75       p99      p999
----------------------------------------------------------------- -----------------------------
isValidEncodedURL valid       181 ns/iter       (174 ns … 567 ns)    182 ns    218 ns    262 ns
isValidEncodedURL invalid     178 ns/iter       (173 ns … 425 ns)    176 ns    220 ns    277 ns
```
after:
```sh
runtime: node v21.7.1 (x64-linux)
benchmark                      time (avg)             (min … max)       p75       p99      p999
----------------------------------------------------------------- -----------------------------
isValidEncodedURL valid      61.9 …
```

fetch: improve performance of isValidEncodedURL

---

lib/dispatcher/client-h2.js
test/http2.js
test/node-test/client-dispatch.js

refactor: h2 refactoring

---

lib/web/fetch/index.js

This skips the creation of a `TransformStream`, which showed up glowing in the following flamegraph:
After this patch:
main:
```
[bench:run] ┌─────────┬───────────────────────┬─────────┬────────────────────┬────────────┬─────────────────────────┐
[bench:run] │ (index) │ Tests                 │ Samples │ Result             │ Tolerance  │ Difference with slowest │
[bench:run] ├─────────┼───────────────────────┼─────────┼────────────────────┼────────────┼─────────────────────────┤
[bench:run] │ 0       │ 'undici - fetch'      │ 30      │ '4571.92 req/sec'  │ '± 2.72 %' │ '-'                     │
[bench:run] │ 1       │ 'request'             │ 35      │ '5183.44 req/sec'  │ '± 2.90 %' │ '+ 13.38 %'             │
[bench:run] │ 2       │ 'node-fetch'          │ 10      │ '5405.14 req/sec'  │ …
```

Skip the creation of a transform stream in fetch

---

benchmarks/fetch/url-has-https-scheme.mjs
lib/web/fetch/util.js
test/fetch/util.js

before:
```sh
benchmark                              time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------------------------- -----------------------------
urlHasHttpsScheme "http:" String    25.31 ns/iter      (23.7 ns … 263 ns)  24.66 ns   41.4 ns  74.99 ns
urlHasHttpsScheme "https:" String   31.63 ns/iter     (29.23 ns … 120 ns)  30.49 ns  60.29 ns  66.36 ns
urlHasHttpsScheme "http:" Object      927 ps/iter       (443 ps … 186 ns)    955 ps   1.16 ns   8.56 ns
urlHasHttpsScheme "https:" Object     929 ps/iter     (409 ps … 44.81 ns)    955 ps    1.4 ns   8.49 ns
```
after:
```sh
runtime: node v21.7.1 (x64-linux)
benchmark                              time (avg)             (min …
```

fetch: improve performance of urlHasHttpsScheme

---

lib/web/fetch/body.js
lib/web/fetch/index.js

refs: https://github.com/nodejs/undici/pull/3093#issuecomment-2050460276

fetch: avoid creation of an intermediary ReadableStream

---

test/interceptor.js
test/issue-1757.js

the touched two test files have no jest specific tests. Transforming them to normal tests.

test: duplicate jest unspecific tests to native runner

---

benchmarks/fetch/is-valid-header-value.mjs
lib/web/fetch/util.js
test/fetch/util.js

before:
```sh
benchmark                                      time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------------------------------------- -----------------------------
isValidHeaderValue valid                    10.79 ns/iter      (8.87 ns … 620 ns)   9.72 ns  28.58 ns    124 ns
isValidHeaderValue invalid containing NUL    9.91 ns/iter    (8.66 ns … 45.73 ns)   9.96 ns  18.55 ns  34.65 ns
isValidHeaderValue invalid containing CR     12.4 ns/iter   (10.23 ns … 75.84 ns)  12.82 ns  27.69 ns  37.79 ns
isValidHeaderValue invalid containing LF    13.54 ns/iter    (11.39 ns … 57.7 ns)  14.19 ns  33.01 ns  47.61 ns
isValidHeaderValue invalid trailing TAB      7.76 ns/iter    (6.82 ns … 30.76 ns)   7.74 ns   9.79 ns  19.44 ns …
```

fetch: improve performance of isValidHeaderValue

---

lib/core/util.js

This function got obsolete, when we dropped node16 support as it was necessary to implement a stream.isDisturbed equivalent in userland. 
See the original PR by @ronag
https://github.com/nodejs/undici/commit/a3c0413b4fae2c30417f883f67ae6e5d266cb0e7

util: remove isReadableAborted

---

docs/docs/api/EventSource.md
lib/web/eventsource/eventsource.js
test/eventsource/eventsource-custom-dispatcher.js
test/types/event-source-d.ts
types/eventsource.d.ts

add dispatcher option to EventSource

---

benchmarks/core/is-valid-port.mjs
lib/core/util.js
test/node-test/client-errors.js
test/util.js

There were some issues hidden.
E.g. if fields are undefined it will serialize them to undefined
```js
describe('common', () => {
test('returns valid URL object', () => {
const url = parseURL({ protocol: 'http:' })
strictEqual(url instanceof URL, true)
strictEqual(url.href, 'http://undefined/')
})
})
```
So it should be now hardened and if the provided object has not sufficient information it will be replaced with empty string and not with undefined.

core: improve parseURL

---

benchmarks/fetch/body-arraybuffer.mjs
lib/web/fetch/body.js
lib/web/fetch/util.js

Deps: #3109
Optimize cases where the body is a string, BufferSource, URLSearchParams, or stream (only one chunk).
Avoid cloning if unnecessary.
- #3109
```
benchmark                 time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------------ -----------------------------
• small (length 512)
------------------------------------------------------------ -----------------------------
Response#arrayBuffer  22'113 ns/iter  (11'200 ns … 3'439 µs) 19'100 ns    116 µs    441 µs
Response#text         16'603 ns/iter    (11'700 ns … 673 µs) 15'100 ns 51'600 ns    268 µs
summary for small (length 512)
Response#text
1.33x faster than Response#arrayBuffer
• middle (length 8192)
------------------------------------------------------------ …
```

perf: avoid unnecessary clone

---

.github/workflows/test.yml
test/client-request.js
test/content-length.js
test/issue-803.js

Closes #3120 
Also lets have a try to deflake issue-803.js

test: improve test and ci performance

---

lib/web/fetch/body.js
test/fetch/client-fetch.js
test/node-fetch/main.js

fixes #3097
To make the "Body is unusable" error a bit more helpful.
Changed the "Body is unusable" error to be more verbose. I'm not attached to this wording, just included it to get the ball rolling.
N/A
N/A
N/A

fetch: Change wording of "Body is unusable" error

---

benchmarks/fetch/request-creation.mjs
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/util.js
test/fetch/request.js
test/fetch/response.js

Slow initialization of object literals with getters.
- main
```
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)  12'398 ns/iter   (8'100 ns … 4'134 µs) 11'000 ns 34'100 ns    147 µs
```
- this patch
```
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)  10'997 ns/iter   (7'000 ns … 3'704 µs)  9'700 ns 34'000 ns    159 µs
```

perf: use class instead of object literals with getters

---

lib/api/util.js
test/issue-3136.js

Refs: https://github.com/nodejs/undici/issues/3136

fix: unhandled exception or failing error body

---

lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/util.js

This change has a slight speedup, but this is mostly for correctness. Having a new "realm" (which is meant to be a distinct global environment) or settings object per Request/Response doesn't make sense.

reuse realm for Request/Response

---

lib/dispatcher/client-h2.js
lib/dispatcher/client.js
test/http2.js

Closes #3140
Upon `GOAWAY` frame, now all requests are aborted

fix(H2-#3140): abort requets upon GOAWAY

---

lib/web/cache/cache.js
lib/web/eventsource/eventsource.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/symbols.js
test/fetch/request.js
test/fetch/response.js

Refs: https://github.com/nodejs/undici/pull/3142#issuecomment-2068066669

don't store realm on Request/Response

---

docs/docs/api/EnvHttpProxyAgent.md
lib/dispatcher/env-http-proxy-agent.js
test/env-http-proxy-agent.js

> I'm late to the party, but I strongly recommend to reconsider the case preference as per the [proxy var "spec"](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/#the-lowest-common-denominator), lowercase form should be preferred:
>
>> Use lowercase form. HTTP_PROXY is not always supported or recommended.
>> If you absolutely must use the uppercase form as well, be sure they share the same value.
https://github.com/nodejs/undici/pull/2994#discussion_r1572954012
EnvHttpProxyAgent now prefers lowercase env vars over uppercase ones, and documentation has been updated to reflect that.
When there both uppercase and lowercase env vars (http_proxy, https_proxy & no_proxy) exist, the lowercase is now used instead of uppercase.
[cert]: …

fix(EnvHttpProxyAgent): prefer lowercase env vars

---

test/fetch/request.js

test: add headerslist copy check

---

.github/workflows/release.yml
scripts/release.js

- https://github.com/nodejs/undici/pull/3089
- https://github.com/nodejs/undici/issues/3103
Auto release logic currently generates release notes compared to most recent release (`releases[0]`). Instead, ensure comparisons are made to most recent **v6** release. This is a stop gap until more robust multi-branch releases can be set up.
I tested this in fork and my concern of v6 release followed by v5 release is probably unwarranted, because it appears releases[0] always refers to the most recent, highest valued, semver major release. I also tested it if a v7.0.0-alpha.1 release exists, and the problem issue arises. Best to get this in sooner than later as a safety precaution, and hopefully will have a proposal for multi-branch release merged before it became an issue.
[cert]: …

chore: ensure automated v6 release compared to v6

---

lib/web/fetch/headers.js
lib/web/fetch/request.js
test/fetch/headers-case.js

Refs: https://github.com/nodejs/undici/pull/3159#issuecomment-2075537226

fix casing issue when cloning Headers object

---

lib/web/fetch/headers.js
test/fetch/headers.js

Refs: https://github.com/nodejs/undici/pull/3160#issuecomment-2075797019
Refs: #3161

fix header cloning bug

---

.github/workflows/bench.yml

chore: change bench naming for h2

---

index-fetch.js
test/fetch/bundle.js

Refs: https://github.com/nodejs/node/issues/50275
Refs: https://github.com/nodejs/node/issues/47587

expose WebSocket related events in node bundle

---

lib/web/fetch/request.js
test/wpt/status/fetch.status.json

Fixes #2227
I’ｍ happy to be able to add undici to a test that has only passed Chrome and Deno yet.
https://wpt.fyi/results/fetch/api/abort/general.any.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=deno&product=node.js&aligned=

fix: correct firing order of abort events

---

benchmarks/websocket/messageevent.mjs
index-fetch.js
lib/web/eventsource/eventsource.js
lib/web/websocket/connection.js
lib/web/websocket/events.js
lib/web/websocket/util.js

Refs: https://github.com/nodejs/node/pull/52370

create fast MessageEvent

---

package.json

We are using @fastify/busboy but not requiring it as dev dependency. If borp would removes @reporters/github or better say @actions/http-client updates undici to latest, it will break our tests.
Lets add it...

chore: add explicitly @fastify/busboy

---

lib/web/cache/cache.js
lib/web/cache/cachestorage.js
lib/web/cookies/index.js
lib/web/eventsource/eventsource.js
lib/web/fetch/formdata.js
lib/web/fetch/headers.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/util.js
lib/web/fetch/webidl.js
lib/web/fileapi/filereader.js
lib/web/fileapi/progressevent.js
lib/web/websocket/events.js
lib/web/websocket/websocket.js
test/fetch/headers.js
test/webidl/converters.js
test/webidl/errors.js
test/webidl/helpers.js
test/websocket/messageevent.js
types/webidl.d.ts

- In 'singular' converters, we now default the options to undefined.
- defaultValue (for dictionary converters) is now a function
- We now attach context (a header like 'Headers.has' and the argument name) to each webidl call for better errors.

webidl changes

---

lib/web/fetch/webidl.js
test/fetch/headers.js
test/types/dispatcher.test-d.ts
test/webidl/errors.js
test/websocket/messageevent.js

The errors are actually useful now, oops.
Next up, hopefully tomorrow, will be when I get to handling sequence errors.

preserve dictionary key name in webidl errors

---

lib/web/fetch/headers.js
lib/web/fetch/request.js
test/fetch/headers-case.js

Follow up of #3160.
In the following cases. Lose the original raw header name.
```js
await fetch(new Request(url, { headers: [['Content-Type', 'text/plain']] }), { method: 'GET' })
```

fix: keep raw header name

---

lib/web/fetch/data-url.js

I noticed that these tests were failing in node but were passing in Deno. 
https://wpt.fyi/results/mimesniff/mime-types/parsing.any.html?label=master&label=experimental&product=node.js&product=deno&product=chrome&product=firefox&view=subtest
Of course it was an issue with regex.
We now pass 1031/1898 of the tests while Deno "only" passes 1030/1898!

fix 3 mimesniff tests

---

lib/web/fetch/request.js

Hi, I was watching @mcollina's stream and noticed a spread operator in fetch `makeRequest()` which I thought could be slow, so I've removed to get some more perf.
main
```
cpu: Apple M1 Pro
runtime: node v22.0.0 (arm64-darwin)
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)   1'238 ns/iter   (1'149 ns … 1'533 ns)  1'263 ns  1'494 ns  1'533 ns
```
pr
```
cpu: Apple M1 Pro
runtime: node v22.0.0 (arm64-darwin)
benchmark               time (avg)             (min … max)       p75       p99      p999
---------------------------------------------------------- -----------------------------
new Request(input)     784 ns/iter     (743 ns … 1'230 ns) …
```

perf: avoid spread in makeRequest()

---

test/types/mock-interceptor.test-d.ts
types/mock-interceptor.d.ts

https://github.com/nodejs/undici/issues/1583
The issue is self-explanatory. It's kinda complicated to get what the actual types are. So I decided to print the `opts`argument:
https://github.com/nodejs/undici/blob/0b5a4515f3b7c0bbdc873ea172c47a56e515b167/lib/mock/mock-interceptor.js#L124
This is what I got:
From what I understand, only  `path` and `method` are sure to exist.

fix: MockResponseCallbackOptions type

---

lib/web/websocket/connection.js
lib/web/websocket/receiver.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js
test/websocket/client-received-masked-frame.js
test/websocket/close-invalid-status-code.js
test/websocket/close-invalid-utf-8.js

fix websocket receiving an invalid utf-8 in close frame

---

lib/api/readable.js

perf: avoid setImmediate if body is reading

---

lib/api/api-request.js
test/client.js

fix: remove abort handler on close

---

benchmarks/websocket/generate-mask.mjs
lib/web/websocket/frame.js

The disadvantage is increased memory usage.
```
benchmark                  time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------------- -----------------------------
• generate
------------------------------------------------------------- -----------------------------
generateMask            15.69 ns/iter      (9.77 ns … 332 ns)  15.14 ns  72.66 ns    180 ns
crypto.randomBytes(4)   3'874 ns/iter   (2'971 ns … 6'260 ns)  4'528 ns  6'086 ns  6'260 ns
summary for generate
generateMask
246.99x faster than crypto.randomBytes(4)
```

websocket: 200x faster generate mask

---

lib/web/websocket/util.js

This can also be adapted to fetch.

websocket: don't clone buffer if it's not needed.

---

lib/web/websocket/receiver.js

I know, I know... we wont improve the performance of cold branches... but I really think it makes sense to move these lines higher. Checking the code for validity after we set the code makes more sense then checking the validity after we instantiate a buffer for reason.

websocket: move codeblock in parseCloseBody

---

test/wpt/server/server.mjs
test/wpt/status/fetch.status.json

while investigating failing tests, here conditional-get.any.js, I created the cache.py equivalent in server.mjs. Because our fetch is not caching by etag, the second fetch in conditional-get.any.js wont send the if-none-match header.

fetch: wpt add /fetch/api/resources/cache.py to server.mjs

---

test/wpt/runner/runner.mjs
test/wpt/server/constants.mjs
test/wpt/server/server.mjs
test/wpt/server/util.mjs
test/wpt/start-FileAPI.mjs
test/wpt/start-cacheStorage.mjs
test/wpt/start-eventsource.mjs
test/wpt/start-fetch.mjs
test/wpt/start-mimesniff.mjs
test/wpt/start-websockets.mjs
test/wpt/status/fetch.status.json

Many tests will communicate with the server and change request behaviors by using "pipes". A "pipe" is a list of commands that modifies the request in different ways. For example:
```js
...?pipe=status(206)|header(Content-Type, text/plain)
```
will cause the server to change the status code to 206 and add a `content-type: text/plain` header.

add pipe support for wpt server

---

lib/web/fetch/index.js
lib/web/fetch/util.js
lib/web/websocket/connection.js
lib/web/websocket/websocket.js
test/fetch/issue-rsshub-15532.js

refs: https://github.com/DIYgod/RSSHub/issues/15532

fetch: don't set an invalid origin header

---

test/wpt/runner/runner.mjs
test/wpt/runner/util.mjs
test/wpt/status/FileAPI.status.json
test/wpt/status/fetch.status.json
test/wpt/status/websockets.status.json

fail wpt runner if expected failures does not match actual

---

lib/api/api-request.js
test/client-request.js

fix: ignore content-length when dumping HEAD

---

index-fetch.js
index.js
test/fetch/client-error-stack-trace.js

Closes #2869 
This is an odd bug. 
Obviously `this` is `undefined`, because nobody will run fetch with the `new` operator.
So currently if fetch throws, we create a second time the same stacktrace?
Maybe it is wrong and we should set fetchImpl instead of fetch as reference point?
Maybe we can improve the perf, by storing the stackTraceLimit and set it to 0 and after the fetch we reset it. But problem is, that aggregated errors in cause will have no stack trace then?

fetch: fix captureStackTrace

---

test/wpt/server/lockedresource.mjs
test/wpt/server/routes/network-partition-key.mjs
test/wpt/status/fetch.status.json

Strange... it seems that the python code in network-partition-key.py is invalid anyway?

fetch: fix wpt test request-upload.any.js

---

lib/web/websocket/websocket.js
test/wpt/status/websockets.status.json

 websocket: don't clone buffer

---

lib/dispatcher/client-h1.js

No await is used inside `writeBuffer`
- Remove unecessary async from `writeBuffer`

Remove unecessary async from writeBuffer

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js
test/websocket/issue-2859.js

Closes #3239 
Closes #2859 
Control frames cannot be fragmented which guarantees that they will be handled in full in a single message. Since this is the case, there's no reason to assign values to `this.#info` (which is the internal state/settings of a frame) which should avoid race conditions.

refactor websocket control frame handling

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js
test/websocket/continuation-frames.js

Fixes a bug I discovered when testing continuation frames, but this is more of a general refactor.
The old way didn't work at all and sucked pretty hard.

fix parsing continuation frames in websocket

---

.github/workflows/nightly.yml

today again i got an email that our nightly fails. checked it and wondered why node nightly from 24 april was used. checked the [node page](https://nodejs.org/download/nightly/)  and saw, that since we have node 23, no node 22 nightlies are published. So we have to change the target.
Also here I wonder if the following condition is correct:
https://github.com/nodejs/undici/blob/38c8b55c699199bd3523511737127a236d1a2521/.github/workflows/nightly.yml#L37
I would actually say, that it should be or conditions and not and conditions. If the tests fail in windows but mac and linux pass, as it is now, then we dont get an issue created. Rn i still get an email that it failed.
Maybe @mweberxyz share his opinion?
Maybe can be taken care in a follow up.

ci: node nightly test should use node 23

---

test/fetch/exiting.js

Adds a test to verify `res.body.cancel()` works as expected.

Add test to verify if the connection is correctly aborted on cancel

---

.github/workflows/autobahn.yml
lib/web/websocket/receiver.js

Refs: #3252
Fixes cases 2.6, 2.11, 5.5, 5.8, 9.3.1, 9.4.1

websocket: fix 6 autobahn tests

---

lib/web/websocket/receiver.js

Cleanup websocket

---

benchmarks/fetch/headers-length32.mjs
benchmarks/fetch/headers.mjs
lib/core/symbols.js
lib/web/cookies/util.js
lib/web/fetch/headers.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/symbols.js
lib/web/websocket/connection.js
test/fetch/headers.js
test/fetch/issue-3267.js
test/fetch/request.js
test/fetch/response.js

use private properties in Headers

---

lib/web/fetch/data-url.js
lib/web/websocket/connection.js
lib/web/websocket/constants.js
lib/web/websocket/permessage-deflate.js
lib/web/websocket/receiver.js
lib/web/websocket/sender.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js
test/autobahn/client.js
test/websocket/send-mutable.js

https://www.rfc-editor.org/rfc/rfc7692
Famous last words, but I'm looking at the spec and it doesn't seem too difficult to implement.

permessage-deflate decompression support in websocket

---

test/fetch/client-node-max-header-size.js
test/utils/node-http.js

https://github.com/nodejs/node/pull/53028
When running in 18.20.3, the test suite fails to stop the test as the HTTP server does not close if some connections are still pending.
This PR changes the test utils to close pending connection first before closing the server. This is already the default behavior in Node 20+.
N/A
N/A
N/A

fix: Fix server closing in tests.

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js

This reverts 13523fd7fe66a4238f9ee79326b64cac4fc47d15 which broke permessage-deflate support.
See https://github.com/nodejs/undici/issues/3289 for why the tests did not catch this.

revert: "websocket: pre-calculated length"

---

lib/web/websocket/sender.js

websocket: use FixedQueue instead of Set

---

lib/web/cookies/index.js
lib/web/cookies/util.js
lib/web/fetch/headers.js
test/cookie/global-headers.js

refs: https://github.com/nodejs/undici/pull/3286
I have no idea why we didn't do this before 🤷

don't use internal header state for cookies

---

docs/docs/api/RetryHandler.md
lib/core/symbols.js
lib/core/util.js
lib/handler/retry-handler.js
test/retry-handler.js

fix: retry on body support

---

lib/web/websocket/websocket.js
test/node-test/debug.js

remove websocket experimental warning

---

lib/dispatcher/client-h1.js
lib/dispatcher/client-h2.js

Convert passing object to passing params to `writeBuffer` `writeIterable` `writeBlob` `writeStream`
Generally speaking constructing new object and passing it to function is more costly than just passing params.
Also using [deoptexplorer-vscode](https://github.com/microsoft/deoptexplorer-vscode) I have found that writeBuffer was deoptimized probably because off passing different shape of object.
- Convert passing object to passing params to `writeBuffer` `writeIterable` `writeBlob` `writeStream`

perf: convert object to params

---

test/imports/undici-import.ts
types/index.d.ts

Fixes: https://github.com/nodejs/undici/issues/3308

export interceptor to type def file

---

docs/docs/api/Client.md

Fixes: https://github.com/nodejs/undici/issues/3297
Docs -> request -> bodyTimeout
Clarify the potential misunderstanding in how `bodyTimeout` works.

doc: clearify the behaviour of `bodyTimeout` in the request

---

lib/core/connect.js
test/connect-pre-shared-session.js

#3315 
Support passing custom session in connect options for pre-shared sessions.
- Session passed to client connect will be passed to tls.connect instead of using the built-in module session store.

 feature: support pre-shared sessions

---

package.json

Refs: https://github.com/nodejs/undici/issues/3339

build: use `husky` as `husky install` is deprecated

---

package.json
types/formdata.d.ts
types/index.d.ts
types/interceptors.d.ts
types/retry-agent.d.ts
types/webidl.d.ts

Closes #3330 
We need to remove skipLibCheck to throw the error. Now we can detect the bug.

fix: interceptors.d.ts has no default export

---

lib/web/fetch/index.js
test/fetch/encoding.js

When decoding, it must be processed from the reverse. We didn't catch this because the test is wrong.

fetch: fix content-encoding order

---

lib/api/api-request.js
test/request-signal.js

Fix issue #3353 
Request API doesn't remove the signal listener after complete the request
Remove abort listener after success

fix: post request signal

---

lib/api/api-request.js
test/request-signal.js

Refs: https://github.com/nodejs/undici/pull/3358

Revert "fix: post request signal (#3354)"

---

lib/web/websocket/frame.js
test/websocket/frame.js

websocket: don't use pooled buffer in mask pool

---

lib/api/readable.js

fix: consider bytes read when dumping

---

lib/api/api-request.js
lib/core/util.js

refactor: simplify signal handling

---

lib/api/readable.js

fix: use explicit flag for when use has interacted with stream

---

docs/examples/README.md

https://github.com/nodejs/undici/pull/3349
Refactor example documentation structure and add CacheableLookup example

Refactor example documentation structure and add CacheableLookup example

---

lib/api/api-request.js

refactor: simplify request error handling

---

lib/api/api-pipeline.js
lib/core/request.js
lib/handler/decorator-handler.js

fix: ensure onConnect is always called

---

test/types/dispatcher.test-d.ts
types/dispatcher.d.ts

https://github.com/nodejs/undici/pull/2317
The name of the field should be responseHeaders
Change the field name to `responseHeaders`

Refactor responseHeader to responseHeaders

---

lib/web/fetch/request.js
test/fetch/max-listeners.js

Fixes https://github.com/nodejs/node/issues/47449
Please note, I haven't tested this PR.

fix: don't override user defined MaxListeners

---

lib/dispatcher/dispatcher.js
test/dispatcher.js

Refs: https://github.com/nodejs/undici/discussions/3373
Refs: https://github.com/nodejs/undici/issues/3370

fix: forward dispatch return value

---

lib/handler/retry-handler.js
test/issue-3356.js

fix: throw on retry when payload is consume by downstream

---

lib/web/websocket/frame.js

```shell
> $ node memory.js // before
memoryUsage: 104Kib
> $ node memory.js // after
memoryUsage: 68Kib
```
```js
const socket = new WebSocket("ws://localhost:5001")
socket.onopen = function () {
const rss = process.memoryUsage.rss()
socket.send("hi")
socket.onmessage = function () {
console.log(`memoryUsage: ${(process.memoryUsage.rss() - rss) / 1024}Kib`)
socket.close()
}
}
```
Refs: https://github.com/websockets/ws/commit/ddfe4a804d79e7788ab136290e609f91cf68423f

websocket: reduce memory usage

---

README.md
docs/docs/api/Dispatcher.md
docs/docs/api/Fetch.md
lib/api/readable.js
test/client-request.js
test/readable.js
test/types/readable.test-d.ts
types/dispatcher.d.ts
types/readable.d.ts

feat: implement `BodyReadable.bytes`

---

lib/web/websocket/constants.js
lib/web/websocket/sender.js
lib/web/websocket/websocket.js

websocket: avoid using Buffer.byteLength

---

lib/web/websocket/connection.js
lib/web/websocket/receiver.js
lib/web/websocket/symbols.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js

refs: https://github.com/nodejs/undici/pull/3394#discussion_r1667601624
cc @tsctx

separate whatwg websocket logic from rfc 6455

---

test/types/api.test-d.ts
test/types/dispatcher.test-d.ts
types/api.d.ts
types/dispatcher.d.ts

This closes #3378 
This adds a `TOpaque` generic type parameter to the type definitions for request(), connect(), stream(), and pipeline(). The type parameter defaults to null, which is the default value of the opaque property. If an opaque value is passed in the options, its type can usually be inferred automatically, such that no explicit type declaration is necessary. This commit also adds tsd tests to make sure the type definitions work as expected.
N/A
N/A
No breaking change, unless I've missed something in the explanation below:
Previously, the type of `opaque` was `unknown`, which means it needed to be either type-checked or casted to another type before anything could be done with it. Such code should not be broken by this commit, although some type checks or assertions might …

Add generic type for opaque object

---

lib/handler/decorator-handler.js

In some edge cases this causes issues. Leave it to the user to handle if necessary.

fix: don't call onConnect automatically

---

test/connect-timeout.js
test/node-test/debug.js

Our tests are failing on CITGM because we rely on IPv6 being available on all hosts and a few other OSS flavours. I'm skipping those tests there. 
Fixes https://github.com/nodejs/citgm/issues/1051

In CITGM, skip tests that are flaky there

---

docs/docs/api/RetryHandler.md

Looking at the typings of [RetryHandler](https://github.com/nodejs/undici/blob/main/types/retry-handler.d.ts#L26), I saw that it must return `number | null` but the [documentation](https://undici.nodejs.org/#/docs/api/RetryAgent?id=parameter-retryhandleroptions) says `void`.
Fixed the documentation page for RetryHandler
N/A
N/A
None
- [ x ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ S ] Tested
- [ S ] Benchmarked (**optional**)
- [ x ] Documented
- [ x ] Review ready

Fix signature of RetryHandler

---

README.md

I've been toying with the `duplex` option, and I noticed our docs are a little confusing. The implementation forces me to use `'half'` for the value, but it seem like a full duplex operation... unless the `'full'` duplex refers to just the `request` or `response` individually? 
It's a bit confusing. 
WDYT @KhafraDev ?

Fix fetch `duplex` docs

---

.github/workflows/nodejs-shared.yml
CONTRIBUTING.md
build/wasm.js

Fixes: https://github.com/nodejs/undici/issues/3345
Refs: https://github.com/nodejs/undici/pull/2643
Changes were previously accepted to allow Undici to be built to work with Node.js' `--shared-builtin-undici/undici-path` `configure` option. This allows Undici to exist on disk instead of being compiled into the Node.js binary. This is used by downstream Node.js packagers (e.g. Linux distributions, such as Fedora) that require the ability to build everything from source (including all dependencies and tooling). 
This functionality was regressed by https://github.com/nodejs/undici/pull/3074 and was not noticed as nothing in this repository broke.
Restore the ability to build Undici compatible with Node.js' `configure --shared-builtin-undici/undici-path ...` build option and adds a workflow …

fix: restore externalized Node.js dep compatibility

---

README.md

N/A
Example was added in https://github.com/nodejs/undici/pull/1035 in September 2021, when node 14/16 were still supported and WebStreams were added in v16.5.0.
The link can be switched to the default one, since undici supports >=18.17 where WebStreams are available.
Replaces 16.x link of Web Streams API with default link.
N/A
N/A
N/A
- [S] Tested

docs: use default link of Web Streams API

---

lib/web/fetch/response.js

Holding a reference to the stream in the finalization registry causes a memory leak, even when consuming the body.
https://github.com/orgs/nodejs/discussions/54248
and
https://github.com/vercel/next.js/discussions/68636
I believe we're maintaining a strong reference to `innerResponse.body.stream` even when the body is consumed.
Please see the above issues where many people are seeing a memory leak when Node is updated from 20.15.1 to 20.16.0
I was able to reproduce the issue (https://github.com/vercel/next.js/discussions/68636#discussioncomment-10270351) and use that to test in order to find the commit where things started breaking.
I'm not an expert on memory leaks, but this seems to make sense and fixes the issue.
It seems like this was introduced in …

fix: memory leak in finalization first appearing in v6.16.0

---

test/fetch/response.js

@mcollina I was able to finally get a minimal reproduction without using next or react 
https://github.com/snyamathi/undici-mem-leak
Looking at the chart, it does indeed appear to be a memory leak but it seems to be specific to Node's `AsyncLocalStorage` which is something that I dug out of the React source code [here](https://github.com/facebook/react/commit/cce18e3504fca651051da72cf9c2d126c16eb013)
This may actually have a root issue in Node itself which the team may want to be aware of - it seems like the reference prevents garbage collection so this same bug could bite others using `AsyncLocalStorage` in the same way.
-----
The test is a little round-a-bout in its testing, but it tries to assert that the body is garbage collected by checking that the weak ref becomes `undefined`.
This …

test: add test for memory leak

---

CONTRIBUTING.md
build/wasm.js

Enhances: https://github.com/nodejs/undici/pull/3421
The wasm-opt binary may be available in different place than the local directory (`./wasm-opt`) – for example, in `/usr/bin/wasm-opt`.
Similarly to the other parametrized WASM build options, use WASM_OPT environment variable to identify the wanted binary, with fallback to the previous value (`./wasm-opt`).
Even with the new environment variable, the `hasOptimizer` check is kept for the cases where no optimizer is available anywhere.
N/A
N/A
N/A

build: parametrize the location of wasm-opt

---

test/types/dispatcher.test-d.ts
types/dispatcher.d.ts

fixes #3168 
I still think, that it reduces the necessary strictness, as now also lowercased methods like "get" are allowed via types, but are invalid values. 
So at transpile time we get no warning if the value is wrong. But atleast we keep the autocomplete capability. 
I  think that #3168 should be closed as on wont fix, but here is the solution.
For more inforation for the solution see https://github.com/fastify/fastify/pull/5046

types: allow non strict HTTPMethod

---

lib/web/fetch/body.js
lib/web/fetch/request.js
lib/web/fetch/response.js

This also changes bodyUnusable to follow the spec better.

use bodyUnusable to check if body is unusable

---

lib/dispatcher/balanced-pool.js

Using the recursive way of calculating the gcd is slower than the non-recursive way, especially when using map and reduce.... it basically means calling functions over and over...  So this PR aims to reduce the overhad an function calls
benchmark script and results
<details>
```js
import { bench, group, run } from 'mitata'
import assert from 'assert'
function euclidianRecursive (a, b) {
if (b === 0) return a
return euclidianRecursive(b, a % b)
}
function euclidianLinear (a, b) {
if (a === 0) return b
while (b !== 0) {
const t = b
b = a % b
a = t
}
return a
}
function euclidianSwap (a, b) {
if (a === 0) return b
if (b === 0) return a
if (a < b) {
([a, b] = [b % a, a])
} else {
a %= b
}
let t = b
while (b !== 0) {
t = b
b = a % b
a = t
}
return a
}
function gcdTest (gcd) {
let data = [0, 0] …
```

perf: non-recursive implementation of euclidian gcd in balanced pool

---

lib/api/readable.js
lib/dispatcher/agent.js
lib/dispatcher/balanced-pool.js
lib/dispatcher/client.js
lib/dispatcher/pool.js
lib/dispatcher/proxy-agent.js
lib/interceptor/dump.js
lib/mock/mock-client.js
lib/mock/mock-pool.js

Highly opinionated change. Or is there some hidden logic, which says, that super() calls are optimized in v8?

fix: do validation first before actual business logic, like super()

---

lib/web/fetch/body.js
lib/web/fetch/request.js
lib/web/fetch/response.js
test/fetch/fire-and-forget.js

running test with `node --expose-gc --test test/fetch/fire-and-forget.js`
<details>
<summary>Before</summary>
```
RSS 66 MB after 50 fetch() requests
RSS 68 MB after 100 fetch() requests
RSS 76 MB after 150 fetch() requests
RSS 84 MB after 200 fetch() requests
RSS 93 MB after 250 fetch() requests
RSS 101 MB after 300 fetch() requests
RSS 110 MB after 350 fetch() requests
RSS 117 MB after 400 fetch() requests
RSS 125 MB after 450 fetch() requests
RSS 133 MB after 500 fetch() requests
RSS 141 MB after 550 fetch() requests
RSS 134 MB after 600 fetch() requests
RSS 143 MB after 650 fetch() requests
RSS 149 MB after 700 fetch() requests
RSS 155 MB after 750 fetch() requests
RSS 163 MB after 800 fetch() requests
RSS 171 MB after 850 fetch() requests
RSS 178 MB after 900 fetch() requests
RSS 185 …
```

use FinalizationRegistry for cloned response body

---

lib/dispatcher/client.js

trivial change. isIP will first run isIPv4 and then isIPv6. Also both are basically calling regexes on node. So by calling isIPv6 directly we improve the performance.

perf: use isIPv6 for checking if hostname is isIPv6

---

lib/mock/mock-symbols.js

kOriginalDispatch is not existing, thus resulting in being  undefined. It works as long there are not two keys missing...

fix: add missing kOriginalDispatch Symbol in mock-logic

---

lib/web/eventsource/eventsource.js
lib/web/fetch/formdata.js
lib/web/fetch/request.js
lib/web/websocket/websocket.js

USVString only expects a value parameter.

fix: remove unnecessary parameters in USVString calls

---

lib/web/cookies/index.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/websocket/connection.js

we have the parameter isLowerCase for performance reasons as we can provide header names as lowercase strings. As such it does not need to transform the header names to lowercase, increasing the performance

perf: set isLowerCase param on all calls of HeadersList.append

---

lib/interceptor/response-error.js

It is disputable. Maybe body should not be passed as data?

fix: instantiation of ResponseError, pass headers and data correctly

---

.github/workflows/nightly.yml

[meta]
This change has the issue that is created when nightly tests fail use the issue body for text, rather than creating a seperate comment.

meta: move nightly comment body to issue body

---

lib/web/cookies/index.js
lib/web/cookies/parse.js

chore: improve jsdoc in cookies

---

lib/web/eventsource/eventsource-stream.js
lib/web/eventsource/eventsource.js

chore: improve jsdoc and minor changes in EventSource

---

lib/core/errors.js
test/proxy-agent.js
types/errors.d.ts

calling super(message, options) was not working.
Is there a reason, that we set cause "manually"?

fix: instantiation of SecureProxyConnectionError should pass options to parent class

---

package.json

super annoying. if you run npm run test:typescript, than it would generate the corresponding `test/imports/undici-import.js`.If you then run lint, you get linting errors.
This PR makes the tsc call not generating the js file.

chore: add --noEmit for typescript tests

---

test/types/mock-agent.test-d.ts
types/mock-agent.d.ts

fix(types): MockAgent accepts ProxyAgent, EnvHttpProxyAgent and RetryAgent for agent option

---

lib/web/cookies/index.js
lib/web/fetch/webidl.js
test/cookie/global-headers.js
types/webidl.d.ts

stricter Headers brand checks in cookies

---

lib/api/readable.js
test/client-request.js

Fixes #1125 
Super old bug #1125 is the result of some premature encoding of already buffered content in node core.
https://github.com/nodejs/node/blob/4e68b541fd7ccd9fe1328d5b4dc93a3689aa505d/lib/internal/streams/readable.js#L585
This PR overwrites the setEncoding function, with a custom solution which is not encoding the buffered content.

fix: setEncoding should not throw on body #1125

---

lib/web/websocket/websocket.js
test/websocket/issue-3506.js

Fixes https://github.com/nodejs/undici/issues/3506

websocket: set websocket readyState on fail

---

lib/dispatcher/client-h1.js

Potentially fixes #2143 ?
tbh... I investigated the heap and saw alot of Timeouts (of our fast timers implementation) dangling(?) with onParserTimeout as callback. I guess when you run it for 6 minutes, like in the reproduction of the  reported issue, some of those timeouts keep dangling and get not gc'ed?
Anyhow... this PR seems to reduce the memory usage anyway?!
So please review/take it with a grain of salt. 
before:
```sh
aras@aras-Lenovo-Legion-5-17ARH05H:~/workspace/undici$ node --expose-gc test/fetch/fire-and-forget.js 
RSS 90 MB after 50 fetch() requests
RSS 94 MB after 100 fetch() requests
RSS 105 MB after 150 fetch() requests
RSS 119 MB after 200 fetch() requests
RSS 132 MB after 250 fetch() requests
RSS 143 MB after 300 fetch() requests
RSS 154 MB after 350 fetch() requests
RSS …
```

fix: avoid  memoryleak in client-h1

---

.github/workflows/autobahn.yml
.github/workflows/nightly.yml
.github/workflows/triggered-autobahn.yml

step 1. make autobahn reusable
step 2. run autobahn in ci
step 3. ???
step 4. profit.

ci: make autobahn workflow reusable workflow, run the autobahn on nightly tests

---

lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/webidl.js
lib/web/websocket/websocket.js
test/webidl/converters.js

remove double validation in webidl

---

test/fetch/fetch-leak.js
test/fetch/fire-and-forget.js
test/fetch/response.js
test/gc.js

Now it will throw a helpful error, when gc is not exposed

test: improve gc detection

---

lib/web/fetch/webidl.js
test/webidl/converters.js

… undefined
The test explains the commit purpose better.
`benchmarks/fetch/request-creation.mjs` was consistently 10-15% faster. Not sure how @Uzlopak @tsctx, was this a fluke?

populate defaultValues in webidl dict. converter when passing null or undefined

---

lib/web/fetch/headers.js
lib/web/fetch/webidl.js
lib/web/websocket/websocket.js
test/webidl/converters.js
test/webidl/util.js
types/webidl.d.ts

change webidl.util.Type return to an enum value

---

lib/web/fetch/request.js
lib/web/fetch/response.js

now that c108287b85e63bf7c5ef0613c20bd0ee40474897 has landed, this can be done. 
a micro-optimization, but a harmless change

set default argument values to undefined instead of {}

---

.github/workflows/autobahn.yml

ci: fix nightly workflow

---

lib/web/fetch/formdata.js
test/fetch/formdata.js

```js
var fd = new FormData()
fd.set('key', new Blob([]), undefined)
fd.get('key').name // should be 'blob'
fd.append('key1', new Blob([]), undefined)
fd.get('key1').name // should be 'blob'
```
I painfully found out that the wpts are not extensive

fix formdata arg validation

---

package.json
types/eventsource.d.ts
types/patch.d.ts
types/websocket.d.ts

Fixes #3524
PR #3531
Several missing DOM types from `@types/node` were added as part of `patch.d.ts`. `Event` & `EventTarget` exported DOM types in global were overwritten with `patch.d.ts`.
* Remove patched `Event` & `EventTarget` type and references to it from other declaration files.
* Lock version for `@types/node` to `~18.17.19`.
N/A
* Fixes typing bug related to DOM `Event` type.
N/A
`@types/node` version was updated to reflect the minimum supported engine version in `package.json`.

Remove patched DOM types

---

package.json
types/eventsource.d.ts
types/filereader.d.ts
types/patch.d.ts
types/websocket.d.ts

Fixes #3524
Several missing DOM types from `@types/node` were added as part of `patch.d.ts`. `Event` & `EventTarget` exported DOM types in global were overwritten with `patch.d.ts`.
* Remove patched `Event` & `EventTarget` type and references to it from other declaration files.
* Lock version for `@types/node` to `~18.17.19`.
N/A
* Fixes typing bug related to DOM `Event` type.
N/A
This only applies to branch `v6.x`, which is the latest stable version available currently. This will also need to be ported for the `main` branch, where the major version was bumped to v7.
`@types/node` version was updated to reflect the minimum supported engine version in `package.json`.

Remove patched dom types (`v6.x` branch)

---

lib/dispatcher/client-h1.js

chore: minor changes in client-h1, use subarray instead of slice

---

lib/api/api-upgrade.js
lib/core/connect.js
lib/core/util.js
lib/dispatcher/client-h1.js
lib/dispatcher/client.js

this PR tries to run various asserts before instantiating variables. also use assert instead of assert.strictEqual because passing boolean values is cheaper than passing primitive and non-primitive values to the assert.strictEqual function.

fix: run asserts first if possible

---

lib/api/api-pipeline.js
lib/api/api-request.js
lib/api/api-stream.js
lib/core/util.js

According to @mcollina noop in the same file is better optimized by v8
https://github.com/fastify/avvio/pull/215#pullrequestreview-1496769952

chore: noop per file

---

lib/core/request.js
lib/core/util.js
lib/mock/mock-interceptor.js
lib/mock/mock-utils.js
test/node-test/util.js

imho it makes the purpose more clear

chore: rename buildUrl to serializePathWithQuery + jsdoc

---

lib/core/util.js

add jsdoc to the utils.js file to improve typings in other places.
also made minor changes, which i will comment

fix: add jsdoc and do minor changes in utils.js

---

lib/dispatcher/client-h1.js

Fixes #3553 
This PR targets the fast-timer-connect branch of PR #3552 
@ronag 
Is this to your liking?

fix: use native timeouts for TIMEOUT_IDLE, rename TIMEOUT_IDLE to TIMEOUT_KEEP_ALIVE

---

lib/web/websocket/connection.js
lib/web/websocket/receiver.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js
test/websocket/issue-3546.js

handle websocket closed correctly

---

lib/dispatcher/client.js
lib/dispatcher/proxy-agent.js
lib/web/fetch/index.js

fix: extract noop everywhere

---

lib/web/websocket/util.js

we could add `// @ts-check` at the top of the file

chore: add jsdoc for lib/web/websocket/util.js, minor rewrite of utf8Decode

---

lib/api/readable.js
lib/core/util.js
test/types/readable.test-d.ts
types/readable.d.ts

Adds jsdoch to readable, fixes some aspects which i will comment

jsdoc: lib/api/readable.js, fix some types

---

package.json

it seems like latest typescript brakes the typing tests. This PR updates the deps accordingly...

chore: update typescript testing deps

---

lib/core/tree.js

minor changs... not changing logic.

chore: improve jsdoc of lib/core/tree.js

---

lib/core/util.js

now it returns the same type as the provided argument.

jsdoc: improve typing of deepClone

---

lib/core/constants.js

chore: improve jsdoc of lib/core/constants.js

---

lib/dispatcher/fixed-queue.js

sync with nodejs implementation

chore: upgrade fixed queue, lint accordingly, add jsdoc

---

test/request-timeout.js

The CI is a little bit flaky because fast timer resolution is making the underlying test not fail always as expected. This should fix it ;)

ci: less flaky test/request-timeout.js test

---

lib/mock/mock-errors.js

Error.captureStackTrace is not necessary because the stack trace will be generated when calling super().

mock: remove Error.captureStackTrace in MockNotMatchedError

---

.husky/pre-commit

Fixes #3592
husky made changes on how it is used on v9. See https://github.com/typicode/husky/releases/tag/v9.0.1 for more information.
* fix husky deprecation warning
_N/A_
_N/A_
* fix husky deprecation warning

fix: husky deprecation warning

---

package.json

https://github.com/nodejs/undici/pull/3593#issuecomment-2348013546
`pre-commit` usage (introduced with commit 25b8a5480ce7fe620911c94683520b3e02b01306) has been replaced with husky in #605.
* remove `pre-commit` from `devDependencies` in `package.json`
N/A
N/A
N/A

chore: remove unused `pre-commit` dependency

---

lib/core/diagnostics.js

In engines we declare that we support node >= 18.17. and the new subscribe notation is existitng since 18.7. 
https://nodejs.org/api/diagnostics_channel.html#diagnostics_channelsubscribename-onmessage

diagnostics-channel: use not deprecated subscribe fn

---

lib/web/cache/cache.js
lib/web/fetch/util.js

closer to the spec and avoiding an async call.

fetch: make fullyReadBody sync

---

docs/docs/api/Client.md

Fix small typo in `Client.md` documentation.
- [S] Tested

fix: typo in Client.md

---

lib/web/fetch/index.js

We can avoid some promises here.

fetch: avoid async function in mainFetch to generate response

---

lib/web/fetch/body.js
test/fetch/issue-3624.js

fixes #3624 
this change is harmless. Servers that don't care should ignore it.

append crlf to formdata body

---

lib/web/websocket/websocket.js
test/websocket/issue-3546.js

See nodejs/undici#3546, nodejs/undici#3548 & nodejs/undici#3565
CC: @Uzlopak @KhafraDev
#3565 attempted to fix #3546, however the test for #3546 made in #3548 was modified in #3565 and [skipped the `close` event check](https://github.com/nodejs/undici/pull/3565/files#r1749099808), which ultimately ended up with not actually fixing the original issue. This PR will check the `close` event correctly and correctly fixes the original issue.
Additionally, [this commit has been already tested to make sure it passes the autobahn testsuite](https://github.com/eXhumer/undici/actions/runs/10758006235/job/29832745599)
* correctly fire `close` event if there is no successful connection to server.
* fix test to actually check the `close` event correctly firing.
_N/A_
* correctly fire `close` event on …

fix: fire `close` on failed WebSocket connection

---

lib/web/websocket/constants.js
lib/web/websocket/receiver.js
lib/web/websocket/websocket.js
test/websocket/issue-3546.js

probably relies on #3627 landing first
the way we previously handled closing made no sense; either side could send/receive a close frame, but the closing handshake is only completed \_cleanly\_ when the said side sends & receives a close frame. We were only tracking a single state, and then we had a `receivedClose` boolean property... which is very confusing
now we know if a closing handshake
- has started (sent OR received close frame)
- has completed (sent AND received close frame)
- was closed cleanly (same logic as the bullet point above)
I have no idea if this will pass the autobahn tests, but it's too late for me to be running them (they take forever)

fix: fire close on failed WebSocket connection

---

index.js
lib/web/cache/cache.js
lib/web/cache/cachestorage.js
lib/web/cache/symbols.js
lib/web/fetch/body.js
lib/web/fetch/formdata.js
lib/web/fetch/headers.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/symbols.js
lib/web/fetch/util.js
test/fetch/issue-3630.js
test/fetch/response.js
test/fetch/spread.js
test/node-fetch/response.js

No longer exposes symbols in FormData, Request, and Response. The same change was made for Headers a little while back.

Remove symbols from web specs

---

lib/web/fetch/body.js
lib/web/fetch/headers.js
lib/web/fetch/util.js
test/fetch/spread.js
test/wpt/runner/worker.mjs

- removes kHeadersSortedMap from Headers' prototype
- fix wpt runner (we were `import`ing from a file which was removed

cleanup web symbol removal

---

docs/docs/api/WebSocket.md
index.js
test/wpt/runner/worker.mjs
types/websocket.d.ts

export WebSocketStream and WebSocketError, add minimal docs, and types.

export WebSocketStream, add docs and types

---

lib/web/websocket/receiver.js
lib/web/websocket/stream/websocketstream.js
lib/web/websocket/websocket.js

both \_fail the websocket connection\_ and \_close the websocket connection\_ do fundamentally the same things, but failing it will emit an error event (for WebSocket) which is a better fit for these cases

prefer fail over close the websocket connection in error cases

---

lib/mock/mock-utils.js
test/mock-interceptor.js
test/mock-utils.js

mock: fix mocking of Uint8Array and ArrayBuffers as provided mock-responses

---

lib/web/websocket/connection.js
lib/web/websocket/stream/websocketstream.js
lib/web/websocket/util.js
lib/web/websocket/websocket.js

testing the waters (autobahn tests)

ws: move implementation agnostic onFail logic to shared function

---

lib/web/fetch/formdata-parser.js
test/busboy/issue-3676.js

ignore leading and trailing crlfs in formdata body

---

lib/web/cookies/index.js
test/cookie/cookies.js
test/cookie/global-headers.js
test/node-test/debug.js
test/request.js

If you run those test cases with ` --no-experimental-fetch`  they will fail. They use on purpose the global HEaders and this PR makes it clear that they use globalThis.Headers and not by accident undici own Headers.

test: use globalThis.Headers and skip if is missing

---

lib/web/cache/cache.js
lib/web/cookies/index.js
lib/web/fetch/body.js
lib/web/fetch/formdata-parser.js
lib/web/fetch/formdata.js
lib/web/fetch/index.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/util.js
lib/web/fetch/webidl.js
lib/web/websocket/events.js
lib/web/websocket/stream/websocketerror.js
lib/web/websocket/stream/websocketstream.js
lib/web/websocket/websocket.js
test/webidl/helpers.js
types/webidl.d.ts

As a side note, but not majorly important: isPrototypeOf is also resilient against Symbol.hasInstance shenanigans. The real benefit is needing less imports to perform brand checks now that it is unified.

replace instanceof in brand checks with isPrototypeOf

---

test/fetch/client-node-max-header-size.js

missed this test when wanting to make test run without internet

test: make fetch test independent from internet connection

---

lib/web/fetch/util.js

While I investigated if there were significant changes in esbuild, I found the following change:
So the comments were added because they were of  `/** */`  notation and not of `//` notation. While I fixed, I saw that the implementation is not matching 1:1 the spec text, like the order of the cases. So I adapted it accordingly.

fix: restructure determineRequestsReferrer to match better spec

---

lib/web/fetch/index.js
lib/web/fetch/util.js
test/fetch/issue-3616.js

[Backport v6.x] handle body errors

---

lib/web/websocket/websocket.js
test/websocket/issue-3697-2399493917.js

https://github.com/nodejs/undici/issues/3697#issuecomment-2399493917
A websocket connection is closed in two ways: 1) when the socket closes, or 2) if a connection could not be established. We were only setting the readyState in the first case.

set ws readyState if closed before connection could be established

---

lib/web/fetch/constants.js
lib/web/fetch/util.js
test/fetch/referrrer-policy.js
test/fetch/util.js

The helper function for the referrer policy are not that strict. This PR improves the spec conformance.

fetch: refactor referrer policy util functions

---

lib/dispatcher/client-h1.js

fix: add more expectsPayload methods

---

lib/dispatcher/pool-base.js

other classes based on DispatcherBase are not returning but awaiting the Promise. So it streamlines PoolBase with the others.

fix: PoolBase kClose and kDestroy should await and not return the Promise

---

benchmarks/fetch/webidl-is.mjs
lib/web/fetch/formdata.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/webidl.js
lib/web/websocket/stream/websocketerror.js
test/webidl/helpers.js
types/webidl.d.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Symbol.hasInstance#reverting_to_default_instanceof_behavior
- main
```shell
benchmark              avg (min … max) p75   p99    (min … top 1%)
-------------------------------------- -------------------------------
webidl.is.FormData (ok)   7.17 ns/iter   6.91 ns  █▄
(6.20 ns … 150.63 ns)  14.65 ns ▁██▃▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
webidl.is.FormData (b..   8.81 ns/iter   9.03 ns █
(7.62 ns … 101.73 ns)  18.87 ns █▄▁▄▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁
instanceof (ok)          22.41 ns/iter  23.14 ns  █
(19.60 ns … 63.67 ns)  43.04 ns ▁█▂▁▄▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
instanceof (bad)         23.51 ns/iter  22.61 ns  █
(20.53 ns … 122.12 ns)  47.97 ns ▁█▂▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
┌                                            ┐
webidl.is.FormData (ok) …
```

faster brand check

---

lib/dispatcher/client-h1.js

analogue to #3722 this PR extracts the functions from the client function.

http: extract listeners from client-h1

---

lib/web/websocket/constants.js

we could add `// @ts-check` at the beginning of the file.

chore: add jsdoc to lib/web/websocket/constants.js

---

lib/api/readable.js

fixes #3610
We dont need to wrap non awaited Promises/async calls.

chore: remove redundant async in readable.js

---

test/types/fetch.test-d.ts
types/fetch.d.ts

fix(types): add missing `cache` prop to RequestInit

---

lib/core/util.js
lib/handler/cache-handler.js
lib/handler/cache-revalidation-handler.js
lib/interceptor/cache.js
lib/util/cache.js
types/cache-interceptor.d.ts

[http-cache] follow up

---

lib/web/cache/cache.js
lib/web/cache/cachestorage.js
lib/web/eventsource/eventsource.js
lib/web/fetch/formdata.js
lib/web/fetch/headers.js
lib/web/fetch/request.js
lib/web/fetch/response.js
lib/web/fetch/webidl.js
lib/web/websocket/events.js
lib/web/websocket/websocket.js
test/node-platform-objects.js
types/webidl.d.ts

* web: mark as uncloneable when possible
This tells node that the marked instances from undici are not cloneable, so that attempts to cloning those throw `DataCloneError`.
* test: add test cases for platform objects uncloneable
* fix: move to webidl
* fix: move it under webidl
* fixup: rename it to markAsUncloneable
* fix: mark more web instances uncloneable
* fixup
---------
Co-authored-by: Khafra <maitken033380023@gmail.com>
(cherry picked from commit 1ab238207d84196479428494d52fc922833e8e5b)

[Backport v6.x] web: mark as uncloneable when possible (#3709)

---

lib/web/fetch/body.js
lib/web/fetch/formdata-parser.js
test/busboy/issue-3760.js

fixes #3760 
also fixes a case where we were too strict by disallowing spaces after `filename` and `filename*` parameters. The RFC uses examples with spaces ([`filename*= UTF-8''%e2%82%ac%20rates`](https://datatracker.ietf.org/doc/html/rfc6266#section-5))
it also adds a cause to errors that gives a little more information rather than the bland "failed to parse form-data!" one

fix filename* parsing

---

docs/docs/api/Dispatcher.md

Documentation for dispatcher.request() 
It is very easy to cause a memory leak or even crash the process if you forget to handle the response body.
A new example showing how to conditionally reading the body
N/A
N/A
N/A

chore(docs): add request() example for conditionally reading the body

---

lib/interceptor/dns.js
test/interceptors/dns.js

How long time to cache the dns records from the dns interceptor.
For how long time the dns records from the dns interceptor should live.
Set timestamp once on each resolved record and compare the ttl to that timestamp. If the record is too old, remove it.
N/A

fix: dns interceptor ip ttl

---

lib/interceptor/dns.js
test/interceptors/dns.js

DNS interceptor
* error was thrown when a single ip address was resolved with dual-stack: "Cannot read properties of null (reading 'offset')"
* `pick` always started on the second ip address if multiple were resolved
* affinity was ignored with dual-stack
Always start pick with the first ip address when multiple are resolved (ipv4 before ipv6)
Prefer affinity family with dual-stack, fallback to other family
Handle single ip address resolved with dual-stack

fix: dns interceptor affinity

---

index.js
lib/web/cookies/index.js
lib/web/cookies/parse.js
test/cookie/npm-cookie.js
types/cookies.d.ts

adds a new `parseCookie` method that takes in a string rather than a Headers instance
fixes one test failure (decodes cookie values now)

add tests from cookie package

---

lib/api/api-request.js
lib/dispatcher/client-h2.js
test/http2.js

fix: http2 queueing

---

lib/interceptor/dns.js
test/interceptors/dns.js

DNS interceptor
Support custom functions that resolve both IP addresses and ports. It can be used e.g. with `dns.resolveSrv` followed by
`dns.resolve`.
Change priority of the port used to:
1. Resolved address port
2. Origin port
3. Default protocol port
Use port on resolved address.

feat: use resolved ports in dns interceptor

---

lib/cache/memory-cache-store.js
lib/handler/cache-handler.js
lib/handler/cache-revalidation-handler.js
lib/interceptor/cache.js
types/cache-interceptor.d.ts

The first of a future sequence of post-merge review PR's...
@flakey5 feel free to close this PR and open a new one based on this one.

fix: cache

---

README.md
benchmarks/benchmark.js
docs/docs/api/Dispatcher.md
lib/core/request.js
test/client-connect.js
test/client-idempotent-body.js
test/client-pipelining.js
test/client-upgrade.js
test/client.js
test/fetch/long-lived-abort-controller.js
test/node-test/client-abort.js
test/node-test/client-connect.js
test/pipeline-pipelining.js
test/promises.js
types/dispatcher.d.ts

fix: assume blocking unless HEAD

---

index.d.ts
test/imports/undici-import.ts

https://github.com/neostandard/neostandard/actions/runs/11543696852/job/32128394927?pr=197

refactor: silence neostandard import rules error

---

docs/examples/proxy/fetch.mjs

https://github.com/nodejs/undici/issues/3508
Add documentation for using proxy with fetch
added exmaple of using proxy with fetch

docs: add example using proxy with fetch

---

test/node-test/debug.js

Related #3809, https://github.com/nodejs/undici/issues/3787

Skip debuglog tests

---

lib/dispatcher/client-h2.js

I've seen the HTTP2 goaway test fail a bunch, and I've tried a fix.

h2: do not emit data after goaway

---

lib/handler/redirect-handler.js
test/interceptors/redirect-issue-3803.js
test/types/interceptor.test-d.ts
types/index.d.ts
types/interceptors.d.ts

fix redirect interceptor with FormData body

---

docs/docs/api/BalancedPool.md
docs/docs/api/MockClient.md
docs/docs/api/Pool.md
docs/docs/api/api-lifecycle.md
docs/docs/best-practices/mocking-request.md
docs/docs/best-practices/proxy.md
docs/docsify/sidebar.md
docs/index.html

https://github.com/nodejs/undici/issues/3322
https://github.com/nodejs/undici/issues/3748
Using `renderer` for `links` can format them to route to appropriate page and not break readmes in github repo.
Absolute links will need to be used updated them for links in `docs/docs/api/` instead of relative links
https://github.com/user-attachments/assets/a519cb04-08a9-4073-9e5e-ac75e32dd6f5
https://github.com/nodejs/undici/issues/3322
https://github.com/nodejs/undici/issues/3748

docs: fix broken links in undici webpage

---

lib/handler/redirect-handler.js
test/redirect-request.js

#3777
This is a follow up MR addressing that: https://github.com/nodejs/undici/pull/3777#discussion_r1833340766

fix: handle undici Headers and Maps in redirect-handler

---

lib/handler/retry-handler.js
test/interceptors/retry.js

The retry interceptor treats the `end` parameter of the `Range` or `Content-Range` header as 1-indexed (or 0-indexed but exclusive), leading to an error, for example, when the `Content-Range` header is not present and `end` is assigned to the value of the `Content-Length` header:
```shell
AssertionError [ERR_ASSERTION]: content-range mismatch
at RetryHandler.onHeaders (D:\_\node_modules\undici\lib\handler\retry-handler.js:236:7)
at downstreamOnHeaders (D:\_\node_modules\undici\lib\handler\cache-handler.js:64:53)
at CacheHandler.onHeaders (D:\_\node_modules\undici\lib\handler\cache-handler.js:112:14)
at CookieHandler.onHeaders (D:\_\node_modules\http-cookie-agent\dist\undici\cookie_handler.js:43:28)
at Request.onHeaders (D:\_\node_modules\undici\lib\core\request.js:246:29)
at …
```

fix: range end is zero-indexed

---

docs/docs/api/CacheStore.md
lib/cache/memory-cache-store.js
lib/core/util.js
lib/handler/cache-handler.js
lib/handler/cache-revalidation-handler.js
lib/interceptor/cache.js
lib/util/cache.js
test/cache-interceptor/cache-stores.js
test/cache-interceptor/utils.js
test/interceptors/cache.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

Closes #3806
- Removes `CacheStoreReadable` and `CacheStoreWritable`, replaces w/ just `Readable` and `Writable`
- Reasoning: api simplicity
- Renames `CacheStoreValue` type to `CachedResponse`
- Removes `CacheStore#createReadStream` function (see one below on reasoning)
- Adds `CacheStore#get` function that acts similarly to `createReadStream`
- Reasoning: api simplicity & niceness. Returns a `GetResult` which separates the `CacheResponse` and `Readable` for the body
- Simplifies `MemoryCacheStore`
- Inline readable & writables
- `readLock` and `writeLock` condensed into just `locked` that only stops value from being read
- Introduces `CacheKey` type that we pass into the cache handler, cache stores
- Replaces us passing in the full request options
- Reasoning: cache stores don't need …

lib: more cache fixes

---

lib/cache/memory-cache-store.js
lib/handler/cache-handler.js
lib/interceptor/cache.js
lib/util/cache.js
test/cache-interceptor/cache-stores.js
test/interceptors/cache.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

fix: cache fixes

---

lib/core/request.js
lib/dispatcher/client-h2.js
test/http2.js

This PR changes how GOAWAY frames and user aborts are handled in HTTP/2.
In essence, we had a flaky test for a while that showed up locally on my machine after 2-3 hours of continuous runs. It's a bad race condition, which has been hard to find and a bad overlap between goaway, aborts, and manipulation of the `Client` state from the outside.

Fix goaway

---

lib/cache/memory-cache-store.js
types/cache-interceptor.d.ts

We should later add `maxEntriesSize`.

refactor: maxEntriesCount

---

lib/cache/memory-cache-store.js
test/cache-interceptor/cache-stores.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

fix: memory store

---

benchmarks/timers/now-absolute.mjs
lib/cache/memory-cache-store.js
lib/handler/cache-handler.js
lib/interceptor/cache.js
lib/util/timers.js
test/cache-interceptor/cache-stores.js
test/interceptors/cache.js
test/timers.js

This adds a `nowAbsolute` function to the fast timers lib that allows for fetching the approximate absolute timestamp. This is useful in places like the cache interceptor and cache stores, where we're currently calling `Date.now()`.
cc @mcollina

lib: add `nowAbsolute` to fast timers

---

docs/docs/api/CacheStore.md
lib/cache/memory-cache-store.js
lib/handler/cache-handler.js
lib/interceptor/cache.js
lib/util/cache.js
test/cache-interceptor/cache-stores.js
test/cache-interceptor/utils.js
test/interceptors/cache.js
types/cache-interceptor.d.ts

Re http caching, adds support for etags for when we need to revalidate a cached response.
No breaking changes to the public api. the `etag` property is nullable so a cache store _could_ just not implement it and it will be fine. However, I did add it to the tests as if it was required just so we can ensure the builtin cache stores fully support the behavior.
This only checks if the etag exists in the response's headers and ignores it if it's in the trailers for simplicity sakes (as allowed by the spec in [8.8.3](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.8.3-8))
Closes #3718

feat: cache etag support

---

lib/interceptor/cache.js
test/interceptors/cache.js

~~**Note**: this is a draft since https://github.com/nodejs/undici/pull/3562 isn't landed. Until it is landed, this will be based off of that pr's branch. For the actual diff see https://github.com/flakey5/undici/compare/flakey5/3231...flakey5:undici:flakey5/20240924/cli-cache-control~~
Adding client side http caching (https://github.com/nodejs/undici/pull/3562)
RFC9111 allows the request to specify a cache-control header with directives that can affect how we handle the request in the cache interceptor (re [5.2.1](https://www.rfc-editor.org/rfc/rfc9111.html#name-request-directives)). This adds support for them.
cc @mcollina @ronag

feat: support request cache control directives

---

lib/api/api-request.js
test/client-request.js
test/http2.js

This applies the changes in #3740 that failed automatic backport into `v6.x`. Our testing suggests that this resolves #3848.
Adds a no-op `"error"` event handler to the `res` stream when handling `AbortSignal` aborts in `request()` that was otherwise leading to process-level uncaught exceptions in our codebase.
N/A
Fixes #3736 in v6.x
Fixes #3848 in v6.x

fix(#3736): back-port 183f8e9 to v6.x

---

lib/handler/redirect-handler.js
test/interceptors/redirect.js
test/redirect-request.js
test/redirect-stream.js

Didn't open an issue before this PR so sorry if this is expected but I could not find any discussion about it.
The redirect handler doesn't change the method to `GET` when the status code is 301/302 and the original method is `POST` despite being the standard in fetch spec and browser behavior. Also the HTTP standard mentions this too:
> Note: For historical reasons, a user agent MAY change the request method from POST to GET for the subsequent request. If this behavior is undesired, the 307 (Temporary Redirect) status code can be used instead.
Method is changed to `GET` and body is removed when a 301/302 response code is received, aligning with fetch and browser behavior
The tests were updated to reflect this change and the ones specifically about request body/method were updated to use …

fix: 301 and 302 change method to GET

---

docs/docs/api/CacheStore.md
index.js
lib/cache/memory-cache-store.js
lib/cache/sqlite-cache-store.js
lib/util/cache.js
test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/memory-cache-store-tests.js
test/cache-interceptor/sqlite-cache-store-tests.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

~~**Note**: this is a draft since #3562 isn't landed. Until it is landed, this will be based off of that pr's branch. For the actual diff see https://github.com/flakey5/undici/compare/flakey5/3231...flakey5:undici:flakey5/20240910/sqlite-cache-store~~
Adding client side http caching (#3562)
Adds a sqlite cache store option given the `--experimental-sqlite` flag is provided
* Cache store using sqlite as a backend
n/a
n/a
cc @mcollina @ronag

feat: sqlite cache store

---

lib/dispatcher/client-h2.js
test/http2.js

refs: https://github.com/nodejs/undici/issues/3803#issuecomment-2490835431

fix: sending formdata bodies with http2

---

test/types/retry-handler.test-d.ts
types/retry-handler.d.ts

https://github.com/nodejs/undici/discussions/3824
Fix the return type of RetryCallback

Update return type of RetryCallback

---

docs/docs/api/Dispatcher.md
index.js
lib/interceptor/dns.js
test/interceptors/dns.js
types/interceptors.d.ts

fix(#3817): send servername for SNI on TLS (#3821) [backport]

---

lib/cache/sqlite-cache-store.js

fix: cleanup sqlite store

---

lib/cache/sqlite-cache-store.js

refactor: sqlite versioning

---

lib/handler/cache-handler.js
lib/handler/retry-handler.js
test/interceptors/retry.js

The retry and cache handlers do not pass down the context of the `onConnect` method. This means that using the redirect handler with one of them will not pass the context to the main handler:
```js
request("http://github.com", {
dispatcher: new Agent().compose(
interceptors.redirect({ maxRedirections: 1 }),
interceptors.retry(),
),
}).then((res) => console.log(res.context)); // undefined
request("http://github.com", {
dispatcher: new Agent().compose(
interceptors.redirect({ maxRedirections: 1 }),
),
}).then((res) => console.log(res.context)) // { history: [URL, URL] }
```
- Cache handler: used `...args` to pass all the args (like in the decorator handler)
- Retry handler: `onConnect` is now called on the first connection instead that in the constructor, allowing to pass the context …

fix: pass down context in onConnect

---

lib/handler/redirect-handler.js
test/interceptors/redirect.js
test/redirect-request.js

fix: we can redirect disturbed request body if it's not going to be used

---

lib/cache/sqlite-cache-store.js

perf: only prune if adding new entry

---

lib/dispatcher/client-h2.js

onHttp2SessionGoAway throws an error
```log
TypeError: Cannot read properties of undefined (reading 'onError')
at Object.errorRequest (node:internal/deps/undici/undici:3935:13)
at ClientHttp2Session.onHttp2SessionGoAway (node:internal/deps/undici/undici:5969:8)
at ClientHttp2Session.emit (node:events:513:28)
at ClientHttp2Session.emit (node:domain:489:12)
at Http2Session.onGoawayData (node:internal/http2/core:683:11)
at Http2Session.callbackTrampoline (node:internal/async_hooks:130:17)
```
The reason is `const request = client[kQueue][client[kRunningIdx]]` where request is empty.
Then I tried adding some console.log 
```javascript
function onHttp2SessionGoAway (errorCode) {
...
// Fail head of pipeline.
console.log('clinet[kRunningIdx]:', clinet[kRunningIdx])  // clinet[kRunningIdx]: 2 …
```

fix: Fixed the issue that there is no running request when http2 goaway

---

lib/cache/memory-cache-store.js
lib/cache/sqlite-cache-store.js
lib/handler/cache-handler.js
lib/handler/cache-revalidation-handler.js
lib/interceptor/cache.js
lib/util/cache.js
test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/sqlite-cache-store-tests.js
test/interceptors/cache.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

Closes #3853
This cleans up the cache interceptor file. This also makes the cache stores store the responses' cache control directives. This was the nicest way I could think of to implement stale-if-error and also sets it up nicely for if we ever allow for more cache control directive extensions.

cache: fix stale-while-revalidate and stale-if-error

---

lib/core/util.js
lib/handler/cache-handler.js
lib/handler/decorator-handler.js
lib/handler/redirect-handler.js
lib/handler/unwrap-handler.js

refactor: port redirect handler to new hooks

---

lib/cache/sqlite-cache-store.js
test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/sqlite-cache-store-tests.js

perf: store data as blobs in sql cache

---

docs/docs/api/Dispatcher.md
lib/handler/cache-handler.js
lib/handler/cache-revalidation-handler.js
lib/handler/redirect-handler.js
lib/handler/unwrap-handler.js
lib/handler/wrap-handler.js
lib/interceptor/cache.js
types/dispatcher.d.ts

fix: move statusMessage as optional arg in end

---

lib/core/errors.js
lib/interceptor/response-error.js
test/interceptors/response-error.js

This makes the `responseError` interceptor backward compatible.
`throwOnError` added a `err.body` property, while the interceptor adds a `err.data` property. I've renamed `data` to `body`.

Make the responseError interceptor backward compatible, add a body property

---

lib/interceptor/response-error.js
test/interceptors/response-error.js

The usual `Content-Type` for JSON is `application/json; charset=utf-8` due to some old incompatibility (https://github.com/fastify/fastify/issues/913).

Correctly parse JSON contentType in responseError interceptor

---

docs/docs/api/Client.md
lib/dispatcher/client-h2.js

Alternative to #3814. We just mark HTTP/2 as stable for now.
After speaking with multiple people, they _prefer_ not to use HTTP/2.

Mark http/2 support as stable

---

test/interceptors/dns.js

Fixes #3898
Use fake timers to reduce test flakiness

test: fix dns interceptor flakiness

---

lib/interceptor/dns.js

fix(#3901): migrate dns interceptor to new hooks

---

lib/handler/decorator-handler.js
lib/interceptor/dns.js
lib/interceptor/dump.js
lib/interceptor/response-error.js
test/decorator-handler.js

- **feat(interceptors): migrate decorator handler to new hooks**

feat(interceptors): migrate decorator handler to new hooks

---

index.js
test/cache-interceptor/sqlite-cache-store-tests.js

I am not really sure how to write a test for this...
N/A
This was a bit too restrictive for how big of a failure it can lead to
N/A
Fixes #3899
N/A

feat: Adjust allowed error codes for detecting node:sqlite

---

test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/sqlite-cache-store-tests.js
test/interceptors/cache.js
types/index.d.ts

The tests currently cover a good amount but are a bit messy. This cleans them up and adds some more checks around some required behaviors

test: cleanup cache tests

---

lib/web/fetch/data-url.js

The current code does not include *past the end of input*, so add equal sign.

fix mimetype parser wrong operator

---

README.md

See #3914
Added an example for `request` + "Garbage Collection".

Add example for `request` + "Garbage Collection"

---

lib/interceptor/response-error.js
test/interceptors/response-error.js

This [this issue](https://github.com/nodejs/undici/issues/3929) 
Use the correct method signature.

fix: response error interceptor

---

lib/interceptor/dns.js
test/interceptors/dns.js

fix(#3937): respect correct host header

---

lib/handler/wrap-handler.js
test/client-node-max-header-size.js
test/issue-3934.js

support array of headers in WrapHandler

---

index.js
lib/cache/sqlite-cache-store.js

`node:sqlite` is now unflagged, and it emits a warning every time it's loaded, and we load it every time. This PR prevents the warning by moving the require inside the constructor.

Support SQLite unflagged without useless warnings

---

docs/docs/api/ProxyAgent.md

Closes #3944 
We might want to adjust several options from the ProxyAgent for better scoping; but that might require a major bump on it.

docs: enhance documentation

---

lib/interceptor/dns.js
test/interceptors/dns.js

An undefined function error is thrown if the dns interceptor lookup or dispatch results in ENOTFOUND. The test depends on #3956  being merged first.

fix: dns interceptor undefined function

---

lib/interceptor/dns.js
test/interceptors/dns.js

fix(3951): typo on errorede dns lookup

---

lib/web/websocket/receiver.js
lib/web/websocket/util.js

Adjust to avoid creating a temporary buffer

websocket: improve frame parsing

---

lib/handler/retry-handler.js
test/interceptors/retry.js

fix(#3966): account for network errors

---

docs/docs/api/Dispatcher.md

docs: fix dispatcher stream example links

---

docs/docs/api/DiagnosticsChannel.md

On diagnostic channel message `undici:request:headers`, it does not indicate completion of a response. Remove the inaccurate doc line.
- [S] Tested

fix: `undici:request:headers` does not indicate completion of a response

---

test/interceptors/retry.js

fix: retry flaky test

---

lib/interceptor/dns.js
test/interceptors/dns.js

DNS interceptor
The DNS interceptor can be stuck in an infinite loop if dual-stack is enabled and a lookup results in a network error. It is also possible for a request to retry the same family multiple times if another request is made in-between.
Retry a failed request **once** with dual-stack and force it to use the other ip family.
If no valid ip address is found, e.g. due to ttl timeout, no retry should be made.

fix: dual-stack retries infinite loop

---

lib/core/util.js
test/fetch/issue-node-56474.js

refs: https://github.com/nodejs/node/issues/56474
ReadableByteStreamController.enqueue handles empty typed arrays differently than the normal ReadableStreamController: it throws an error when receiving one. To combat this, we didn't enqueue anything and did nothing if the buffer was empty. For whatever reason, this caused the promise to never resolve (I didn't dig into the spec long enough to figure out why, sorry). The fix is to simply continue pulling until we respond to the pull in some manner.
I am not a webstreams expert please review with caution.

ReadableStreamFrom pull until cannot on empty enqueu

---

lib/cache/sqlite-cache-store.js

fix: sqlite null ref

---

lib/cache/sqlite-cache-store.js

fix: sqlite remove unnecessary parameter

---

lib/cache/sqlite-cache-store.js
test/cache-interceptor/sqlite-cache-store-tests.js
types/cache-interceptor.d.ts

set is a more performant variant of createWriteStream for small responses...

feat: sqlite add set and minor cleanup

---

lib/cache/sqlite-cache-store.js

Doesn't make any difference in practice as byteOffset is always going to be 0 but it's theoretically more correct and could avoid future bugs.

fix: apply byte offset on Buffer.from

---

MAINTAINERS.md

This adds the instruction to issue a release.

Add release instructions

---

README.md
docs/docs/api/Errors.md

errors from node:internal leak #3987
As discussed in #3987 - errors are affected by global dispatcher
Docs about globalDispatcher being truely global
Docs about errors coming from globalDispathcer from another module
N/A
N/A
N/A
- [s] Tested
- [s] Benchmarked (**optional**)

docs: document about global dispatcher and errors (#3987)

---

docs/index.html

This PR will add simple click to copy button to all preformatted code blocks to effortlessly allow users to copy example code from the docs and format code
close: #4035

feat(docs): copy to clipboard button

---

lib/web/fetch/request.js
test/fetch/long-lived-abort-controller.js

don't check AbortSignal maxListeners on some node versions

---

docs/docs/api/EnvHttpProxyAgent.md
lib/dispatcher/env-http-proxy-agent.js

Looking at the issue tracker and the file history, it looks like the implementation has been quite stable since it was introduced, so I suggest we make the docs reflect that.
Remove the "Experimental" mention in the docs.
Remove the experimental warning
N/A
N/A
N/A

feat: mark `EnvHttpProxyAgent` as stable

---

lib/mock/mock-utils.js
test/mock-interceptor.js
test/mock-utils.js

N/A
See below (Bug Fixes)
See below (Bug Fixes)
N/A
When interceptor.reply would return `{ data: undefined }`, it blows up in `getResponseData`:
```
TypeError [Error]: Cannot read properties of undefined (reading 'toString')
at getResponseData (/Users/frederikprijck/Development/frederikprijck/undici/lib/mock/mock-utils.js:128:17)
at TestContext.<anonymous> (/Users/frederikprijck/Development/frederikprijck/undici/test/mock-utils.js:180:26)
at Test.runInAsyncScope (node:async_hooks:206:9)
at Test.run (node:internal/test_runner/test:639:25)
at Suite.processPendingSubtests (node:internal/test_runner/test:382:18)
at Test.postRun (node:internal/test_runner/test:730:19)
at Test.run (node:internal/test_runner/test:688:12)
at async Suite.processPendingSubtests …
```

fix: do not throw unhandled exception when data is undefined in interceptor.reply

---

lib/cache/memory-cache-store.js
lib/cache/sqlite-cache-store.js
lib/util/cache.js
test/cache-interceptor/utils.js
test/issue-3959.js
test/types/cache-interceptor.test-d.ts
types/cache-interceptor.d.ts

fixes: https://github.com/nodejs/undici/issues/3959

fix: handle missing vary header values

---

test/types/interceptor.test-d.ts
types/interceptors.d.ts

#3684 has backported the DNS interceptor from #3490. However, the func that is exported, was not added to TypeScript defs. Opts and return type were added with the backport already.
Allow v6 + TS users to hook the DNS interceptor in.
[fix(types): add missing DNS interceptor](https://github.com/nodejs/undici/commit/a235e2067402dfece6886c0a4ad84c2567a12698)

fix(types): add missing DNS interceptor

---

lib/handler/retry-handler.js
test/interceptors/retry.js
test/retry-handler.js

Fix retry-handler when retry-after header is a Date
Fix using original header retry-after for calculate timeout instead header casted to Number
Fix retry-handler when retry-after header is a Date
Fix test related using longer timeout 

fix: Fix retry-handler.js when retry-after header is a Date

---

lib/dispatcher/client.js
lib/dispatcher/pool.js
test/node-test/autoselectfamily.js
types/client.d.ts

Currently the options are only passed if they enable autoSelectFamily. However, if autoSelectFamily is the default, we want to be able to disable it too.
Noticed this while debugging https://github.com/nodejs/node/issues/47822#issuecomment-2689454370
https://github.com/nodejs/node/issues/47822#issuecomment-2689454370
Currently this claims to accept a boolean but really only accepts `true`.
React to the autoSelectFamily option if it is passed in.
Agent's can disable autoSelectFamily
None?

Allow disabling autoSelectFamily in an Agent

---

lib/handler/cache-revalidation-handler.js

Include if-not-modified as a potential header which can tell the origin we want to revlidate.
The current comment implies that `if-modified-since` is the only header relevant to revalidation.
- [S] Tested

CacheRevalidationHandler: add missing header to comment

---

docs/docs/api/Dispatcher.md
test/types/dispatcher.test-d.ts
types/dispatcher.d.ts

https://github.com/nodejs/undici/issues/3840
- Export `UndiciHeaders`
- Set dispatcher headers type to `UndiciHeaders`
- Add tests to `test/types/dispatcher.test.d.ts`

fix: export UndiciHeaders type and set dispatch headers to UndiciHeaders

---

docs/examples/README.md

Resolves https://github.com/nodejs/undici/issues/4120#issuecomment-2753713036. Updates the DNS caching example to use Undici’s own DNS interceptor rather than recommending an external library; and adds the retry and response caching interceptors to make the example more representative of a typical production configuration. cc @mcollina

Update DNS caching example to include other interceptors, production configuration

---

lib/cache/sqlite-cache-store.js

- Drop unnecessary single-column indices (url, method, start alone), as the composite index effectively covers them.
- Avoid redundant indices that can slow down inserts without additional query benefits.

cache: more efficient sqlite indices

---

test/types/websocket.test-d.ts
types/websocket.d.ts

N/A
`ReadableStream` and `WritableStream` were not imported in the typings. This pull request imports them from `stream/web`.
N/A
Fixes TypeScript compilation error:
```
types/websocket.d.ts(167,15): error TS2304: Cannot find name 'ReadableStream'.
types/websocket.d.ts(168,15): error TS2304: Cannot find name 'WritableStream'.
```
https://github.com/discordjs/discord.js/actions/runs/13081715315/job/36506493876
N/A

types(websocket): Import from stream/web

---

docs/docs/api/MockAgent.md
lib/mock/mock-agent.js
lib/mock/mock-symbols.js
lib/mock/mock-utils.js
test/mock-agent.js
test/mock-utils.js
test/types/mock-agent.test-d.ts
types/mock-agent.d.ts

This PR adds a new `acceptNonStandardSearchParameters` option to make
instances of `MockAgent` accept search parameters specified
using non-standard syntaxes such as multi-value items specified with `[]`
(e.g. `param[]=1&param[]=2&param[]=3`) and multi-value items which values
are comma separated (e.g. `param=1,2,3`) 
With these changes `MockAgent` instances can be enabled to intercept requests
such as `https://example.com/qux-c?arraykey[]=a&arraykey[]=b`, etc...
MockAgents created with the `acceptNonStandardSearchParameters` "normalize" requests such as `https://example.com/qux-c?arraykey[]=a&arraykey[]=b` into ones like
`https://example.com/qux-c?arraykey=a&arraykey=b` so that they can then be handled normally
N/A
Fixes https://github.com/nodejs/undici/issues/4146
None
- [S] Benchmarked …

feat: add new `acceptNonStandardSearchParameters` MockAgent option

---

lib/dispatcher/client-h2.js
test/http2.js

When passing a flat header array and using HTTP/2, duplicate keys were discarded and lost unexpectedly.
In addition, the value-combining formatting (effectively `join(',')`) for explicitly array-valued headers in HTTP/2 didn't quite match the formatting for both Undici HTTP/1 or for Node HTTP/2's value-combining behaviour for headers that differ only by case (both of which do `join(', ')` - i.e. with whitespace) which was a bit weird.
```js
const client = new undici.Client('https://testserver.host', { allowH2: true })
client.request({
method: 'GET',
path: '/anything',
headers: ['a', 'b', 'a', 'c']
}).then(async (response) => {
console.log(await response.body.text())
})
```
The response shows what the server receives: headers including `a: c` but without `a: b` (all but the last header …

Ensure conflicting flat headers in HTTP/2 are combined correctly

---

docs/docs/api/DiagnosticsChannel.md

It looks like the code is intended to show the headers before and after addHeader, so the console.log('headers') line appears to be missing the actual value and was likely an oversight.
N/A
N/A
N/A

Fix missing code in diagnostics example

---

lib/cache/memory-cache-store.js
lib/interceptor/cache.js
test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/cache-tests-worker.mjs
test/cache-interceptor/sqlite-cache-store-tests.js
test/interceptors/cache.js

The cache tests were not being run. Restore them and add a check to prevent this situation to happen again.
Moreover, it fixes a bug in the memory storage that prevented the max-age and expiry directives to work properly.
fixes https://github.com/nodejs/undici/issues/4203

Restore cache tests & fix max-age behavior

---

.github/workflows/nodejs-shared.yml
.github/workflows/nodejs.yml
test/http2.js
test/wpt/status/fetch.status.json

add node v24 workflow

---

.gitignore

When I run `pnpm install` it creates a lockfile and I accidentally commit it.
This doesn't happen when I run `yarn install` or `npm install` because they are already ignored. So we should also ignore pnpm lock file.
Add `pnpm-lock.yaml` to `.gitignore`
N/A
N/A
N/A

chore: add `pnpm-lock.yaml` to `.gitignore`

---

lib/dispatcher/agent.js
lib/mock/mock-agent.js

There was a TODO introduced in a previous PR:
- https://github.com/nodejs/undici/pull/2536
There is a known memory leak
Track the number of origins per dispatcher, then clean up when that reaches 0 in order to avoid the memory leak. 
You may not notice this memory leak if you don't fetch from many different origins.
N/A
- Related to https://github.com/nodejs/undici/issues/3895
N/A

fix: agent memory leak

---

docs/examples/README.md

docs: correct example in FormData request

---

docs/docs/api/Debug.md
lib/core/diagnostics.js

When fixing an issue in a unrelated third-party package that was incorrectly adding an extra forward slash. The node debug logs still contained an extra forward slash which lead me to believe the issue had not been patched in the unrelated third-party package. 
When enabling the fetch debug logs, the request contains two forward slashes.

fix(debug): remove extra forward slash in logs

---

types/eventsource.d.ts

When you initialize an EventSource Instance, then onmessage, onerror and onopen are null by default.

types: EventSource short handlers can be null

---

lib/cache/sqlite-cache-store.js
test/client.js
test/fetch/fire-and-forget.js
test/fetch/max-listeners.js
test/interceptors/cache-fastimers-fix.js

we already use everywhere `node:` prefix, these places should do it too.

chore: require node native modules  with `node:`-prefix

---

lib/web/eventsource/eventsource.js
lib/web/eventsource/util.js
test/eventsource/eventsource-connect.js
test/node-platform-objects.js

To be honest: I am pretty much confused, why we had this regression. In #2665 the setTimeout got replaced with the non promise one, and thus broke the reconnection logic. It seems like setTimeout from timers/promise without reference, still keeps the process running, but the unref`d normal setTimeout results in letting the process die, even though we are still in reconning state.
Also I dont understand anymore why I wrote the close logic into `processEventSourceEndOfBody`.  
So take this PR with a grain of salt.

fix: eventsource does not reconnect on network error

---

README.md

#4066
Added section in documentation to highlight undici vs fetch differences and usecases

doc: undici vs fetch 

---

benchmarks/_util/index.js
benchmarks/_util/runner.js
benchmarks/package.json
benchmarks/websocket-benchmark.mjs
benchmarks/websocket-echo-server.mjs
benchmarks/websocket/generate-mask.mjs
lib/web/websocket/frame.js

bench: add websockets

---

docs/docs/api/RetryAgent.md

Code example over [here](https://undici.nodejs.org/#/docs/api/RetryAgent?id=new-retryagentdispatcher-options) is currently incorrect:
Function `agent.request()` does not take `string` but `Dispatcher.RequestOptions`
I've updated the code example with expected `Dispatcher.RequestOptions` props.

fix: Use correct `Dispatcher.RequestOptions`

---

docs/docs/api/MockClient.md
docs/docs/api/MockPool.md
lib/mock/mock-client.js
lib/mock/mock-pool.js
test/mock-client.js
test/mock-pool.js
test/types/mock-client.test-d.ts
test/types/mock-pool.test-d.ts
types/mock-client.d.ts
types/mock-interceptor.d.ts
types/mock-pool.d.ts

closes: https://github.com/nodejs/undici/issues/3737
Add `cleanMocks` method to `Interceptable` interface and implement it in `MockPool ` and `MockClient`.
Add tests, typings, docs.
add `cleanMocks` method 

Add `cleanMocks` to `MockClient` and `MockPool`

---

test/wpt/status/eventsource.status.json
test/wpt/status/websockets.status.json

A few of the freshly landed wpts are now failing. I'm skipping them

Skip failing wpts

---

docs/docs/api/DiagnosticsChannel.md
lib/core/diagnostics.js
lib/core/request.js
test/node-test/diagnostics-channel/get.js
test/node-test/diagnostics-channel/post-stream.js
test/node-test/diagnostics-channel/post.js
test/types/diagnostics-channel.test-d.ts
types/diagnostics-channel.d.ts

Fixes https://github.com/nodejs/undici/issues/4166
Add diagnostics channel `undici:request:bodyChunkSent` and `undici:request:bodyChunkReceived`.

feat: add request body diagnostic channels

---

types/env-http-proxy-agent.d.ts

`EnvHttpProxyAgent.Options` extends from `Agent.Options`, so it's not possible to pass `ProxyAgent.Options` such as `requestTls` to the `EnvHttpProxyAgent` constructor.
`EnvHttpProxyAgent.Options` extends `Omit<ProxyAgent.Options, 'uri'>`.
`uri` is omitted, because it's provided by `EnvHttpProxyAgent`.
N/A
It's not possible to pass `requestTls` (and others) to the `EnvHttpProxyAgent` constructor.
- [s] Tested
- [s] Benchmarked (**optional**)
- [s] Documented

fix: EnvHttpProxyAgent.Options should accept ProxyAgent.Options

---

lib/web/fetch/body.js
lib/web/fetch/index.js
lib/web/fetch/util.js

the function `fullyReadBody` is sync, so the await is unnecessary.

fetch: remove await, add jsdoc for some body read functions

---

docs/docs/api/Dispatcher.md

People not knowing well the HTTP cache semantic may misleadingly believe that `private` is a safer choice than `shared`. Add a bit of guidance about the effect of private.
The `type` option of the cache interceptor, so, HTTP caching of fetches done by Undici.
The `private` `type` option of the cache interceptor causes the Undici HTTP cache to act as a private cache while in most circumstances a Node.js application will be shared between many users. This can lead to private data leakage. Furthermore people not understanding well the HTTP cache semantic may misleadingly think choosing `private` instead of `shared` is safer.
Add some guidance about the `private` choice.
N/A
N/A
None
[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md#developers- …

Clarify the type option of the cache interceptor

---

lib/web/websocket/stream/websocketstream.js
package.json
test/websocket/stream/readable-closed-after-close.js
test/wpt/status/websockets.status.json

https://github.com/ricea/websocketstream-explainer/issues/25
In the test added, `reader.closed` would hang forever because readablestream.cancel() would always throw due to the stream being locked from the getReader().

websocketstream: close readablestream properly

---

lib/web/websocket/websocket.js
test/websocket/ping-util.js

fix sending ping with no payload

---

lib/web/fetch/index.js
lib/web/fetch/util.js

fetch: minor modifications

---

lib/mock/mock-agent.js
test/jest/mock-agent.test.js

fix #4342
MockAgent.prototype.get now respect the `ignoreTrailingSlash` option.

MockAgent.prototype.get support ignoreTrailingSlash option

---

lib/api/readable.js

chore: more jsdoc and minor improvements for lib/api/readable.js,

---

docs/docs/api/ProxyAgent.md
lib/dispatcher/proxy-agent.js
test/proxy-agent.js

This refactors the way the legacy unsecured behaviour is implemented, by wrapping the Proxy client in a wrapper which rewrites requests, and handles errors. This will also insert authentication headers in each request.
CURRENTLY:
For nonsecure channels, clients allocated by the pool all delegate to the proxy client, and reuse the same HttpContext. This is probably not a good thing, but at least in cases where only one request is performed at a time, it seems harmless enough. In order to make this ready to land, this probably needs to handle simultaneous concurrent requests and have a test for that.

feat(ProxyAgent) improve Curl-y behavior in HTTP->HTTP Proxy connections (#4180)

---

README.md

For the curious mind, this was implemented in https://github.com/nodejs/undici/pull/3199.

Amend the GC warning in the README to clarify that consuming bodies is recommended but not required

---

docs/docs/api/DiagnosticsChannel.md
lib/web/websocket/websocket.js
test/websocket/diagnostics-channel-handshake-response.js

- Add handshakeResponse object to undici:websocket:open diagnostic event
- Include status, statusText, and headers from HTTP handshake response
- Enables Chrome DevTools Protocol Network.webSocketHandshakeResponseReceived support
- Add comprehensive test coverage for handshake response diagnostic data
Fixes #4394

feat(websocket): add handshake response info to undici:websocket:open diagnostic event

---

package.json
scripts/generate-pem.js
test/connect-pre-shared-session.js
test/fetch/cookies.js
test/fetch/http2.js
test/h2c-client.js
test/http2.js
test/https.js
test/interceptors/dns.js
test/node-test/ca-fingerprint.js
test/node-test/client-dispatch.js
test/node-test/client-errors.js
test/node-test/diagnostics-channel/get-h2.js
test/node-test/unix.js

Closes #4156 
- **test: fix key-size pem errors**
- **chore: use @metcoder95/https-pem**

fix: h2 CI

---

lib/web/eventsource/eventsource.js
test/eventsource/eventsource-connect.js
test/eventsource/eventsource-custom-dispatcher.js
types/eventsource.d.ts

Tests can be implemented if #4247  is merged

feat: EventSource can be configured with reconnectionTime

---

lib/mock/snapshot-agent.js
test/snapshot-testing.js

@mcollina 
Was there a reason to make _replaySnapshot async? Because it was asyncy it resulted in the flaky behaviour. Basically returning the snapshot was async so it was not ensured which response Body needed to be returned.

test: fix snapshot testing flaky test

---

lib/web/fetch/formdata.js
test/fetch/formdata.js

The [FormData](https://xhr.spec.whatwg.org/#dom-formdata) constructor's arguments are all marked as optional in the specification, so let's make them optional.

fix formdata constructor args mark optional

---

lib/dispatcher/proxy-agent.js
lib/web/cache/cache.js
lib/web/fetch/response.js
lib/web/websocket/stream/websocketstream.js
lib/web/websocket/websocket.js

Just some negligible improvements which i did while i played with [dependency-cruiser](https://www.npmjs.com/package/dependency-cruiser)

chore: improve imports and requires

---

lib/mock/snapshot-agent.js
lib/mock/snapshot-recorder.js
lib/mock/snapshot-utils.js
test/snapshot-recorder.js
test/snapshot-testing.js

I used jsdoc to make a static code analysis. I found some redundant calculations etc.. "Simplified" it.
@mcollina

refactor: snapshot-recorder

---

docs/docs/api/ProxyAgent.md
lib/dispatcher/proxy-agent.js
test/proxy-agent.js
types/proxy-agent.d.ts

Backports #4180  - Relates to #4430

feat(ProxyAgent): match Curl behavior in HTTP->HTTP Proxy connections (#4180)

---

build/wasm.js
docs/examples/snapshot-testing.js
lib/dispatcher/client-h1.js

We can savely remove exception in the `catch (e)` head if we dont process it.

chore: remove unused exceptions in try catch blocks

---

lib/web/cookies/parse.js
lib/web/fetch/body.js

chore: avoid overriding global escape and unescape

---

docs/docs/api/ProxyAgent.md
lib/dispatcher/proxy-agent.js
test/proxy-agent.js

feat(ProxyAgent) improve Curl-y behavior in HTTP->HTTP Proxy connections (#4180) (#4340)

---

.github/workflows/release.yml

Ref https://github.com/nodejs/admin/issues/998

Drop npm token, use OIDC instead

---

lib/dispatcher/client.js

Reduces the amount of promises for a simple fetch by 3.

perf: make `client.connect()` sync

---

index-fetch.js
index.js
test/fetch/client-error-stack-trace.js

This PR avoids one additional promise in success cases in the exported fetch wrapper.

fetch: remove promise in exported fetch

---

lib/dispatcher/client-h2.js
test/http2.js

fix(#4451): implement http2 cookie support

---

test/cache-interceptor/cache-store-test-utils.js
test/cache-interceptor/sqlite-cache-store-tests.js

With this change, some skipped sqlite checks wont be swallowed by the test engine. 

test: cache store tests should properly be skipped

---

test/fetch/issue-2171.js

test: remove skip check for AbortSignal.timeout, as it exists since node18

---

test/client-post.js
test/fetch/http2.js
test/http2.js
test/util.js

basically a follow up of #4362 by @KhafraDev 

test: remove skip checks for existance of global available Blob and File

---

lib/mock/mock-utils.js

I dont think that #4472 will be accepted, but anyhow: we dont usually dont use instanceof in our lib folder for errors

fix: avoid instanceof MockNotMatchedError

---

lib/dispatcher/h2c-client.js
lib/dispatcher/pool.js
lib/dispatcher/proxy-agent.js

We should call super as the "last" step.

chore: call super() after type checks

---

test/interceptors/cache-revalidate-stale.js

This fixes the flakyness of test/interceptors/cache-fastimers-fix.js and renames the filename to a more descriptive name cache-revalidate-statel.js. Also "fastimers" is a clear typo.
The flakyness was due to the fact, that the http-server by nodejs is sending the date header, which is not overridable by modifying the global Date and/or Timer Logic. I guess node core also caches the date and refreshes it every second and not on every http request?! That resulted in the flakyness, we saw.
I basically deactivated sending the date header via the http server and send my own mocked date header t. Thus making it fully deterministic.

fix: deflake cache-fastimers-fix.js

---

lib/web/fetch/util.js
test/fetch/util.js

127.0.0.0 is in the CIDR range
simplified the regexes

fix: improve validation of IP addresses as trustworthy, correct ipv4 check

---

test/eventsource/eventsource-attributes.js
test/eventsource/eventsource-close.js
test/eventsource/eventsource-connect.js
test/eventsource/eventsource-constructor-stringify.js
test/eventsource/eventsource-constructor.js
test/eventsource/eventsource-message.js
test/eventsource/eventsource-reconnect.js
test/eventsource/eventsource-redirecting.js
test/eventsource/eventsource-request-status-error.js

- use tspl with plan instead of a custom deferredPromise logic
- use FakeTimers instead of waiting
- condense the logic
Reduces the time to test from about 11 seconds to round about 1s. 

test (eventsource): refactor tests for eventsource, speed them up

---

lib/dispatcher/client-h1.js

If we just rethrow then we can remove the catch anyway. sonarjs shows useless-catch error

fix: remove useless catch in client-h1.js

---

test/fetch/encoding.js

Lets skip this god forsaken test 

test: skip flaky encoding test on macos and node20

---

test/websocket/issue-2679.js

The test takes excessively long. i tested against the codebase, which had the bug we test against, and it will still take cover that bug. 
npm run test:websocket will because of this change run on my machine in 1.2 sec instead of 3.8 sec.

test (websocket): speed up test/websocket/issue-2679.js

---

lib/web/webidl/index.js
test/webidl/converters.js
types/webidl.d.ts

Aims to provide support for a resolution for #4495.
Factors contributing to the specification divergence for fetch/websockets as detailed in the linked issue are:
- the required buffer source converters are missing;
- the existing buffer source converters are not used within the codebase;
- those that do exist are out-of-date with the IDL standard.
Changes to existing converters:
- `ArrayBuffer` used to convert to either `ArrayBuffer` or `ArrayBuffer | SharedArrayBuffer`, depending on the presence or absence of the `[AllowShared]` attribute. Subsequent changes to the standard have separated these out into separate IDL types, and so this converter has been split into two.
- The `ArrayBuffer` and `SharedArrayBuffer` converters correctly handle the presence or absence of the …

webidl: fix existing and add missing buffer source converters

---

test/fetch/encoding.js

test: another try to fix flaky macos and node 20

---

lib/core/request.js
lib/core/util.js
lib/dispatcher/client-h2.js
lib/dispatcher/client.js
test/h2c-client.js
test/http2.js

Adjust the pseudo header `:scheme` in accordance to the actual protocol used (support for h2c client).

fix(h2): adjust :scheme on h2 requests

---

lib/web/fetch/response.js
lib/web/webidl/index.js
lib/web/websocket/stream/websocketstream.js
lib/web/websocket/websocket.js
test/fetch/request.js
test/web-platform-tests/expectation.json
test/webidl/converters.js
test/webidl/util.js
types/webidl.d.ts

change webidl attribute to bitwise flag

---

.github/workflows/ci.yml
.github/workflows/nodejs.yml
package.json

ci: fine grained test nodejs workflow

---

test/web-platform-tests/wpt-runner.mjs

@KhafraDev 
Wanted to setup the wpt runner locally. didnt work properly. ofc you need sudo right to write /etc/hosts. So instead of failling with a EACCESS error, now you get clear instructions what to do. 

wpt: properly handle write permissions errors in wpt-runner setup

---

.github/workflows/nodejs.yml

@metcoder95 
h2 tests are just a subset of test:unit, so it is redundant

ci: remove h2

---

README.md

Add a comprehensive example showing how to use the Cache Interceptor with Fetch, including configuration options and usage patterns.
Refs: #4283

docs: add Cache Interceptor example to README

---

lib/dispatcher/dispatcher-base.js
types/dispatcher.d.ts

close and destroy is now more similar. also the ClientDestroyedError is instantiated in the close function and not in the queueMicrotask to ensure that you have some meaningful stack.
regarding typings:
actually functions need to be sorted by descending arity.
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering

fix: minor changes in dispatcher-base.js and types for Dispatcher

---

test/interceptors/dns.js

there were two typos. instead of t.completed it was t.complete

fix: dns-interceptor test should await plan to complete

---

test/eventsource/eventsource-attributes.js
test/eventsource/eventsource-close.js
test/eventsource/eventsource-connect.js
test/eventsource/eventsource-constructor-stringify.js
test/eventsource/eventsource-constructor.js
test/eventsource/eventsource-custom-dispatcher.js
test/eventsource/eventsource-message.js
test/eventsource/eventsource-properties.js
test/eventsource/eventsource-reconnect.js
test/eventsource/eventsource-redirecting.js
test/eventsource/eventsource-request-status-error.js
test/eventsource/eventsource-stream-bom.js
test/eventsource/eventsource-stream-parse-line.js
test/eventsource/eventsource-stream-process-event.js
test/eventsource/eventsource-stream.js
test/eventsource/eventsource.js
test/eventsource/util.js

chore: remove tspl from eventsource

---

lib/dispatcher/balanced-pool.js
test/node-test/balanced-pool.js
test/types/balanced-pool.test-d.ts
types/balanced-pool.d.ts

- Add getUpstream(upstream) method to BalancedPool class that returns the Pool instance for a given upstream URL
- Enable users to retrieve specific Pool instances for debugging, monitoring, or direct Pool operations
- Comprehensive test coverage following TDD approach with TypeScript definitions
- **lib/dispatcher/balanced-pool.js**: Implement getUpstream() method that finds and returns Pool for upstream
- **test/node-test/balanced-pool.js**: Add comprehensive test suite covering valid/invalid upstreams and error cases  
- **types/balanced-pool.d.ts**: Add TypeScript method definition with proper typing
- **test/types/balanced-pool.test-d.ts**: Add TypeScript tests to verify type definitions
- ✅ Returns correct Pool instance for valid upstream URLs
- ✅ Handles non-existent upstreams …

feat: add getUpstream() method to BalancedPool

---

lib/web/fetch/request.js
test/web-platform-tests/expectation.json

fetch: handle invalid priority values properly

---

docs/docs/api/Dispatcher.md
lib/interceptor/dns.js
package.json
test/interceptors/dns.js
test/types/dns-interceptor.test-d.ts
types/interceptors.d.ts

Alternative implementation for https://github.com/nodejs/undici/pull/4565
Custom `cache` for DNS interceptor allows:
- add custom metrics for DNS cache hit rate monitoring
- use any cache library (`lru-cache`, etc.)
Reference - https://github.com/szmarczak/cacheable-lookup?tab=readme-ov-file#cache
Added `cache` parameter for `DNSInstance`

Feat dns interceptor storage

---

docs/docs/best-practices/crawling.md
docs/docsify/sidebar.md
test/fetch/user-agent.js

In the fallout of issue #4588 I was in the FSF IRC channel and discussed the issue and we discussed about potential solutions. cURL`s user agent is also blocked by many servers. The reason is, that bad implemented crawlers can be identified by it. 
I offered, that we can add a page in to the documentation regarding crawling and that we recommend to change the user agent to some random value, but that would not solve potential bots which ignore robots.txt.
It was further discussed, that doing a curl request against 'bgp.tools' `curl https://bgp.tools` results in following response:
```sh
Requests from default user agents are not allowed, please set a descriptive user-agent. For example: 'acmeco bgp.tools - contact@acme.co', This is so that if your program gets out of control I can contact …
```

docs: add crawling best practices
