- lib/client.js
- lib/pool.js
- package.json
- test/pool.js
Turns out that the algorithm that I wrote for client selection was
highly inefficient, because it constantly made clients to create
new connections. This new algorithm uses a LIFO queue to select
the latest client that drained, and keep using it until it is full.
> Improved backpressure algorithm

- lib/client.js
- test/client.js
In case of HEAD method `client.parser.[HTTPParser.kOnHeadersComplete]`
should tell the parser to skip the body by returning 2.
See https://github.com/creationix/http-parser-js/blob/master/http-parser.js#L357
I ran tests multiple times and on my machine the `lib/pool.js` tests failed once in the git precommit hook. 
I'll look into adding tests also.
> fix(client): skip body if method is `head`

- lib/client.js
- test/client-errors.js
The client constructor only expects, protocol, host and port.
Anything else will be ignored. Throw in order to inform user
of incorrect usage, e.g. a user might assume that the path
is always prepended to all requests.
> fix: validate URL

- lib/client.js
Not sure what you prefer, but resetParser doesn't need to live on the object and take up an unnecessary property.
> refactor: extract reset parser

- lib/client.js
- test/client-errors.js
Readable can emit 'end' after .destroy() as well
as legacy streams might not implement the whole
Readable contract properly. Try to handle these
edge cases better.
Fixes: https://github.com/mcollina/undici/issues/66
> fix: request body edge cases

- lib/client.js
- test/client-errors.js
The parser is dependent on the socket and not the client. This
refactors the connection to properly encapsulate state to the
connection and not to the client.
Avoid having to check for !client.socket etc...
> refactor: encapsulate parser to connection

- lib/client.js
- lib/request.js
- test/client-errors.js
- test/client.js
Fixes: https://github.com/mcollina/undici/issues/52
> fix: pause while piping

- lib/client.js
finished will be invoked on 'end' while destroy(err) will be delayed.
This can break the assertion in theory on edge cases.
> fix: broken assertion

- lib/pool.js
- test/pool.js
This does differ a bit from the previous implementation as it does not take `'drain'` into account. I will probably have to change it but wanted to see whether this makes sense.
Basically this will always priotize the first connection in the list assuming that's the one least likely to timeout and the one that is fully saturated.
I hope this will also sort out the flakiness.
Also prioritizes clients which are connected.
> fix: pool should be depth first connected

- README.md
- lib/client.js
- lib/symbols.js
- test/client-stream.js
By providing a `resume` property on the callback response and making `body` a lazy factory getter; it's possible to avoid the intermediate `Readable`. This would speed up e.g. creating a proxy using undici.
e.g.
Pre this PS
```js
function proxy (req, res) {
client.request(fromReq(req), ({ statusCode, headers, body }) => {
res.writeHead(statusCode, headers)
// Body is an intermediate Readable
body
.on('error', (err) => res.destroy(err))
.pipe(res)
})
}
```
With this PR:
```js
function proxy (req, res) {
client.request(fromReq(req), ({ statusCode, headers, resume }) => {
res.writeHead(statusCode, headers)
return pipe(res, resume)
})
}
function pipe(dst, resume) {
dst.on('drain', resume)
return (err, chunk) => {
if (err) {
dst.destroy(err)
} else if (chunk == null) {
dst.end()
} else { …
```
> feat: request.consume

- lib/pool.js
Noticed while testing that Pool would open lots of connections in the edge case where no client is connected.
If there is no connected client, pick the first one that is not full, instead of a random one.
> fix: pool should avoid opening connections

- README.md
- lib/client.js
- lib/request.js
- test/client-stream.js
This improves the `client.stream` API at the cost of a slightly (negligible?) slower request dispatch.
```js
await client.stream({
path: '/',
method: 'GET'
}, ({ statusCode, headers }) => {
console.log('response received', statusCode)
console.log('headers', headers)
return fs.createWriteStream('destination.raw')
})
```
> refactor: improve client.stream API

- lib/request.js
- test/client-stream.js
Fixes: https://github.com/mcollina/undici/issues/130
Fixes: https://github.com/mcollina/undici/issues/128
> fix: request.stream don't wait for 'end'

- lib/client.js
- test/https.js
Please note `fix: remove https option`. I see future problems with having two names for the same option when useland modules start forwarding options upstream to undici and all of a sudden they have overlap of tls and https and unexpectedly lose options. Removes this ambiguity by just having one of the options.
> Some more cleanup

- lib/client.js
- test/client-stream.js
Don't destroy readable side and closer mimic pipeline behavior.
> fix: only destroy if err

- README.md
- benchmarks/index.js
- lib/client.js
- lib/pool.js
- test/client-pipeline.js
Fixes: https://github.com/mcollina/undici/issues/106
```js
stream.pipeline(
fs.createReadStream('source.raw'),
client.pipeline({
path: '/',
method: 'PUT',
}, ({ statusCode }) => {
if (statusCode !== 201) {
throw new Error('invalid response')
}
}),
fs.createReadStream('response.raw'),
(err) => {
if (err) {
console.error('failed')
} else {
console.log('succeeded')
}
}
)
```
> feat: stream.pipeline

- README.md
- benchmarks/index.js
- lib/client.js
- lib/request.js
- lib/symbols.js
The old implementation was a bit ugly. This extracts the API specific parts to the `request`, `stream` and `pipeline` methods and keeps the "core" clean.
Fixes broken .pipeline benchmark.
Slightly improves .pipeline perf by replacing `PassThrough` with `Readable` for `res`. Also opens up for further future optimizations to replace `ret` and `req` with `Readable`.
> unify impl

- README.md
- lib/client.js
- lib/symbols.js
- Make req Readable instead of PassThrough.
- Bypass Duplex writable buffering.
Brings stream.pipeline to parity with stream.requests.
> perf: optimize stream.pipeline

- README.md
- lib/client.js
- test/client-pipelining.js
- test/client.js
- test/close-and-destroy.js
I'm not 100% `'drain'` is implemented correctly. Since I find its usefulness limited and it allows us to skip a `nextTick` I would prefer removing it.
> fix: remove drain

- lib/client.js
- test/client-errors.js
The current port validation will fail if you use the default http/https port or not use a port at all, for example:
```js
undici('http://localhost')
undici('http://localhost:80')
undici('https://localhost')
undici('https://localhost:443')
```
All the examples above will throw an exception, even if the URL is valid.
Given that internally we are using the `URL` constructor, I think we should leave to it the bad port validation, for example, the following will cause an exception:
```js
undici('http://localhost:foobar')
```
> fix: URL default port validation

- README.md
- lib/client.js
- test/client-abort.js
- test/client-errors.js
- test/client-pipeline.js
- test/client-reconnect.js
- test/client-stream.js
Rename reconnect to disconnect. We won't actually reconnect
unless there are pending requests. Hence, reconnect is not
strictly true.
Also forward the error which caused the socket to close in
order to provide some form of hint to the user.
> fix: disconnect event w err

- lib/client.js
- test/http-100.js
Even if we don't support 1xx response we shoudl still
not corrupt the client state if the server sends one.
> fix: 100 response should not corrupt client state

- lib/client-base.js
- lib/request.js
- test/client-pipeline.js
- Early abort of body could cause unhandled exception.
- Abort could deadlock close.
> fix: avoid unhandled exception on early abort

- lib/client-base.js
- lib/client.js
- test/async_hooks.js
Ensure destroy is always in async scope.
Note, depends on and includes https://github.com/mcollina/undici/pull/213
> fix: pipeline destroy async scope

- README.md
@ronag 
1. The description for the url parameter was misleading.
1. The description for the pipeline handler return value was wrong.
1. There was a mistake in the pipeline example.
> fix: README docs

- lib/client.js
- test/client-pipeline.js
Some legacy streams don't have a .pause() method.
> fix: pipeline legacy stream

- lib/client-base.js
- test/client.js
If the socket fails while there is no active request then it might not be recoverable and we should error and destroy.
> fix: only retry recoverable socket errors

- README.md
- lib/client-base.js
- lib/symbols.js
- package.json
- test/client-errors.js
Using llhttp through node binding. llhttp is more maintained, secure and "correct" than http-parser-js.
@dnlup: Thanks for the hints!
> fix: use node native parser

- lib/client-base.js
- test/unix.js
This is the least controversial solution I could come up with. Basically just do it like Node and curl already does.
For the host header it uses the passed hostname in the url. curl does the same.
> feat: add support for unix socket

- lib/client-base.js
- lib/request.js
- test/client-pipeline.js
- test/client.js
Fixes: https://github.com/mcollina/undici/issues/248
> fix: pipeline with `end()` in same tick should not use chunked encoding

- lib/client-base.js
- lib/request.js
- test/client-pipeline.js
- test/get-head-body.js
Fixes: https://github.com/mcollina/undici/issues/246
> fix: reset socket on GET & HEAD with body

- lib/client-base.js
- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- lib/client.js
- test/client.js
This refactors the implementation a bit by moving logic out from `Request` and into the specific API implementations. This will allow future improvements to the API and extend it to support trailers, informational headers, upgrades and connect.
It does introduce some code duplication that did not exist before but I think it's worth it.
An API (`client.request`, `client.pipeline`, `client.stream`) is now expected to extend `Request` and implement the following methods:
```js
class MyApi extends Request {
onHeaders(statusCode, headers, resume),
onBody(chunk, offset, length),
onComplete(trailers),
onError(err)
}
```
Plan to add `onUpgrade` for websocket upgrades and `CONNECT` later, e.g. for `client.upgrade` and `client.connect` or something...
> refactor: split impl into apis

- README.md
- benchmarks/index.js
- lib/pool.js
- lib/symbols.js
Adds some more variations to benchmark to explore what the theoretical maximum performance is.
```js
http - keepalive x 5,291 ops/sec ±5.37% (71 runs sampled)
undici - pipeline x 9,330 ops/sec ±2.53% (81 runs sampled)
undici - request x 11,724 ops/sec ±1.36% (83 runs sampled)
undici - stream x 11,988 ops/sec ±2.29% (80 runs sampled)
undici - simple x 13,391 ops/sec ±1.05% (81 runs sampled)
undici - noop x 19,939 ops/sec ±3.01% (65 runs sampled)
```
In particular it's interesting that `simple` is so much faster than `stream`. Might be interesting to explore where that overhead occurs.
`noop` is intersting to detect regression in dispatching and parsing of requests.
> bench: add more variations

- .github/workflows/bench.yml
- package.json
Add benchmarks jobs in CI workflow. It was taken from https://github.com/mcollina/undici/issues/256#issuecomment-657255734 .
Did you have some customization in mind specific for `undici`?
TODO:
Fix #256
> ci: add benchmarks jobs

- lib/util.js
- test/stream-compat.js
In one of the previous changes we did lost compatibility with `IncomingMessage`, which is a feature needed to avoid parsing the bodies of requests in proxies.
I think this is the simplest fix. I know it is using `IncomingMessage` directly, but I think it's pretty safe.
We might need a similar fix for http2 compat.
> Compatibility with IncomingMessage

- lib/request.js
- test/client.js
- test/http-100.js
- test/invalid-headers.js
As titled. Without this patch we had a double `connection` header which was confusing some server.
> Throw if connection header is specified

- lib/client.js
- lib/request.js
- test/invalid-headers.js
Provide a hint for the server to keep connection alive until it is
considered no longer re-usable by client. This reduces the risk of
a race where the client sends a request and the server closes it
before receiving it.
I don't think Node core uses this... but I guess it still could be useful.
> fix: throw on keep-alive header

- lib/client-stream.js
- test/client-stream.js
- test/pool.js
keep it simple, if you don't care about the response, abort it. This aligns it with what the docs says.
> fix: stream must return Writeable

- README.md
- benchmarks/index.js
- lib/client-connect.js
- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- lib/client-upgrade.js
- lib/client.js
- lib/pool.js
- lib/request.js
Makes our internal API public. This is the API which our public API is implemented on top.
There is need for some internal cleanup and refactor post this PR. I've tried to keep the changes as small as possible for easy of review.
I am not 100% satisfied with the API. However, I believe it does fullfil functional and performance requirements. Would appreciate some feedback and maybe ideas. I suspect this API might evolve/improve over time and be less stable than the other ones.
Some problems that might or might not need to be resolved:
- ~~There is now two `AsyncResource`s, the `handler` object and `Request` object. Depending on whether the implementation needs to asynchronously propagate async scope.~~
- ~~It's a bit weird that `_onConnect` takes a `resume` function.~~
- ~~Not sure about …
> feat: dispatch

- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- test/async_hooks.js
Don't propagate async scope across events.
Pending recommendation/consensus in https://github.com/nodejs/node/issues/34430
Refs: https://github.com/nodejs/node/issues/34430
Small perf boost:
```
undici - stream x 12,681 ops/sec ±1.95% (83 runs sampled)
```
vs
```
undici - stream x 12,226 ops/sec ±2.12% (80 runs sampled)
```
> don't propagate async scope across events

- lib/client.js
- lib/request.js
- lib/util.js
- package.json
- test/jest/test.js
> fix: buffer check for jest

- lib/client-connect.js
- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- lib/client-upgrade.js
- lib/client.js
- lib/pool.js
- test/client-pipelining.js
If all clients are busy then put requests in a queue and dispatch on first client that is no longer busy.
> perf: improved pool balancing

- README.md
- lib/client.js
- lib/request.js
- test/client-errors.js
- test/client.js
This reverts commit 911d724e1bd6b1872b83d9555daa70c07fb20362.
Not part of any release yet. This added some ambiguity in behavior as well as added unnecessary complexity. Something I would like to avoid as much as possible. This logic should probably live in higher level abstraction.
> Revert "fix: prepend client url pathname (#313)"

- README.md
- lib/client-connect.js
- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- lib/client-upgrade.js
- lib/client.js
- lib/request.js
- lib/util.js
- test/client-dispatch.js
https://github.com/mcollina/undici/pull/316 made me realize that we don't have an efficient way for library implementors to implement a different behavior than default.
This changes so that the dispatch methods receives raw headers.
> fix: dispatch receives raw headers

- README.md
- benchmarks/index.js
- lib/client-connect.js
- lib/client-pipeline.js
- lib/client-request.js
- lib/client-stream.js
- lib/client-upgrade.js
- lib/client.js
- lib/request.js
- test/client-dispatch.js
- test/pool.js
- test/request-timeout.js
When no resume is going to be scheduled, request.onError might never be detected or in the case of `Client.pipeline` the stream destroy.
See test case in first commit, https://github.com/mcollina/undici/pull/345/commits/adb4faee1f7a1dc545ea2373f39d49f30c4455e9.
Fixes: https://github.com/mcollina/undici/issues/344
----
There is a problem with the existing API where if a running request is aborted while the server is not providing any data nothing is ticking the state machine.
There are some API changes:
- A new hook is added on dispatch handler, `onConnect(abort)`. 
- `onData` now only returns a boolean (no magical `null`).
> fix: close() deadlock

- lib/client-connect.js
- lib/client-request.js
- lib/client-stream.js
- lib/client-upgrade.js
- lib/core/client.js
- lib/core/request.js
This is a first part of a refactoring aimed at resolving #350 & #356. The idea is to try and simplify `Request` as much as possible and move logic over to handlers.
> refactor: simplify request

- README.md
- lib/core/client.js
- lib/core/request.js
- test/client-pipelining.js
- test/pipeline-pipelining.js
This significantly simplifies the `busy` logic. Slightly changes behavior of `busy`. However, since we now have `'drain'` it has minor impact.
Actually seems to improve performance slightly.
The difference is mostly for the `Client.pipeline` API.
> refactor: simplify busy

- lib/core/client.js
- lib/core/request.js
With a few more changes `Request` would no longer need to live in core.
> refactor: reduce Request dependency on client

- README.md
- lib/core/client.js
- lib/core/request.js
- lib/core/symbols.js
- test/client-errors.js
- test/request-timeout.js
- test/socket-timeout.js
Fully decouples `Request` from `Client` at the cost of losing the global `requestTimeout` option.
A little bit hard to motivate but still something I would personally like to do. Eventually maybe even move `requestTimeout` out from core and into handlers.
> refactor: remove Client requestTimeout option

- README.md
- benchmarks/index.js
- benchmarks/server.js
EDIT: Weird results resolved. Linux network stack tuning.
Trying to add some pipelining to benchmarks. However, I'm getting weird results when running on a server vs local computer.
OSX MacBook/Node 14
```
http - keepalive x 386 ops/sec ±3.51% (265 runs sampled)
undici - pipeline x 573 ops/sec ±5.17% (260 runs sampled)
undici - request x 877 ops/sec ±5.51% (272 runs sampled)
undici - stream x 1,197 ops/sec ±1.66% (262 runs sampled)
undici - dispatch x 1,351 ops/sec ±2.66% (257 runs sampled)
undici - noop x 2,754 ops/sec ±3.66% (273 runs sampled)
```
Linux Supermicro/Docker/Node 14
```
http - keepalive x 685 ops/sec ±3.13% (271 runs sampled)
undici - pipeline x 374 ops/sec ±5.39% (228 runs sampled)
undici - request x 415 ops/sec ±3.54% (228 runs sampled)
undici - stream x 471 ops/sec …
```
> bench: w pipelining & unix sockets

- lib/core/client.js
- test/client-errors.js
- test/client-reconnect.js
Don't error requests in client `onSocketError` on these codes:
* `UND_ERR_INFO`
* `UND_ERR_SOCKET`
Modify `client-reconnect.js` test. Add socket error test.
> test: add socket error and remove reconnect from client

- lib/core/client.js
- test/client-errors.js
- test/socket-back-pressure.js
Fixes: https://github.com/nodejs/undici/issues/434
> fix: socket back pressure memory leak

- lib/core/request.js
- test/client-dispatch.js
- test/invalid-headers.js
If a header is set to null it is casted to the string 'null'.
This is the same behavior we have in Node's HTTP client if I am not mistaken.
Note: I am not sure this is a fix, though. I can amend the commit :wink: 
Fix #416
> fix(core/request): handle header set to null

- .github/workflows/nodejs.yml
I'm attempting to use `undici` in a library that supports entire semver major ranges of Node.js. I found that on Windows with Node 12.0.0 there was an abort when used with my library's test suite.
This is an attempt to establish an explicit baseline version range to support.
**EDIT:** I tested locally and the minimum versions included now are the minimum ones that would pass on my machine.
> test: support earliest versions in range in CI

- benchmarks/index.js
The use of `close` event was causing timeouts. Switching to the `finish` event fixed it.
Fixes #456
> fix(benchmarks): fix timeout errors

- .github/workflows/nodejs.yml
- lib/core/client.js
Unfortunately the private API of the HTTP parser changed in 12.19.0. It would crash without this fix.
> Fix for node 12.19

- lib/core/client.js
- lib/core/symbols.js
Avoid using socket timeout. We don't need to refresh the timer on every chunk.
> fix: simpler and faster idle timeout

- benchmarks/index.js
- benchmarks/server.js
Very minor change to make it portable for *nix benchmarking.
Noticed the benchmark fails in windows but is unrelated to this PR (pre-existing).
> fix: Changing hardcoded `socketPath` to utilize `os.tmpdir()`

- lib/core/client.js
- test/client-idempotent-body.js
Fixes:https://github.com/nodejs/undici/issues/470
> fix: retry idempotent with original body

- .github/workflows/nodejs.yml
- README.md
- test/abort-controller.js
Noticed this very randomly ^^
We have native abortcontroller so it can be used.
Also - a few of the places used `AbortController` for signals incorrectly.
Cheers
> Update abort docs to native AbortController

- lib/client-stream.js
- lib/core/client.js
- lib/core/request.js
- test/client-stream.js
Fixes: https://github.com/nodejs/undici/issues/441
Refs: https://github.com/nodejs/node/pull/35348
Refs: https://github.com/nodejs/node/issues/35341
> fix: Client.stream writableNeedDrain

- types/client.d.ts
Closes #480 
Also adds some missing semicolons (probably should add a linter to ts definitions eventually)
> fix AbortController types

- .github/workflows/nodejs.yml
- README.md
- package.json
* setup codecov coverage report in CI workflow
* add coverage badge in README
Fixes #397 
There is no custom configuration setup using `codecov.yml` file, I don't see anything we could add ATM. The config reference:
https://docs.codecov.io/docs/codecov-yaml
> Coverage badge

- lib/core/client.js
- test/client-keep-alive.js
- test/client.js
idleTimeout was not cleared when socket is destroyed. Causing process to keep executing for 4s.
> fix: clear timeouts

- lib/core/client.js
- lib/core/util.js
Fails on certain endpoints. Not sure why and wasn't able to create a test. The endpoint I was able to reproduce with is unfortunately private.
> fix: fallback to url as servername

- README.md
- lib/core/client.js
- lib/core/request.js
- lib/core/symbols.js
- test/request-timeout.js
- test/socket-timeout.js
body and headers timeouts live in the parser and not on the request. Makes the implementation cleaner and simpler.
> fix: simplify timeouts

- index.d.ts
Trivial change I didn't catch until now. Just need to rename the import/export here so that the type resolution comes across the same as the JS api
> Fix capitalization of 'errors' in types

- README.md
Fixes two small grammar nits I found while reading through the documentation.
> Two small grammar nits

- README.md
- lib/pool.js
- test/pool.js
Make the `Pool` forward the `connect` and `disconnect` events emitted by its
clients. The `Client` instance that emitted the event is passed as
the argument.
Fixes #509
> feat(pool): forward connect and disconnect events

- .github/workflows/nodejs.yml
- package.json
See https://github.com/nodejs/citgm/pull/837
> Do not run .mjs in test. Add npm test to CI.

- .taprc
- test/gc.js
Add a test to check [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) support. 
I wasn't able to trigger the gc cycle any faster, I had to increase the default timeout of `tap`.
Fixes #501
> Test WeakRef support

- README.md
- lib/agent.js
- lib/core/symbols.js
- test/agent.js
Use `Pool`'s `connect`/`disconnect` events to add support of the `Agent` on Node 12 and lower.
Fixes #529 
Note:
I think it's better to wait for https://github.com/nodejs/undici/pull/521 to get merged before continuing. I have to touch many of the same blocks of that PR.
> agent: add support on Node 12 and lower

- lib/core/client.js
- test/client.js
busy should be true if pipeline is full. Should not have request unnecessarily queued.
> fix: busy if full

- README.md
- lib/agent.js
- lib/core/client.js
- lib/pool.js
- test/client.js
- test/content-length.js
- 'connect' and 'disconnect' event should have same arguments.
- connected should be an integer
> fix: unify Pool and Client APIs

- lib/core/request.js
- lib/core/util.js
- test/client-dispatch.js
- test/client-request.js
When e.g. returning a stream through resolve the user
needs to get a chance to register an 'error' handler
before the stream is destroyed. Otherwise we risk an
unhandled exception.
> fix: wait for queued handlers to run before onError

- lib/core/client.js
- test/client-upgrade.js
closes #554 
doc update included in #550
> fix missing client arg

- lib/agent.js
- test/agent.js
✅  Closes: #522 
* Add support for connect and disconnect events to Agent.
* Provide the necessary set of tests for this change.
* Increase the test coverage of Agent, by testing the `pool` instance returned from the Agent `get` method.
@ronag If any changes are required prior to merging these changes, I'll be more than glad to contribute.
> Feat: Agent connect/disconnect events

- test/types/agent.test-d.ts
- types/agent.d.ts
In `undici.request|stream|pipeline` helper functions, the opts param may not contain path.
see https://github.com/nodejs/undici#undicirequesturl-opts-promise
Without this fix you get the following Typescript error:
But if you pass the path parameter you get a runtime error: https://github.com/nodejs/undici/blob/master/lib/agent.js#L86-L88
> fix: omit 'path' in undici.request opts (ts)

- lib/node/http-parser.js
As Node.js prepares to deprecate `process.binding()`, we can still use `_http_common` to get the `HTTPParser`.
Ref: https://github.com/nodejs/node/pull/37485.
> Remove process.binding()

- docs/proxy.md
- lib/core/request.js
- package.json
- test/proxy.js
This pr adds a test and the documentation to show how to connect through a proxy :)
I had to remove the super complex regex as it was not validating all absolute urls (eg: `http://localhost:8080` didn't pass the check). I think that lazily checking the protocol is enough, as trying to save *all users* from themselves is impossible.
/cc @szmarczak
Closes #427
> Connecting through a proxy

- README.md
- docs/Client.md
- lib/core/client.js
- lib/core/symbols.js
- package.json
- test/no-strict-content-length.js
- types/client.d.ts
Closes #581
Adds ability to tread request content length mismatch as a warning instead of an error, via `strictContentLength` option.
> feat: treat request content length mismatch as warning

- docs/api/Agent.md
- docs/api/Errors.md
- docsify/sidebar.md
Hey folks, 
So i'm going to be away-from-keyboard this weekend, but I did not want to leave our docs without the Agent or Errors api. I've gone ahead and copy-pasted the old docs we had for these sections and added them to the docs folder. I also touched them up a little bit so links work and it renders nicely. I'm okay for "launching" our docs site with this content if that happens this weekend; otherwise, I'll follow up next week with documentation pages similar to `Client` and `Pool`.
🚀
> add old agent and errors docs

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE/template.md
Objectives 1 and 2 of #584 (I also checked Objective 6, so that may be crossed
off too).
N/A (justified by above).
- Added bug report issue template
- Added feature request issue template
- Added general PR template (the one used to make this PR)
N/A.
N/A.
N/A.
- [S] Tested
> chore: add pr and issue templates

- index.js
- lib/agent.js
- lib/api/abort-signal.js
- lib/api/api-connect.js
- lib/api/api-pipeline.js
- lib/api/api-request.js
- lib/api/api-stream.js
- lib/api/api-upgrade.js
- lib/api/index.js
- lib/client-pool.js
- lib/core/symbols.js
- test/agent.js
- test/pool.js
- Move `client-*` to api folder as `api-*`.
- Rename `pool` to `client-pool`.
- Move `api-` references to index root only.
> refactor: cleanup and restructure

- lib/core/request.js
- lib/core/util.js
- test/stream-compat.js
- test/util.js
Fixes #625 - Added a similar check that the Node.js project uses.
The check used in `undici` was the reverse of the problem in the Node.js project. The commit mentioned in #625 shows they were missing the check for `.on()` where `undici` was missing the checks for `pipe()` or `write()'.
In its current state the `util.isStream()` allows `Stream`, correctly returns false on `Buffer`, but does allow `EventEmitter` since it also has `.on()`.
I changed the `util.isStream()` method to match what the Node.js project uses.
In https://github.com/nodejs/undici/blob/main/lib/core/request.js#L39 I switched to using the newly exposed `util.isReadable()` since the error message there indicates that it should be a Readable stream. There are likely other places that should use the more specific …
> fix: add more strict check for streams in `util.isStream()'

- README.md
- docs/api/Agent.md
- docs/api/Client.md
- docs/api/Dispatcher.md
- docs/api/Pool.md
- index.js
- lib/agent.js
- lib/client.js
- lib/dispatcher.js
- lib/handler/redirect.js
- lib/pool.js
- test/agent.js
- test/client-upgrade.js
- test/client.js
- test/content-length.js
- test/pool.js
- test/redirect-request.js
- test/utils/esm-wrapper.mjs
- Unifies `Client`, `Pool` and `Agent` under a single interface.
- Removes `Agent.get` (in favor of extra args to client connect/disconnect).
- Removes `Client/Pool.busy` in favor of return value on `dispatch`. (I'm not 100% sure this is possible, but I think so).
- Makes `connect/disconnect` emit an array of entire connect/disconnect chain for introspection.
- Makes `'drain'` emit origin as first argument.
- Makes `Agent` a client with all the api methods (request, stream etc...) on the prototype and same events as `Client`.
So `Agent`, `Pool` and `Client` all implement the same interface and could be used interchangeably. 
Fixes:
https://github.com/nodejs/undici/issues/610
https://github.com/nodejs/undici/issues/616
https://github.com/nodejs/undici/issues/612
> refactor: Unify Client, Pool & Agent

- README.md
> fix(docs): use bold text for new collaborator name

- lib/agent.js
- test/agent.js
- test/dispatcher.js
- test/pool.js
Related to https://github.com/nodejs/undici/issues/438
Started adding some tests to improve coverage. When writing the test for `dispatcher.running`
I realized the iteration in agent `connected`, `size`, `pending`, and `running` was not taking the WeakRef into account.
Wanted to get this change in if it looks good and get back to more tests in another PR.
> test: improve coverage on agent and pool

- benchmarks/index.js
Based on the naming and the look of the options there, it appears the `http - no agent` benchmark was using the incorrect options object.
> test: change `http - no agent` benchmark to use the correct options

- docs/api/Client.md
- docs/api/MockAgent.md
- docs/api/MockClient.md
- docs/api/MockPool.md
- index.d.ts
- test/mock-agent.js
- test/mock-client.js
- test/mock-interceptor.js
- test/mock-pool.js
- test/mock-scope.js
- test/mock-utils.js
- test/types/agent.test-d.ts
- test/types/api.test-d.ts
- test/types/client.test-d.ts
- test/types/dispatcher.test-d.ts
- test/types/global-dispatcher.test-d.ts
- test/types/mock-agent.test-d.ts
- test/types/mock-client.test-d.ts
- test/types/mock-pool.test-d.ts
- test/types/pool.test-d.ts
- types/agent.d.ts
- types/api.d.ts
- types/client.d.ts
- types/dispatcher.d.ts
- types/global-dispatcher.d.ts
- types/mock-agent.d.ts
- types/mock-client.d.ts
- types/mock-interceptor.d.ts
- types/mock-pool.d.ts
- types/pool.d.ts
This PR is a follow up to https://github.com/nodejs/undici/pull/587 as discussed here: https://github.com/nodejs/undici/pull/587#issuecomment-812039005
It adds the following:
- Refactor typings to fit new Dispatcher API
- Adds additional tests for these new typings
- Resolves `tap` deprecation warnings in mock tests
- Corrects small typos in docs
> Update typings to match new Dispatcher API

- lib/client.js
- test/client-timeout.js
- test/http-100.js
Fixes: https://github.com/nodejs/undici/issues/645
> fix: don't headersTimeout while writing request body

- .gitignore
- lib/client.js
- lib/core/request.js
- test/request-timeout.js
Trying to close https://github.com/nodejs/undici/issues/666
Not sure I'm on the right way,  still missing tests 
I'm curious about the HttpParser, I don't have a context there, so I rely on `client[kRunningIdx]` inside `onHeaders`
as it is done in `onHeadersComplete`
> Override timeouts per request

- lib/client.js
Check that the returned pointer is valid befire retrieving the error
message.
Fixes #684
> fix(parser): safer get_error_reason

- test/client.js
> test(client): add parser buffer reallocation case

- lib/client.js
Fixes: https://github.com/nodejs/undici/issues/710
> fix: copy buffers

- README.md
:) 
(Alternatively, if it _is_ a third option and not part of `options`, the declaration needs to be updated)
> Fix small MD issue in readme API doc

- lib/client.js
- lib/pool.js
- test/agent.js
Parsed origin will remove :80 and :443 which will make
the check fail. Resolving this will incur performance loss
so let's just remove it.
Fixes: https://github.com/nodejs/undici/issues/727
> fix: Don't check origin for Pool & Client

- README.md
- index.js
- lib/core/util.js
```js
undici.request('http://foo:800', { path: '/bar' })
undici.request({ path: '/bar', origin: 'http://foo:800' })
undici.request('http://foo:800/bar')
```
> feat: improve global API ergonomics

- benchmarks/index.js
- benchmarks/multiple-sockets.js
- benchmarks/server.js
- benchmarks/single-socket.js
- benchmarks/wait.js
- package.json
This PR closes #715 and #736 by replacing `benchmark` with `cronometro`.
I also refactored the benchmark NPM scripts to use `wait-on` instead of a flat timeout for better reliability.
> chore: Replace benchmark with cronometro for benchmarking.

- package.json
This pr properly exports `index.d.ts` which was not exported previously.
Closes #757
> fix: exports of `index.d.ts`

- lib/core/util.js
👋 all. Thanks for this fantastic lib.
When I require undici inside Electron
and run this code
```js
require('undici/lib/core/util.js').queueMicrotask(() => console.log('hello'))
```
I get a Uncaught TypeError: Illegal invocation
Looks like this is related to how the code is loaded via the cjs/loader
> Fix issue with util.queueMicrotask and cjs loader

- lib/client.js
- lib/core/symbols.js
- test/client-unref.js
- test/connect-timeout.js
Allow process shutdown once all requests have completed without
waiting for keepAliveTimeout.
> feat: unref socket while idle

- lib/client.js
- test/client-request.js
- test/client.js
- test/content-length.js
If response is not keep alive and socket ends then consider it as end of message.
I'm not sure whether this is spec compliant but I believe it would resolve the issue @Ethan-Arrowood encountered.
Refs: https://github.com/nodejs/undici/discussions/782
> fix: end message on connection close

- docs/api/Client.md
- lib/client.js
- lib/core/connect.js
- test/client-errors.js
- test/tls-session-reuse.js
- types/client.d.ts
Issue: https://github.com/nodejs/undici/issues/783
As per the issue description I've added the implementation to handle the maxCachedSessions option, inspired by the node http.Agent.
I would like to discuss about how I handled the default and the zero value.
- Is it ok to set the default to 100 as node does in its Agent?
- Is it ok to disable the session reusability if the value of this option is zero, even if you can disable it reuseSessions option?
Thanks.
> handle maxCachedSessions option in connect class

- lib/client.js
Somehow the error `Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer` occurs when using a saved buffer view.
```js
[1620202083995] FATAL (query): error caused exit
err: {
"type": "TypeError",
"message": "Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer",
"stack":
TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
at Uint8Array.set (<anonymous>)
at Parser.execute (/usr/src/app/node_modules/undici/lib/client.js:513:23)
at Socket.onSocketData (/usr/src/app/node_modules/undici/lib/client.js:892:10)
at Socket.emit (node:events:369:20)
at addChunk (node:internal/streams/readable:313:12)
at readableAddChunk (node:internal/streams/readable:288:9)
at Socket.Readable.push (node:internal/streams/readable:227:10)
at TCP.onStreamRead …
```
> fix: detached buffer error

- docs/api/MockErrors.md
- docsify/sidebar.md
- index.d.ts
- index.js
- lib/mock/mock-errors.js
- lib/mock/mock-utils.js
- test/mock-agent.js
- test/mock-client.js
- test/mock-errors.js
- test/mock-pool.js
- test/mock-utils.js
- test/types/mock-errors.test-d.ts
- types/mock-agent.d.ts
- types/mock-errors.d.ts
Fixes: https://github.com/nodejs/undici/issues/787
As suggested, I've added the following improvements to help debug when a mock dispatch is not matched
For a missing path:
```txt
Mock dispatch not matched for path '/wrong': subsequent request to origin http://localhost:9999 was not allowed (net.connect is not enabled for this origin)
Mock dispatch not matched for path '/wrong': subsequent request to origin http://localhost:9999 was not allowed (net.connect is disabled)
```
For a missing method:
```txt
Mock dispatch not matched for method 'WRONG': subsequent request to origin http://localhost:9999 was not allowed (net.connect is not enabled for this origin)
Mock dispatch not matched for method 'WRONG': subsequent request to origin http://localhost:9999 was not allowed (net.connect is …
```
> Improve mock errors

- docs/api/MockPool.md
- lib/mock/mock-utils.js
- test/mock-agent.js
- test/types/mock-client.test-d.ts
- test/types/mock-pool.test-d.ts
- types/mock-interceptor.d.ts
Closes: https://github.com/nodejs/undici/issues/791
This also adds the following features for the individual header checks:
- Match headers by string
- Match headers by regex
- Match headers by function
> Add mock header matching support

- README.md
- package.json
Fixes https://github.com/nodejs/undici/issues/795
<details>
<summary>System Information</summary>
```console
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1030
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
$ node -v
v16.1.0
```
</details>
<details>
<summary>npm run bench</summary>
```console
$ npm run bench
> undici@4.0.0-rc.3 bench
> concurrently -k -s first npm:bench:server npm:bench:run
[bench:server] 
[bench:server] > undici@4.0.0-rc.3 bench:server
[bench:server] > node benchmarks/server.js
[bench:server] 
[bench:run] 
[bench:run] > undici@4.0.0-rc.3 prebench:run
[bench:run] > node benchmarks/wait.js
[bench:run] 
[bench:run] 
[bench:run] > undici@4.0.0-rc.3 bench:run
[bench:run] > CONNECTIONS=1 node benchmarks/benchmark.js && …
```
> fix(scripts): add `bench:run:simd` with --experimental-wasm-simd enabled

- test/client-connect.js
- test/client-upgrade.js
Adds unit tests for:
* [Line 15](https://codecov.io/gh/nodejs/undici/src/091a4a9fd3e1a9919d974bbef3a2999cc0e65930/lib/api/api-connect.js) of `lib/api/api-connect.js`
* [Line 16](https://codecov.io/gh/nodejs/undici/src/091a4a9fd3e1a9919d974bbef3a2999cc0e65930/lib/api/api-upgrade.js) of `lib/api/api-upgrade.js`
> test: invalid callback for client connect/upgrade

- package.json
Reason: We now always use simd.
Refs: https://github.com/nodejs/undici/pull/735#issuecomment-836255542
Commit: https://github.com/nodejs/undici/commit/50cbeb6622ca4b39c282454ca8efc7accdf13bc0
> chore: remove bench:simd script

- test/types/agent.test-d.ts
- test/types/api.test-d.ts
- test/types/client.test-d.ts
- test/types/dispatcher.test-d.ts
- test/types/pool.test-d.ts
- types/api.d.ts
- types/dispatcher.d.ts
Been starting to use Undici in a TS project and realized I couldn't call `.catch` on the methods! This should fix it.
> make types use promise instead of promiselike

- lib/client.js
The assertion in https://github.com/nodejs/undici/issues/756 should not be possible. This is a try to make that true. I don't really know how those assertions are hit but I'm hoping this might bring some clarity.
Refs: https://github.com/nodejs/undici/issues/756
> fix: try/catch execute

- docs/api/Client.md
- docs/api/Dispatcher.md
- lib/client.js
Consistently propagate unallowed throws in request.onError.
> fix: guard against user throw in onError

- lib/client.js
- lib/core/util.js
- test/http-req-destroy.js
Change so that we destroy IncomingMessage without closing the
socket. Also fixes an invalid assertion that was triggered by
the test.
> fix: destroy IncomingMessage and invalid assertion

- test/types/client.test-d.ts
- test/types/dispatcher.test-d.ts
- types/dispatcher.d.ts
matches typescript types to [UndiciHeaders](https://github.com/nodejs/undici/blob/main/docs/api/Dispatcher.md#parameter-undiciheaders)
> fix(types): add missing string[] option for passed headers

- lib/agent.js
- lib/client.js
- lib/core/symbols.js
- lib/handler/redirect.js
- test/client-dispatch.js
- test/redirect-request.js
**WIP**
Closes #686 
This PR introduces support for redirect by using `RedirectHandler` on `Client` for support redirection.
> feat(Client/Pool): Same origin redirect

- docs/api/Dispatcher.md
- lib/client.js
- lib/core/request.js
- lib/core/util.js
- test/abort-controller.js
- test/abort-event-emitter.js
- test/client-errors.js
- test/client-pipelining.js
- test/client-timeout.js
- test/client.js
- test/content-length.js
- test/get-head-body.js
- test/headers-as-array.js
- test/http-req-destroy.js
- test/no-strict-content-length.js
- test/promises.js
- test/tls.js
- test/utils/async-iterators.js
- test/utils/stream.js
- test/validations.js
continuation of https://github.com/nodejs/undici/pull/363
closes #198
> feature: add support for request iterator body

- lib/handler/redirect.js
- test/redirect-request.js
- test/redirect-stream.js
- test/utils/redirecting-servers.js
> fix: remove `authorization` header when redirecting to unknown origins

- docs/api/Dispatcher.md
- lib/client.js
- lib/core/request.js
- lib/handler/redirect.js
- test/client-dispatch.js
- types/dispatcher.d.ts
Add a callback that's called when a body chunk is sent to the server to `dispatch`.
The callback is invoked only after `stream.write` calls the end callback (I wasn't sure if it should be called synchronously with the call to `write` or not).
For stream bodies, the callback will get invoked after every chunk is written, and for other types (buffer etc.) it will be invoked once after the whole body is sent.
refs: https://github.com/nodejs/undici/issues/820
> feature: add onBodyChunkSent callback to dispatch

- docs/api/Dispatcher.md
- types/dispatcher.d.ts
Add types for 
- DispatchOptions.headersTimeout
- DispatchOptions.bodyTimeout
Add in docs
- DispatchOptions.origin
Reference
- https://github.com/nodejs/undici/issues/874#issuecomment-880227931
> DispatchOptions: add types for headersTimeout, bodyTimeout; add origin in docs

- lib/client.js
writeIterable and writeStream shared a lot of duplicate logic.
>  refactor: reduce code duplication

- lib/client.js
- lib/core/connect.js
- lib/core/symbols.js
- lib/pool.js
- test/close-and-destroy.js
- test/connect-timeout.js
- test/tls.js
Fixes: https://github.com/nodejs/undici/issues/885
> feat: async connect

- lib/agent.js
- lib/core/util.js
- test/agent.js
Fixes #889
```
szm@solus ~/Desktop/undici $ node benchmarks/benchmark.js 
│ Tests               │ Samples │           Result │ Tolerance │ Difference with slowest │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ http - no keepalive │      60 │  5837.63 req/sec │  ± 2.88 % │                       - │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ http - keepalive    │      15 │  9187.24 req/sec │  ± 2.44 % │               + 57.38 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - pipeline   │      25 │ 13515.93 req/sec │  ± 2.76 % │              + 131.53 % │
|─────────────────────|─────────|──────────────────|───────────|───────────────────────── …
```
> fix: accept URL origin in Agent

- lib/agent.js
- lib/client.js
- lib/core/request.js
- lib/core/util.js
- lib/handler/redirect.js
- lib/pool.js
- test/client-dispatch.js
- test/mock-agent.js
Creates a util function to validate handler and adds it on redirect since it was missing.
Also changes the `hostname.startsWith('[')` for `hostname[0] === '['` since it's more performing.
Standardizes invalid handler error messages
Related issue: https://github.com/nodejs/undici/issues/893
> Creating util function to validate handlers

- index.html
Fixes the broken `examples` link for website
Related issue: https://github.com/nodejs/undici/issues/868
**Broken link (current behaviour)**
**Fixed link**
Solution using `noCompileLinks` that was created from a similar problem. More details on Docsify issue: https://github.com/docsifyjs/docsify/issues/203
> fix: broken link for examples on website

- docs/api/Client.md
- test/types/client.test-d.ts
- types/client.d.ts
It looks like the `tls` options has been removed form the types by accident, this pr adds it back.
> Types: improve connect options

- test/types/client.test-d.ts
- test/types/pool.test-d.ts
- types/client.d.ts
- types/pool.d.ts
After PR https://github.com/nodejs/undici/pull/733 `origin` was set to be optional on Client and Pool. This PR fixes the type definitions of `origin` to be optional on `dispatch` and `request` of Client and Pool
Related issue: https://github.com/nodejs/undici/issues/900
> Types: changes origin to be optional on Client and Pool

- docs/api/Client.md
- docs/api/Connector.md
- docsify/sidebar.md
- examples/ca-fingerprint/index.js
- index.d.ts
- index.js
- lib/client.js
- lib/core/connect.js
- lib/pool.js
- test/ca-fingerprint.js
- test/types/connector.test-d.ts
- types/client.d.ts
- types/connector.d.ts
As titled. I've also added an example to show how to validate the CA fingerprint.
Related: https://github.com/nodejs/undici/discussions/904 #905
> Expose Connector in the public API

- lib/core/errors.js
- test/errors.js
This makes undici abort errors compatible with check for `AbortError` i.e.
instead of:
```js
catch (err) {
if (err.code === 'UND_ERR_ABORTED' || err.name === 'AbortError') {
}
}
```
We can now simply do:
```js
catch (err) {
if (err.name === 'AbortError') {
}
}
```
> fix: AbortError compat

- README.md
- docs/api/Dispatcher.md
- lib/api/api-fetch.js
- lib/api/index.js
- test/client-fetch.js
- test/client-pipelining.js
- test/client-write-max-listeners.js
- test/promises.js
It's much easier to implement spec compliant fetch API if we don't try to be node streams at the same time.
> fix: fetch response is not Readable

- lib/api/headers.js
- lib/core/errors.js
This PR ports some of the changes I've made in https://github.com/nodejs/node/pull/38986 
Includes an argument length check as well that isn't in my core PR yet
> port Header class changes from core PR#38986

- lib/api/api-fetch.js
- lib/api/api-request.js
- lib/api/readable.js
- test/client-fetch.js
- test/client-request.js
Closes #925 
Sets the `type` property in `Blob` objects, to the value found in `content-type` response header.
> Fix `blob.type` not having the response type

- test/types/agent.test-d.ts
- test/types/api.test-d.ts
- test/types/client.test-d.ts
- test/types/dispatcher.test-d.ts
- test/types/mock-agent.test-d.ts
- test/types/mock-client.test-d.ts
- test/types/mock-interceptor.test-d.ts
- test/types/mock-pool.test-d.ts
- test/types/pool.test-d.ts
- types/dispatcher.d.ts
fix: #934
Add the easiness of use for TypeScript developers and ensure valid value to be set for `method` parameters.
> types: HttpMethod type

- index.js
- lib/api/readable.js
- test/client-request.js
Refs: https://github.com/nodejs/undici/pull/928#discussion_r688506456
> fix: request body.body regression

- lib/fetch/util.js
- test/node-fetch/response.js
Other `clone` tests error that `clone().buffer` is not a function
> Fix `toWebReadable` finishing too early

- lib/agent.js
- lib/handler/redirect.js
- test/client-request.js
Use EE.prototype.on to avoid mutating stream flowing
state.
> fix: redirect handler should not modify stream state

- lib/handler/redirect.js
- test/redirect-request.js
- test/redirect-stream.js
- test/utils/redirecting-servers.js
In the current implementation, a URL is added to `context.history` only if in the response there is a redirect to follow.
Unfortunately, this results in the final URL of the redirects chain to never be present in the history and apparently there are no other ways to get such URL.
This PR fixes this problem by appending each URL visited. In case of no redirections, the `context.history` will contain just one element.
Hope this helps!
> fix: Include final URL in redirect history.

- .editorconfig
- index.d.ts
- test/types/fetch.test-d.ts
- test/types/formdata.test-d.ts
- types/fetch.d.ts
- types/file.d.ts
- types/formdata.d.ts
> feat: `fetch` types

- lib/core/util.js
- test/util.js
This reverts commit 2ee6e3736c66becea6a14b5aa1693bc06565ecce which incorrectly allowed IP server names.
Sorry for my mistake. Got confused by https://github.com/nodejs/node/blob/e5670f49682ced87451e5fc1e56d7d3fc396c6f2/lib/internal/http2/core.js#L623-L639 incorrectly returning `https://false:443` for IP addresses. However, I did not investigate further. Per [RFC6066](https://datatracker.ietf.org/doc/html/rfc6066#section-3):
> Currently, the only server names supported are DNS hostnames;
> [...]
> "HostName" contains the fully qualified DNS hostname of the server
> [...]
> Literal IPv4 and IPv6 addresses are not permitted in "HostName".
Again I'm deeply sorry for my mistake.
---
Node.js also gives a warning when the servername is an IP address. I must've missed it somehow :(
> fix: revert incorrect servername fix

- docs/api/Dispatcher.md
- lib/api/api-pipeline.js
- lib/api/api-request.js
- lib/api/api-stream.js
- test/agent.js
- test/client-pipeline.js
- test/client-request.js
- test/client-stream.js
- test/types/agent.test-d.ts
- types/dispatcher.d.ts
This is a draft implementation on the onInfo feature proposal. This adds more informations on the context lifecycle of the request. Currently everything is handled in a callback but do we want to have all the infos stored in the request object to be added in the result? With a flag like `verbose` it would make sense otherwise it would fill-up the memory and impact the performances.
If this is ok to implement like so i'll port it to pipeline and stream and add tests for sure. 
fix: https://github.com/nodejs/undici/issues/481
This adds the possibility to get HTTP info headers through a callback
Adding a placeholder for an `onInfo` callback.
Adds an callback handler on Info Headers
N/A
> feat: onInfo

- lib/fetch/formdata.js
- test/fetch/formdata.js
1. `FormData.set(k, v)` will empty the entire `this[kState]` if `k` exists. This is not what it is supposed to do. Fix it.
2. Improve coverage of `lib/fetch/formdata.js`
> fix(fetch): FormData.set empties this[kState] if k exists

- test/fetch/headers.js
Better to require constants from `lib/fetch/constants.js` in `test/fetch/headers.js` rather than to define them.
> test(fetch): requiring consts from constants.js instead of defining

- docs/api/Errors.md
- lib/api/api-connect.js
- lib/api/api-upgrade.js
- lib/client.js
- lib/core/errors.js
- test/client-errors.js
- test/types/errors.test-d.ts
- types/errors.d.ts
If a `SocketError` happens, a user might want to dig deeper to understand why it has happened. For example, they might want to read the socket local/remote address of the socket.
This pr adds a `.socket` property to the `SocketError` which holds the socket that caused the error.
> Expose the socket in case of SocketError

- lib/fetch/body.js
- lib/fetch/file.js
- test/fetch/client-fetch.js
- test/fetch/formdata.js
File class does not have `filename` property, only `name`.
This PR fixes File class, tests and `multipart/form-data` encoder.
See:
* https://developer.mozilla.org/en-US/docs/Web/API/File#instance_properties
* https://w3c.github.io/FileAPI/#dfn-name
> fix: Rename `File.filename` property to `File.name`

- types/file.d.ts
- types/formdata.d.ts
This PR brings various fixes for FormData and File types declarations, including:
1. `FormData`:
* Declare class methods as they should be;
* Minor fixes for methods documentation in code;
* Remove unnecessary constructor declaration;
* Remove unnecessary part from FormData class description;
2. `File`:
* Replace getters with readonly properties;
* Remove `File.stream()` method, because `File` inherits `Blob` which already has this method;
* `FileOptions` interface inherits `BlobOptions` from `@types/node` declarations;
* Rename `name` argument in `File` constructor to `fileName` (based on: https://github.com/microsoft/TypeScript/blob/5546f207c5d20578f1d215ccc110dd42bf8d359b/lib/lib.dom.d.ts#L5220)
* Update `fileBits` description to reflect supported input (based on: …
> fix: Improve `File` and `FormData` types declarations.

- README.md
Adding a simple usage example of Fetch and a very brief explanation of Node Streams vs Web Streams. 
https://github.com/nodejs/undici/issues/940
> docs: add basic example of fetch

- docs/api/Errors.md
- lib/client.js
- lib/core/util.js
- test/client-errors.js
- test/types/errors.test-d.ts
- types/client.d.ts
- types/errors.d.ts
The previous implementation didn't work well, as some of the properties of the `Socket` instance were removed while destroying the socket, making the socket instance useless for debugging purposes.
This pr stores the properties before destroying the socket in a separate object as we previously discussed.
Follow up of https://github.com/nodejs/undici/pull/1041
> Update .socket property of SocketError class

- benchmarks/server.js
- lib/core/connect.js
Node's default HWM is rather small... this can give a slight performance improvement especially for large bodies.
> perf: use bigger HWM by default

- docs/api/DiagnosticsChannel.md
Fixed spelling mistakes in Diagnostic Channel API docs
> docs: spelling fixes to diagnostic channel

- docs/api/DiagnosticsChannel.md
- lib/client.js
- lib/core/request.js
- test/diagnostics-channel/get.js
Fix for issue #1052 
When instrumenting with APM's it is valuable to have the full origin for the request so we can perform filtering.
This is also required at the time the request is created as this is usually when tracing headers are injected.
Adds `origin` member on the `Request` entity for propagation through the diagnostics channels
> Store origin on request to facilitate instrumentation

- lib/fetch/headers.js
- test/fetch/headers.js
This matches the browser behavior, example:
```js
let demo = new Headers({ foo: '123', bar: '456' });
for (let [k,v] of demo) { 
demo.delete(k);
demo.set(`x-${k}`, v);
}
[...demo];
//=> [
//=>   ['x-bar', '456'],
//=>   ['x-foo', '123'],
//=> ]
```
> **Note:** This is included as a test
> fix(headers): iterate over cloned list

- index.d.ts
- test/types/index.test-d.ts
Not sure how I missed this previously. This adds `fetch` to the namespace so you can do:
```ts
import undici from 'undici'
undici.fetch(/* ... */)
```
Includes a test as well.
> add fetch to namespace

- docs/api/MockPool.md
- lib/mock/mock-utils.js
- test/mock-utils.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
With this change, it's possible to return binary payloads from an intercepted call:
```
const mockImage = readFileSync('/path/to/image/png')
mockPool.intercept({ path: '/foo', method: 'GET' }).reply(200, mockImage)
```
I haven't bothered with docs yet. I'll update them if there's interest in merging this.
> feat: Allow buffers as mock response data

- README.md
- docs/api/Agent.md
- docs/api/BalancedPool.md
- docs/api/Client.md
- docs/api/Dispatcher.md
- docs/api/MockAgent.md
- docs/api/MockClient.md
- docs/api/MockPool.md
- docs/api/Pool.md
- docs/api/ProxyAgent.md
- docs/api/api-lifecycle.md
- index.html
- swept through local links and fixed broken anchors
- updated local links to relative
- absolute paths break links when you're browsing docs in the repo, e.g. `https://github.com/nodejs/undici/blob/main/docs/api/docs/api/Client.md`. Absolute paths were apparently added because of docsify, which by default does not recognize relative paths. This can be fixed by setting [`relativePath`](https://docsify.js.org/#/configuration?id=relativepath) to `true` in docsify configs
> docs: fix links

- docs/api/Agent.md
Removed an unexpected ` quote in the Agent.md file.
> docs: fix DispatchOptions markdown format

- lib/fetch/formdata.js
- test/fetch/formdata.js
Fixes #1095 
- add FormData@@toStringTag
- add FormData.entries
- add FormData.keys
- add FormData.values
Typings were already correct & did not need to
be updated. The [FormData Spec](https://xhr.spec.whatwg.org/#interface-formdata) does not include
these methods, but [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FormData#methods) documents them.
> increase FormData compatibility

- lib/fetch/formdata.js
- lib/fetch/util.js
- package.json
- test/fetch/formdata.js
Works around https://github.com/nodejs/node/issues/37340.
Advances https://github.com/telegraf/telegraf/issues/1502.
Closes #930.
> feat: accept third-party `Blob`s in `FormData`

- lib/balanced-pool.js
- lib/pool-base.js
- lib/pool.js
- test/balanced-pool.js
- test/pool.js
Unified pool and balanced-pool to use the same scheduling implementation. There is still room for improvement but this is a good first step.
> fix: balanced pool

- lib/api/readable.js
- test/client-request.js
move from `Array.join()` to `Buffer.concat()` to fix bugs in multibyte characters.
Fixes: https://github.com/nodejs/undici/issues/1119
> fix: concat multibyte characters

- lib/fetch/body.js
- lib/fetch/index.js
- test/fetch/issue-1137.js
Refs: https://github.com/nodejs/undici/issues/1137
> fix: don't cancel with invalid state

- lib/fetch/index.js
- lib/fetch/util.js
Implements spec changes from https://github.com/whatwg/fetch/commit/8659a25e2dcad911a372f74ac70b60607a264e42 
refs: #1141 (this didn't take me very long because it was mostly just renaming the utility function)
> update timingInfo to follow new spec changes

- lib/fetch/constants.js
- lib/fetch/response.js
This condition is not *yet* possible to meet so I couldn't add a test
(sorry!). 
- `response` is always null https://github.com/nodejs/undici/blob/09059fb491b4158a25981eb5598262b43a18c6ae/lib/fetch/index.js#L475
- which means it is set here https://github.com/nodejs/undici/blob/09059fb491b4158a25981eb5598262b43a18c6ae/lib/fetch/index.js#L529 which always either returns a network error or sets the `responseTainting` to either `opaque` or `cors`.
- Then this condition runs if there wasn't a network error (`response.status === 0` would be a network error) https://github.com/nodejs/undici/blob/09059fb491b4158a25981eb5598262b43a18c6ae/lib/fetch/index.js#L605
- Therefore responseTainting is never basic as of now.
The spec says that "[a] basic filtered response is a filtered response
whose type …
> fetch: fix small spec inconsistency

- lib/fetch/index.js
- lib/fetch/request.js
- lib/fetch/util.js
- test/fetch/util.js
This PR contains 3 fetch bug fixes:
- In `mainFetch`, `response` was not being set in 2 places ("then set response to a network error.").
- In [`httpRedirectFetch`](https://fetch.spec.whatwg.org/#http-redirect-fetch), the old step 12 has been removed
- The terms "same origin" actually refers to a [series of steps](https://html.spec.whatwg.org/multipage/origin.html#same-origin) that need to be taken, not just comparing the URL's origin. ([see here](https://github.com/nodejs/undici/pull/1165#issuecomment-1011317842))
> fetch: multiple small fixes

- README.md
Minor issue I've found while making sense of the docs.
> Uncaught TypeError: res is not async iterable
> docs: fix typo in sample code

- index.d.ts
ProxyAgent is imported with the assumption that `allowSyntheticDefaultImports` is enabled. The aforementioned option is disabled by default. As a result, users are required to enable `allowSyntheticDefaultImports` in order to have an error-free TypeScript experience.
https://github.com/nodejs/undici/pull/1070#discussion_r796794771
> Fix import of `ProxyAgent`

- lib/fetch/request.js
- test/fetch/request.js
> fix: fetch - don't coerce null or undefined integrity to a string

- test/types/api.test-d.ts
- types/api.d.ts
DispatchOptions passed to the request api doesn't **NEED** to have a `method` param since it defaults to `'GET'` (or `'PUT'` if there is an optional body).
https://github.com/nodejs/undici/blob/6c2c6addcced5284144e876bce1b827717a03e47/index.js#L83-L88
```ts
const { request } = require('undici');
// Doesn't have method param
const options = {};
// method defaults to "GET"
request('http://example.com', options).then(console.log)
```
Why is this important? If `method` is required it makes it awkward to use a default object that does't specify the method rather than letting it get computed automatically later on.
> Property 'method' is missing in type '{}' but required in type
```ts
const foo = (url, options = {}) => {
// do stuff with options
return request(url, options);
};
```
>  fix: method is not required for request api

- lib/client.js
Recent changes to how the wasm is loaded in #1183 have accidentally changed the order of simd/other builds.
You can see in the diff, originally the 
```diff
try {
-    mod = await WebAssembly.compile(await readFile(resolve(__dirname, './llhttp/llhttp_simd.wasm')))
+    mod = await WebAssembly.compile(Buffer.from(llhttpWasmData, 'base64'))
} catch (e) {
...
-    mod = await WebAssembly.compile(await readFile(resolve(__dirname, './llhttp/llhttp.wasm')))
+    mod = await WebAssembly.compile(Buffer.from(llhttpSimdWasmData, 'base64'))
}
```
This makes sense because the simd build should throw when it isnt supported, and the catch loads the basic version.
Currently no one will be using the simd version.
This PR changes the order back, so that simd is loaded first, and on error we can the basic …
> Fix order of WASM loading

- test/fetch/client-fetch.js
This adds coverage for
https://github.com/nodejs/undici/blob/abf7c4547d1a1aa9e023c0536a890bc0aa183f48/lib/fetch/file.js#L71.
Refs: https://github.com/nodejs/undici/issues/951
Signed-off-by: Darshan Sen <raisinten@gmail.com>
> test(fetch): `File` coverage

- docs/api/MockPool.md
- lib/mock/mock-utils.js
- test/mock-interceptor.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
This adds the ability to have callbacks when replying to a mocked requests, similar to how nock enables callbacks for responses. This is especially helpful for situations where the response depends on certain request options.
Example of how it can be used:
```ts
mockPool
.intercept({
path: '/test',
method: 'GET',
})
.reply(200, ({ headers }) => ({
myHeader: headers.get('foo'),
}));
const res = await fetch('http://localhost:3000/test', {
headers: {
foo: 'bar',
},
}).then((res) => res.json());
console.log(res); // Prints { myHeader: 'bar' }
```
> feat(MockInterceptor): add support for callbacks on `reply`

- lib/fetch/file.js
- test/fetch/client-fetch.js
Signed-off-by: Darshan Sen <raisinten@gmail.com>
> fix(fetch): prevent `Illegal invocations` of the `FileLike` class

- lib/fetch/util.js
- test/fetch/util.js
`/^http?s/` is matched for `htts` and `https`.
It should fix to `/^https?:/` (matched for `http:` and `https:`)
> fix: incorrect http(s) regexp

- docs/api/MockPool.md
- lib/mock/mock-interceptor.js
- lib/mock/mock-utils.js
- test/mock-interceptor.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
This PR is similar to #1200, except it allows dynamic mocking of *all* reply options rather than just the `data`.
```js
mockPool.intercept({
path: '/echo',
method: 'GET',
headers: {
'User-Agent': 'undici',
Host: 'example.com'
}
}).reply(({ headers }) => ({ statusCode: 200, data: { message: headers.get('message') }})))
const { statusCode, body, headers } = await request('http://localhost:3000', {
headers: {
message: 'hello world!'
}
})
console.log('response received', statusCode) // response received 200
console.log('headers', headers) // { 'content-type': 'application/json' }
for await (const data of body) {
console.log('data', data.toString('utf8')) // { "message":"hello world!" }
}
```
This is useful in situations where the status code and the response headers need to be dynamically …
> feat(mock): add support reply option callbacks

- benchmarks/benchmark.js
`fetch()` has significant bottlenecks, we should track its performance.
```
│ Tests               │ Samples │           Result │ Tolerance │ Difference with slowest │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - fetch      │      20 │  1028.31 req/sec │  ± 2.71 % │                       - │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ http - no keepalive │      10 │  3891.51 req/sec │  ± 2.00 % │              + 278.44 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────────|
│ undici - pipeline   │      95 │  6034.47 req/sec │  ± 2.95 % │              + 486.83 % │
|─────────────────────|─────────|──────────────────|───────────|─────────────────────── …
```
> Added fetch to our benchmark suite

- .npmignore
After https://github.com/nodejs/undici/pull/1183, WASM files are no more necessary to be shipped as part of the NPM bundle
> chore: ignore wasm file for npm publishing

- package.json
- test/types/fetch.test-d.ts
- test/types/proxy-agent.test-d.ts
- types/mock-interceptor.d.ts
As titled. I don't know why `tsd` didn't catch this.
Fix #1223
> Add missing ts import

- lib/fetch/request.js
- test/fetch/request.js
Fixes: https://github.com/nodejs/undici/issues/1225
> fix: `RequestInit` doesn't allow explicit `undefined`

- docs/api/BalancedPool.md
- lib/balanced-pool.js
- test/balanced-pool.js
> feat: add factory option to BalancedPool

- lib/api/api-connect.js
- lib/api/api-pipeline.js
- lib/api/api-request.js
- lib/api/api-stream.js
- lib/api/api-upgrade.js
- lib/core/util.js
- test/client-request.js
- test/util.js
- types/dispatcher.d.ts
add rawHeaders whenever we return headers.
hope this PR makes sense
closes https://github.com/nodejs/undici/issues/1213
> feat: pass rawHeaders

- lib/balanced-pool.js
- test/balanced-pool.js
Fixes #1250.
Calls `parseOrigin` on upstream addition/removal to ensure that finding an existing upstream by `origin` works when deduplicating/removing an upstream.
> feat: normalize origin for BalancedPool addUpstream/removeUpstream

- docs/api/BalancedPool.md
- docs/api/Pool.md
- docs/api/PoolStats.md
- lib/core/symbols.js
- lib/pool-base.js
- lib/pool-stats.js
- test/pool.js
In achieving parity with the node.js agent, I'd like to be able to get aggregate statistics about requests and connections in undici. This is possible today, but requires using private symbols.
Addresses #1254, relates to #693 -- I just now noticed that one, so will review it to see if there's any feedback that can be applied here.
I currently use the node.js agent and send its stats to prometheus; I'd like to send the same ones for undici to be able to instrument the switchover and ensure everything is working properly.
* Expose a `stats` getter on pools.
* Access aggregate statistics about undici Pools via a `stats` object.
N/A
N/A
- I didn't benchmark it because the new methods aren't in the normal request path and are …
> feat: expose pool aggregate statistics

- test/fetch/headers.js
- test/node-fetch/headers.js
- types/fetch.d.ts
This is a TypeScript-only change, undici already handles Records with string[] values: https://runkit.com/embed/972d5c6lsor2
A test was created to ensure this feature works properly
> Allow string[] as Record value on HeadersInit

- lib/client.js
- test/client-request.js
#1257
Includes a failing test and a suggestion for how that test can be made to pass.
- Added test confirming that the correct host header is being sent when: 1) it is a non-empty string; 2) it is `undefined`; and 3) it is an empty string.
- Added a change to distinguish empty strings from other falsy values when building the request.
N/A
Fixes #1257
Anyone relying on being able to explicitly set a header to an empty string and have that default to the target host will observe a change in behaviour.
> Fix for ignoring explicit empty host header values

- test/types/readable.test-d.ts
- types/dispatcher.d.ts
- types/readable.d.ts
Updates the `body` to use `BodyReadable`. Currently, body was using an intersection between `Readable` and `BodyMixin`. 
This actually exposes the `dump` function in TypeScript now.
Let me know if the `resume` and `abort` are actually nullable. I looked at the code and `abort` is `null` initially. `resume` seems to be optional for `Readable`
Fixes #1256
> fix: Improve BodyReadable type definition

- lib/client.js
- package.json
- test/jest/test.js
fixes https://github.com/nodejs/undici/issues/1235
Its pretty horrible, and but really need a solution to this problem.
> feat: eager loading of wasm in jest environment

- .github/workflows/nodejs.yml
Fixes https://github.com/nodejs/undici/issues/1263
> drop mac os x because it constantly fails

- .github/workflows/bench.yml
- .github/workflows/fuzz.yml
Bump GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12.
> build(deps-dev): bump github actions

- package.json
It breaks AIX in CITGM. Use npx instead.
> fix: remove esbuild from dev dependencies

- lib/mock/mock-interceptor.js
- test/mock-interceptor.js
See https://github.com/nodejs/undici/issues/1245
As per RFC 3986, clients are not supposed to send URI  fragments to servers when they retrieve a document.
> fix: remove hash from intercept dispatch key

- lib/mock/mock-utils.js
- test/mock-agent.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
resolves #1269 and (subjectively) a preferred alternative to #1274
> feat(mock): allow matching the complete header list

- benchmarks/benchmark.js
> chore: fix import readablestream

- test/node-fetch/main.js
Fixes #1221 
Detailing the issue: https://github.com/nodejs/undici/issues/1221#issuecomment-1069403588
tl;dr delaying the abort made the test flaky
One thing to note: the node-fetch tests here are outdated as of https://github.com/node-fetch/node-fetch/commit/015798edc60f6b480b3df2412f4069df05cb86d5 but they use ESM and rely heavily on internal methods that would require a lot of work to port over. I also don't know if any other tests are flaky, so the node-fetch suite might still cause issues.
> tests: fix CI failure

- test/agent.js
This PR refactors `test/agent.js`.
- It imports `../` and `../index` but those are the same.
- It uses `InvalidArgumentError` and `errors.InvalidArgumentError` but those are the same.
> chore: fix duplicated error import in test/agent.js

- package.json
This PR changes the `coverage` command to output an HTML coverage report in addition to the default text coverage report. https://github.com/istanbuljs/nyc#common-configuration-options
> chore: html reporter

- lib/mock/mock-agent.js
- test/mock-agent.js
This PR fixes a very hard to spot bug that happens under these conditions:
1. You use mocks and setup some interceptors.
2. The pool/client (`mockAgent.get`) is setup within a function and no reference to the pool/client is returned.
3. A lot of request (same or different url doesn't matter) are performed and a lot of data is returned.
4. Some time passes (either with setTimeout or just with regular application I/O delays)
What happens is that the original pool/client is garbage collected and thus all the set interceptors are gone, leading to either test failure or unwanted network activity.
The PR fixes that by using a `FakeWeakRef` in the `MockAgent` that keeps a reference to the pool and thus no garbage collection happens.
> fix: Do not use WeakRef on mocks.

- .husky/pre-commit
- lib/fetch/index.js
- This PR suppresses lint error on WIP implementation.
- This PR adds the lint command to the pre-commit hook.
https://github.com/nodejs/undici/runs/5610494557?check_suite_focus=true
```
> undici@4.1[6](https://github.com/nodejs/undici/runs/5610494557?check_suite_focus=true#step:5:6).0 lint
> standard | snazzy
standard: Use JavaScript Standard Style (https://standardjs.com)
/home/runner/work/undici/undici/lib/fetch/index.js
15[8](https://github.com/nodejs/undici/runs/5610494557?check_suite_focus=true#step:5:8)[9](https://github.com/nodejs/undici/runs/5610494557?check_suite_focus=true#step:5:9):[11](https://github.com/nodejs/undici/runs/5610494557?check_suite_focus=true#step:5:11)  error  'newConnection' is assigned a value but never used
✖ 1 problem
Error: Process completed with exit code …
```
> Fix lint error

- lib/fetch/index.js
- tmp.js
Don't start prefetching the body before headers and status
has been processed.
Fixes: https://github.com/nodejs/undici/issues/1271
> fix: lazy decode body

- benchmarks/benchmark.js
- benchmarks/wait.js
- package.json
Our bench CI job is not working anymore. This PR partially fixes it _but_ the number of iterations do not work anymore.
```
[bench:run] │ Tests               │ Samples │          Result │ Tolerance │ Difference with slowest │
[bench:run] |─────────────────────|─────────|─────────────────|───────────|─────────────────────────|
[bench:run] │ undici - fetch      │       1 │  596.19 req/sec │  ± 0.00 % │                       - │
[bench:run] |─────────────────────|─────────|─────────────────|───────────|─────────────────────────|
[bench:run] │ http - no keepalive │       1 │ 1123.28 req/sec │  ± 0.00 % │               + 88.41 % │
[bench:run] |─────────────────────|─────────|─────────────────|───────────|─────────────────────────|
[bench:run] │ http - keepalive    │       1 │ 1943.09 req/sec │ …
```
> Fix broken bench scripts

- lib/fetch/index.js
- lib/fetch/response.js
Restructure the implementation so that it more clearly
follows the spec.
> refactor(fetch): refactor httpNetworkOrCacheFetch

- test/balanced-pool.js
This PR improves coverage for balanced-pool.
> chore: improve coverage for balanced-pool

- lib/mock/mock-utils.js
- test/node-fetch/mock.js
Fixes the ability to match a mock on the complete header when using fetch. This ability was introduced in [v4.16.0](https://github.com/nodejs/undici/releases/tag/v4.16.0), specifically #1275.
The issue is in the fact that when using fetch the matcher argument is not a plain object but rather HeadersList.
> fix(mock): matching the complete header list when using fetch

- docs/api/MockAgent.md
- docs/api/MockClient.md
- docs/api/MockPool.md
- lib/mock/mock-interceptor.js
- test/mock-client.js
- test/mock-pool.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
I am in the process of migrating an open source project from `node-fetch` to `undici`.  I am making heavy use of `nock`, which doesn't exactly work here :) One of the things I noticed is that nock tends to default to assuming `GET` on interceptors, and I think it's a fairly accepted norm in terms of request libraries.  This change makes `method` optional on the `MockClient.intercept` method, and defaults it to a `GET` in that case.  
```js
const mock = new MockAgent();
const scope = mock
.get('http://fake.local')
.intercept({path: '/'}) // look ma, no {method: 'GET'}!
.reply(200);
```
Not sure if this is a desirable API change or not, but thought it would aid in making the transition from `nock` to here a tad easier.
> fix: default mock interceptor to GET

- lib/fetch/index.js
It avoids treating `request.body` as an async iterator when it's null.
In my local tests, it increases the performance by almost 10%.
> fetch: avoid async iteration when request.body is null

- lib/fetch/util.js
- test/fetch/util.js
Implemented CORBcheck as per the [spec](https://fetch.spec.whatwg.org/#corb-check) 
Maybe `isCORBProtectedMIME` needs to be polished?
> feat: CORB check.

- index.d.ts
- test/types/index.test-d.ts
- test/types/mock-interceptor.test-d.ts
PR related to https://github.com/nodejs/undici/issues/1306
Not sure if i had to add a new TSD test somewhere for this new export.
> chore: export Interceptable interface

- test/types/fetch.test-d.ts
- types/fetch.d.ts
Add missing ReadableStream type to fetch response.body (relate to #1308).
Hope i have not missed something, ~~maybe we need a seperate type for `(ControlledAsyncIterable & ReadableStream) | null` ?~~
> fix(fetch): add missing ReadableStream interface to response.body

- lib/fetch/index.js
Hey, a user of one of our libraries [reported an unexpected syntax error on Node.js 14](https://github.com/graphprotocol/graph-client/issues/34), which I tracked down to this line.
The package.json of this project lists [`"node": ">=12.18"` in the engines](https://github.com/nodejs/undici/blob/8b1dcd44755d7c9bfba06066518f4c01629ad1c0/package.json#L96-L98).
[Logical Assignment is only supported since Node.js 15.14](https://node.green/#ES2021-features-Logical-Assignment).
To me, it seems like this usage here got added unexpectedly.
___
We would love to prevent such things in the future by setting up a GitHub action that runs eslint with the following rule: https://github.com/weiran-zsd/eslint-plugin-node/blob/HEAD/docs/rules/no-unsupported-features/es-syntax.md
Would that be something you …
> fix: remove logical assignment operator

- lib/mock/mock-interceptor.js
- lib/mock/mock-utils.js
- test/mock-agent.js
- test/mock-client.js
- test/mock-utils.js
> Fix mock bugs

- README.md
This PR proposes to resolve the documentation issue outlined in #1208.
I referenced the `fetch` spec in some ways I felt read naturally, and attempted to structure the docs in a way that it would read/flow from most common use cases and wanted-info to most obscure or infrequently used. Added a little sugar to references that users might find useful or interesting. I'm not married to any part of it, but want to make sure that we're pointing users in the right direction for using mixins and potential pitfalls, especially those who have been using alternatives to fetch and aren't up to speed.
> docs: expand mixins information, notate body reuse

- lib/fetch/headers.js
- lib/fetch/index.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/headers.js
- test/node-fetch/mock.js
This PR replaces the `HeadersList` Array inheritance to Map, which basically is more suitable for headers use case. ~It also increases the performance by 10% (it's not done yet, so it might be more/less)~.
> fetch: replace HeadersList Array inheritance to Map

- lib/client.js
- lib/core/util.js
- test/client-request.js
- test/types/formdata.test-d.ts
- test/utils/formdata.js
- types/dispatcher.d.ts
Fixes #1330 
Allows sending a FormData body to `undici.request`.
> feat: allow `FormData` bodies in `request`

- lib/fetch/response.js
- test/fetch/headers.js
Fixes #1328
Two issues with the recently added filtered lists and using Proxy.
> fix(Headers): filter out forbidden headers & `get` should return null on unknown header name

- lib/core/request.js
Prevent using unnecessary slice method and unify version check code.
> Unify version check code with index.js

- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
Partially fixes #1322
This sets the callback option body type to the input types supported by undici. Replication with `Uint8Array`, `Buffer`, etc. can be shown in the code provided in the issue.
(this is a types-only change)
> fix(types): callback body can be any input type

- lib/api/api-request.js
- test/jest/mock-scope.test.js
> fix: jest bug when using MockScope.delay

- docs/best-practices/mocking-request.md
Small fix to a [mock request example](https://undici.nodejs.org/#/docs/best-practices/mocking-request?id=mocking-request) that was broken.
> doc: fix documented mock request example

- lib/fetch/index.js
- lib/fetch/request.js
Those `new URL` calls seem unnecessary. Its basically doing `new URL(new URL(x))`
It bumps the performance by 10% on avg.
> fetch: remove unnecessary new URL calls

- lib/fetch/index.js
- test/fetch/client-fetch.js
fixes: https://github.com/nodejs/node/issues/42804
the error will be warped again by `makeNetworkError` at L1751:
https://github.com/nodejs/undici/blob/b6a72620a67236ea84160a0ae3d505b3d77a2214/lib/fetch/index.js#L1734-L1752
> fix(fetch): makeNetworkError called twice when httpNetworkFetch run error

- lib/fetch/index.js
This PR makes sure no decoding attempt is done when there will be no body.
Fixes: #1359
> fix: do not set decoders when there will be no body (#1359)

- README.md
As PR title states: teeny tiny grammatical fixes.
> docs(readme): minor grammar fixes

- docs/api/Dispatcher.md
- lib/proxy-agent.js
- test/proxy-agent.js
Fixes #1355
types were already correct (I'm guessing this issue has been around for a little bit):
https://github.com/nodejs/undici/blob/1dc2977c94583efbecd5b6791b5a091d18a2ceeb/types/dispatcher.d.ts#L49
> fix: ProxyAgent dispatch options receives a header array when using fetch

- .github/workflows/lint-pr.yml
> build: add support for `lint-pr` GitHub action workflow 🕺

- test/http-100.js
Removes an erroneous `only` filter from a test in `http-100.js`
Refs: https://github.com/nodejs/undici/pull/716
> test: remove erroneous tap test only filter

- .github/dependabot.yml
- .github/workflows/nodejs.yml
> feat: add support for dependabot 🥳

- test/headers-as-array.js
https://github.com/nodejs/undici/pull/1374 broke linting.
> chore: fix linter errors caused by linter update

- lib/mock/mock-utils.js
- test/mock-pool.js
- test/mock-utils.js
> fix(mock-utils): match header when using fetch

- lib/mock/mock-utils.js
- test/mock-agent.js
- test/mock-utils.js
When encountering an unknown status code, an error should not be thrown. This behavior now matches fetch's behavior (tested with undici & node-fetch, unsure about browsers but I doubt it is different).
> fix: use `unknown` statusText by default in mocks

- lib/fetch/index.js
- test/fetch/abort.js
Fixes #1389
Sorry about that, I got lazy and didn't realize recreating the fork would close PRs 😵
Applies ronag's suggestion from #1390
> fix: exit loop early if request was aborted

- benchmarks/benchmark.js
This fixed compatibility with ESM version of cronometro.
> fix: Restored compatibility with cronometro.

- .husky/pre-commit
- lint-staged.config.js
There was nothing wrong with the original pre-commit hook. The only thing #1349 does is introduce an extra dependency that needs to be downloaded (which could be compromised down the road).
> chore: revert #1349

- lib/fetch/request.js
- test/fetch/request.js
Fixes #1407
Although the spec says to "append" the header, setting it should make no difference as the check beforehand ensures that no 'content-type' header exists.
p.s.: I have no idea how the header was being duplicated 😕
> fix(Request): URLSearchParams body w/ Headers obj

- .github/workflows/lint-pr.yml
As discussed in https://github.com/nodejs/undici/pull/1356#discussion_r856063520, the use of `pull_request_target` here opens up a potential security hole.
Declaring the minimum [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for this workflow to run, following principle of least privilege, negates this. See [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/) regarding permissions.
> ci(lint-pr): reduce permissions to minimum

- docs/api/Errors.md
- lib/client.js
- lib/core/errors.js
- test/errors.js
- test/trailers.js
Fixes #1418.
As in that issue, I don't think there's any reason for this, and it doesn't match other implementations, so this removes the error and check entirely, and flips the error tests to check it works correctly.
> fix: Remove unnecessary mismatched trailers check

- lib/fetch/headers.js
- test/fetch/headers-iterator.js
- test/types/fetch.test-d.ts
- types/fetch.d.ts
See:
- https://github.com/node-fetch/node-fetch/issues/1119#issuecomment-100222049
- https://bugs.chromium.org/p/chromium/issues/detail?id=793204
This implements `Headers Iterator` which is a generator-like... thing... that only has a ` .next()` method. Chrome doesn't implement this entirely correct so I recommend using Firefox to see the correct behavior.
Notes:
- Typescript's Header types are incorrect! You can't use `.return()` or `.throw()` on a Headers iterator (.keys(), .entries(), .values(), Symbol.iterator()).
- Deno does implement this correctly.
- The [`Headers`](https://fetch.spec.whatwg.org/#headers-class) standard doesn't mention Headers Iterator at all so I made this implementation through ✨ trial and error ✨.
> feat(Headers): implement `Headers Iterator`

- lib/fetch/headers.js
- test/fetch/headers.js
`Headers.forEach` had a bunch of things wrong with it:
- Parameter order was named weird (where `key` was named as `index` in the code).
- `thisArg` was not set to `globalThis` by default.
- `Headers.prototype.forEach.length` was returning 0, instead of 1 (this is another issue I was going to make a PR for eventually).
I have 2 more PRs planned for Headers fixes, so I'm wondering if you would prefer combining those 2 changes into a single PR, or if you would prefer 2 separate PRs?
> fix(Headers): forEach

- lib/fetch/headers.js
- test/fetch/headers.js
I don't know about fetch's WPTs, but when I was working on a spec-compliant localStorage/sessionStorage, there were tests to ensure the correct function length. Regardless, this change makes the behavior identical to browsers.
> fix(Headers): ensure prototype method signatures are correct

- lib/fetch/headers.js
- test/fetch/headers-iterator.js
Follow-up to #1423 that provides hopefully 100% spec compliance.
See: https://github.com/whatwg/fetch/issues/1437#issuecomment-1122701985
> fix(Headers Iterator): make spec compliant

- lib/fetch/headers.js
- test/fetch/headers.js
Fixes 2 bugs:
1. `Headers.toString` should be inherited from Object's prototype.
2. The `Symbol.toStringTag` getter should not be brand checked.
> fix(Headers): do not brand-check toString & Symbol.toStringTag

- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/file.js
- test/fetch/formdata.js
- test/fetch/request.js
- test/fetch/response.js
Continuation of #1430
I also removed the FormData export resolving to globalthis.FormData by default as it made testing the fixes impossible.
> fix(fetch): remove brand checks from Symbol.toStringTag

- test/fetch/file.js
- test/fetch/request.js
- test/fetch/response.js
The tests would always pass regardless of if the assumption (accessing prototype methods/getters without a valid `this` value will throw) was correct.
For example,
`File.prototype.name` is a string, so `.call(...)` is not a function. It will always throw a TypeError, even if the brand check was removed.
> fix(test/fetch): <getter>.call will always throw

- test/types/fetch.test-d.ts
- types/fetch.d.ts
> fix(types): make `RequestInit` properties assignable

- lib/fetch/index.js
- lib/fetch/response.js
- test/fetch/client-fetch.js
Fixes #1262 
When `credentials` is equal to `include`, the `set-cookie` header(s) should not be stripped.
> fix: get `set-cookie` header with `credentials: include`

- lib/fetch/body.js
On one hand, the current implementation of the core `isFormDataLike` helper is:
https://github.com/nodejs/undici/blob/2ea8f0375dfa83e71d14e68fd90af51af2b868a4/lib/core/util.js#L328
On the other hand, the Fetch code has an actual [`FormData` implementation](https://github.com/nodejs/undici/blob/2ea8f0375dfa83e71d14e68fd90af51af2b868a4/lib/fetch/formdata.js).
The latter's `constructor.name` is `'FormData'`, so the combination of the two does work. So far, so good.
Now, I'm using esbuild to bundle undici into my app. Because of some naming conflict, it renames the class to `FormData3`. And then, all hell breaks loose.
To avoid that issue, this PR makes the Fetch part explicitly check the type of the given object.
It'd probably be better to update the core helper instead. I'd originally …
> fix(fetch): Explicitly check for FormData type

- lib/proxy-agent.js
- test/fetch/blob-uri.js
- test/fetch/request.js
- test/proxy-agent.js
> refactor: replace import of `URL` class with global reference

- lib/fetch/body.js
- lib/fetch/formdata.js
- test/fetch/formdata.js
See https://github.com/nodejs/undici/pull/1451#issuecomment-1131619657
I've tested this using `esbuild` with `--minify` and `util.isFormData` still works on a minified `FormData` class
> fix(fetch): replace `instanceof FormData` check

- lib/fetch/index.js
- lib/mock/mock-agent.js
- lib/mock/mock-utils.js
- package.json
- test/fetch/issue-1447.js
Fixes #1447 
No tests but I could theoretically add them in (by calling `npm run node:build` and then using that file, but seems pretty hacky).
Verify the fix works:
test.mjs:
```js
import * as undici from './index.js' // 5.2.0
import { fetch } from './undici-fetch.js'
const mockAgent = new undici.MockAgent()
mockAgent.disableNetConnect()
undici.setGlobalDispatcher(mockAgent)
const pool = mockAgent.get('https://example.com')
pool.intercept({
path: '/path',
method: 'POST',
body (body) {
console.log(body)
return true
}
}).reply(200, { ok: 1 }).times(2)
const url = new URL('https://example.com/path').href
// undici fetch v5.2.0 from node_modules
await undici.fetch(url, {
method: 'POST',
body: JSON.stringify({ foo: 'bar' })
})
// undici fetch v5.2.0 from node 18.2.0 global
await fetch(url, { …
```
> fix: mock node fetch with `options.body` fn

- docs/best-practices/mocking-request.md
Following up from this discussion https://github.com/nodejs/undici/discussions/1185 I thought there was a missing bit in the doc around the fact that the `reply` `data` parameter can be a function that will have the mocked request options as input .
> docs: Add documentation for reply accepting a function as the data parameter

- test/types/readable.test-d.ts
- types/dispatcher.d.ts
- types/mock-interceptor.d.ts
_This PR is a continuation of the changes made in #1059._
`BodyReadable` is imported with the assumption that `allowSyntheticDefaultImports` is enabled. This is restrictive to consumers wishing to use undici's type definitions without its enablement.
The following imports have been fixed:
- `BodyReadable` in test/types/readable.test-d.ts
- `BodyReadable` in types/dispatcher.d.ts
- `Dispatcher` in types/mock-interceptor.d.ts
> fix: import `BodyReadable` and `Dispatcher` correctly

- docs/api/MockPool.md
- lib/mock/mock-interceptor.js
- lib/mock/mock-utils.js
- test/mock-client.js
- test/mock-interceptor-unused-assertions.js
- test/types/mock-client.test-d.ts
- types/mock-interceptor.d.ts
> feat: add support for request params in mock client

- lib/fetch/formdata.js
- test/fetch/formdata.js
When appending a Blob-like or File-like object to FormData,
the item is wrapped in a `File` object. But this was causing
any options, such as `type` to be hidden in the wrapped type
and not exposed at the top level.
This fix copies the approach used in `formdata-polyfill` and
so also `node-fetch` where the wrapped object is also passed
as the `options` argument when creating a new `File` object.
Fixes https://github.com/cloudflare/wrangler2/issues/1085
> fix: ensure Blob and File `type` are included in FormData

- README.md
- lib/fetch/constants.js
- lib/fetch/headers.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/cookies.js
- test/fetch/headers.js
Fixes #1463 
Fixes #1262 
@ronag's checklist [here](https://github.com/nodejs/undici/issues/1262#issuecomment-1132013882) should be completed:
1. "A WinterCG issue" - https://github.com/wintercg/fetch/issues/6
2. "It's clear in the code that all related logic is outside of spec and a reference motivating it." - Areas of the code where the spec mentioned "filtered" or "safelisted" headers has been commented.
3. "Clearly added to the README."
4. "Investigate what exactly deno, node-fetch and cloudflare does so that we don't introduce another variant with slight differences." - 
- Cloudflare has a [`Headers.prototype.getAll`](https://developers.cloudflare.com/workers/runtime-apis/headers#differences) method (deprecated & removed from the spec) that only works with `set-cookie` headers.
- …
> feat: remove headers filtering

- .github/workflows/nodejs.yml
This stops the job from running if the user is not Dependabot, saving a few seconds CI run time.
> ci: skip automerge job if user is not dependabot

- lib/core/request.js
- test/client-request.js
- `ArrayBuffer.isView(BufferInstance)` didn't allow `isBuffer()` branch to be reached
- Fixed `DataView` dropping whole buffer into request body
- Fixed the rest of `ArrayBufferView`s
> fix: support `TypedArray` and `DataView` as Request body

- test/types/connector.test-d.ts
- types/connector.d.ts
This PR fixes an issue with the type `buildConnector.BuildOptions`.
The `buildConnector.BuildOptions` are used for 2 different methods, `tls.connect(opts)` for https, and `net.connect(opt)` for all other protocols. `TlsOptions` does not include all possible options that can be passed to those methods.
- `tls.connect(opt)` accepts the type `ConnectOptions`
- `net.connect(opt)` accepts the type `NetConnectOpts`
> fix: connector types

- lib/fetch/body.js
With 48c03b62fa9c7e69444fba4a936a7a5e5c88e144, a test from the `node-fetch` suite has started to fail.
```mjs
import vm from 'vm'
import { types } from 'util'
const {
Uint8Array: VMUint8Array
} = vm.runInNewContext('this')
const ab = new VMUint8Array([0, 1, 2]).buffer
ab instanceof ArrayBuffer // false
types.isArrayBuffer(ab) // true
```
https://github.com/nodejs/undici/blob/966a54ff80993573d1baab5999ce258ccc0e7ec9/test/node-fetch/main.js#L36-L38
https://github.com/nodejs/undici/blob/966a54ff80993573d1baab5999ce258ccc0e7ec9/test/node-fetch/main.js#L1004
Not entirely sure how the ci passed 🤷, the precommit hook caught it for me. I assume this is a *really* niche case that possibly shouldn't work, but I think that can be left up to another time...
> fix(tests): broken `node-fetch` tests

- test/proxy-agent.js
It will fix the main CI. However, it's not the best approach.
I'll be working to adjust the certificates for `servername`. FYI: this is happening because the host order has been changed.
> test: add rejectUnauthorized for agent1 cert

- lib/proxy-agent.js
fixes: #1496 
I've tried to include a test, but this happens when the requested URL doesn't contain the port. Usually, external requests, so adding that might lead our tests to flaky in some moment.
> fix(proxy-agent): include host port in the path

- lib/fetch/headers.js
- lib/fetch/util.js
- lib/fetch/webidl.js
- test/fetch/headers.js
Fixes #933 
WebIdl is pretty cool and it's used rather heavily in the fetch spec. Implementing a subset of it (that we need) will make everything much easier once it's finished. I can explain how it'll help if you want, just don't want to write out an essay if you don't care lol
I only did the `Headers` class as a PoC and in the process discovered a *load* of bugs and decided just to add the spec comments since I was already adding a ton to it and fixing stuff anyways 😄.
p.s.: it's very clear that `HeadersList` was not supposed to be Map-like structure, as each key can be duplicated and the actual appending doesn't occur until you use `.get(...)`. Not a big deal, just something I noticed when working on it.
> feat: implement (basic) webidl & headers comments

- lib/fetch/body.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/request.js
- test/fetch/response.js
This adds brand checks to body mixin methods & properties. These are webidl checks done throughout the spec. This disallows the following:
```
// accessing these methods without a proper "this" value
Response.prototype.bodyUsed
Response.prototype.body
Request.prototype.bodyUsed
Request.prototype.body
Request.prototype.text.call({ some: 'this value' })
Response.prototype.text.call({ some: 'this value' })
// same for all other body mixin methods
// "this" must be a Request/Response object now.
```
These checks are already done everywhere else.
Refs: #1436 #1430
> fix(fetch): missing body-mixin brand checks

- lib/fetch/file.js
- lib/fetch/webidl.js
- package.json
- test/fetch/file.js
- test/webidl/converters.js
- test/webidl/helpers.js
- test/webidl/util.js
- types/file.d.ts
Makes `File` completely spec-compliant and adds in a bunch of needed webidl checks.
- Fixes 0 arguments being allowed in File constructor.
- Add webidl checks for File constructor parameters.
- Add missing steps from the spec.
- Add `sequence` converters
- Add dictionary matching & optional key assigning with default & required keys.
- Add TypedArray, (Shared)ArrayBuffer, DataView, and IDL long long converters (required by File).
p.s. most of the webidl apis were inspired by Deno because they're just done well.
> feat(File): proper webidl checks

- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/webidl.js
- test/fetch/formdata.js
- Fixes argument length being incorrect (very minor)
- Updates `makeEntry` since the spec was updated apparently.
Surprisingly the `FormData` class was almost entirely correct and even did most of the webidl conversions.
> fix(FormData): spec compliance

- lib/fetch/headers.js
- lib/fetch/webidl.js
- test/fetch/headers.js
- test/webidl/converters.js
- Removes `TODOs` in the `fill` method. Weird behavior can be entirely explained with one word: "webidl".
- Fixes some invalid errors being thrown when HeadersInit is a function (in webidl, functions are considered Object types).
- Adds a webidl `record<key, value>` converter.
- Combined `webidl.sequenceConverter` and `webidl.converters.sequence` as the latter has no uses without the former.
p.s. once I make a pr for `Response`/`Request` idl, I am going to make a PR to improve the error messages.
---
No major changes in this pr. All current tests pass (other than 2 which were invalid) and node-fetch tests pass.
> feat(Headers): spec-compliant `fill` & constructor

- lib/fetch/response.js
- lib/fetch/webidl.js
- test/fetch/response.js
- test/node-fetch/response.js
- test/webidl/helpers.js
- Adds idl checks to `Response`
- Adds `unsigned short` idl conversion (required by Response).
- Fixes 2 bugs in `webidl.dictionaryConverter` (tests added for these)
All tests pass.
> feat(Response): webidl checks

- lib/fetch/request.js
- lib/fetch/response.js
- lib/fetch/webidl.js
- test/fetch/request.js
- test/node-fetch/request.js
- Remove `abort-controller` npm package support in `fetch`. I could add it back, but unlike `fetch-blob`, doesn't necessarily offer anything over node's built-in AbortController.
- Add in `webidl.converters.any` (just a noop)
- Add in `webidl.converters.boolean` (required for RequestInit.keepalive)
- Add in `webidl.nullableConverter` which allows null as a value in converters.
- Add in `allowedValues` in `webidl.dictionaryConverter` which allows specifying a list of values an input must be (this is needed for webidl enums)
- `webidl.converters.XMLHttpRequestBodyInit` now defaults to using the DOMString converter. Fixed a bug in the node-fetch suite when passing an object as RequestInit's body.
- Add in webidl converters for `Request`.
> feat(Request): webidl checks

- lib/fetch/body.js
- lib/fetch/formdata.js
- lib/fetch/headers.js
- lib/fetch/request.js
- lib/fetch/response.js
- lib/fetch/webidl.js
- test/fetch/headers.js
Adds error messages throughout fetch (everything that was missing a message).
---
My last PR for today. The WebIDL implementation should be done after this, unless there are any bugs.
> feat(webidl): add error messages

- lib/core/errors.js
- lib/fetch/constants.js
- lib/fetch/index.js
- lib/fetch/response.js
- test/fetch/abort.js
This commit uses the proper error when a request is aborted. A WPT actually checks for this behavior.
---
Honestly I didn't know if I should have put DOMException in constants or in util. I can change it if it matters or there's a preference.
> fix(fetch): use AbortError DOMException

- lib/fetch/index.js
Webidl conversions/checks are done in the Request constructor, so the checks in the fetch function were unnecessary.
> feat(fetch): remove unnecessary checks

- README.md
Adds example of getting headers using `HEAD` method to garbage collection section.
Closes #1505.
> docs: add example with `HEAD` method to garbage collection section

- lib/fetch/index.js
- lib/fetch/request.js
- test/fetch/client-fetch.js
Fixes #1527 
---
The fetch docs confused me; for the `method` getter steps, GET is the default value. It should have been unset if the value was not provided in the constructor, though.
See:
1. https://fetch.spec.whatwg.org/#ref-for-dom-requestinit-method
2. https://fetch.spec.whatwg.org/#concept-request-method
> fix(fetch): do not assign default value to `RequestInit.method`

- .github/workflows/nodejs.yml
- README.md
- index.js
- lib/core/request.js
- lib/fetch/body.js
- lib/fetch/constants.js
- lib/fetch/util.js
- lib/fetch/webidl.js
Fetch support incorrectly claimed it would work on node >= v16.5.0.
- Data urls would not work until v16.7.0 (requires `URL.createObjectURL`).
- Body could be infinitely consumed until v16.8.0 (requires [`stream.isDisturbed`](https://nodejs.org/api/stream.html#streamreadableisdisturbedstream)).
- DOMException has some issues where it would extend a TypeError (or at least its name property would be "TypeError")? No idea when this was fixed.
See #1526 (specifically [this](https://github.com/nodejs/undici/pull/1526#issuecomment-1178207405) comment) for more context.
Also adds node v16.8.0 to the test matrix.
> fix(fetch): re-add support for node v16.8.0+

- lib/fetch/headers.js
- test/fetch/response.js
Fixes a regression in a WPT from https://github.com/nodejs/node/pull/43752
This is only an issue in `Headers.prototype.set` when using a header name that contains uppercase characters.
> fix(Headers): lowercase name in `Headers.prototype.set`

- docs/api/MockAgent.md
- lib/mock/mock-interceptor.js
- test/mock-interceptor.js
- test/types/mock-interceptor.test-d.ts
- types/mock-interceptor.d.ts
Quick quality of life fix.  The `reply` method today on the mock interceptor requires both an HTTP status code and a body to send.  In a lot of cases, it's common to mock out an empty body.  Trying to make this as smooth as `nock` by defaulting the body to `''` :)
> fix: allow optional body for mock reply

- lib/fetch/body.js
This will saves some memory and make decoding responses faster and avoids some unnecessary overhead that needs to clone the hole body using Blob that in turns requires everything to be immutable and requires a lots of data being copied.
using `body.text()` became like 2x faster, compared to the prev commit 👍 
closes #1533
> fix: faster direct read approach

- .github/workflows/nodejs.yml
Unfortunately, shared worklfows can't take objects as params - this needs to be a string...
> Fix up `exclude` in CI

- lib/mock/mock-utils.js
- test/mock-pool.js
Fixes #1546
`.abort` is set once `Dispatcher.onConnect` is called, but it's possible the method doesn't exist (another test was failing with this change) and the semantics of calling it when no request was dispatched didn't make much sense to me.
> fix(mock utils): set Readable.abort

- lib/fetch/body.js
- test/fetch/response.js
I was writing a regression test for https://github.com/nodejs/node/issues/43838 and discovered that the body mixin methods were still not spec-compliant. According to the stream standards, every chunk must be a Uint8Array when reading a body.
1. [body-mixin .text()](https://fetch.spec.whatwg.org/#dom-body-text) (for example), calls [consume body](https://fetch.spec.whatwg.org/#concept-body-consume-body)
2. consume body calls [fully reading body as promise](https://fetch.spec.whatwg.org/#fully-reading-body-as-promise)
3. fully reading body as promise calls [ReadableStreamDefaultReader read all bytes](https://streams.spec.whatwg.org/#readablestreamdefaultreader-read-all-bytes)
4. and then [read loop](https://streams.spec.whatwg.org/#read-loop) is called
5. read loop chunk steps says "If …
> fix(body mixin): only allow Uint8Array chunks

- docs/best-practices/proxy.md
update proxy docs example to be runnable copy paste
> docs: updated proxy docs - renamed already used const proxy to proxyServer

- lib/fetch/index.js
- test/fetch/client-fetch.js
Ref: https://github.com/nodejs/node/issues/43868
> Do not decode the body while we are following a redirect

- lib/fetch/index.js
- lib/fetch/webidl.js
- test/fetch/client-fetch.js
- test/webidl/converters.js
Fixes #1317 
Properly converts headers to Latin1. Also fixes some inconsistencies with the regex check in webidl.
> fix(fetch): ByteString checks & conversion in Headers

- lib/fetch/body.js
- test/fetch/client-fetch.js
According to [WHATWG spec](https://fetch.spec.whatwg.org/#body-mixin:~:text=Otherwise%2C%20if%20mimeType%E2%80%99s%20essence%20is%20%22application/x%2Dwww%2Dform%2Durlencoded%22%2C%20then%3A), if mimeType is "application/x-www-form-urlencoded", `.formData()` will parse the body with [application/x-www-form-urlencoded parser](https://url.spec.whatwg.org/#concept-urlencoded-parser). It uses [UTF-8 decode without BOM](https://encoding.spec.whatwg.org/#utf-8-decode-without-bom) which preserves the BOM.
In contrast, `.text()` will use [UTF-8 decode](https://fetch.spec.whatwg.org/#body-mixin:~:text=Return%20the%20result%20of%20running%20UTF%2D8%20decode%20on%20bytes.) , which removes the BOM.
Currently Node.js fails this test case from WPT. …
> fix: x-www-form-urlencoded parser keep the BOM

- lib/fetch/index.js
- lib/fetch/response.js
- lib/fetch/util.js
- test/jest/instanceof-error.test.js
> fix: add `isErrorLike`

- test/types/pool.test-d.ts
- types/pool-stats.d.ts
- types/pool.d.ts
Adds missing stats types to Pool.
Closes #1558
> fix(types): add missing pool stats

- lib/fetch/dataURL.js
- test/fetch/data-uri.js
When data is too large, function argument number will overflow
```
return Uint8Array.of(...output)
```
> fix: fetch a long base64 url will crash and nothing happens (close: #1574)

- lib/fetch/request.js
- test/fetch/request.js
Fixes: https://github.com/nodejs/node/issues/43874
> fix: follow signal.reason in Request

- docsify/sidebar.md
Currently the sidebar link 404s because of the typo: https://undici.nodejs.org/#/docs/api/DiagnosticChannel
> docs: Fix DiagnosticsChannel sidebar link

- lib/mock/mock-utils.js
- test/mock-agent.js
Fixes #1579
This PR makes headers in mock dispatcher case-insensitive. Let me know if I'm going in the wrong direction.
> fix: make mock headers case-insensitive

- lib/fetch/webidl.js
- test/webidl/converters.js
Closes https://github.com/nodejs/undici/issues/1590
Adds a better error message to the ByteString converter. This is close to Firefox's error message.
> feat(webidl): better error message for ByteString converter

- lib/core/util.js
- test/mock-agent.js
- test/util.js
This PR fixes #1532.
The `parseHeaders` method doesn't handle the possibility of the array as the value in the headers. So I've added 1 check to prevent array serialization. I've added 2 tests for that.
The response now is:
```js
{
statusCode: 200,
headers: {
'set-cookie': ['a=b', 'c=d', 'd=e'];
}
}
```
> Fix array headers

- lib/fetch/index.js
- lib/fetch/util.js
- test/fetch/client-fetch.js
This fixes the incorrect error that is thrown in #1594; it will now throw an integrity-mismatch check instead because it hasn't been implemented yet.
This is a weird case where neither uses of `fully read body` had code coverage and I still can't add a test to this area of the code because an error is still being thrown. I did include a test that worked on my end by removing the integrity checks, so once it is implemented the test can be enabled & should run without an issue. I would implement this myself, but there is already a WIP PR at #1596.
In either case, the `response` object referenced in these locations is **not** a WHATWG Response, but an internal representation of a response. It doesn't include the body mixin, which means calling `.arrayBuffer()` on it was throwing an error …
> fix(fetch): implement fully read body algorithm

- lib/fetch/util.js
- test/fetch/client-fetch.js
- test/fetch/integrity.js
> fix: add support for `integrity` option to Fetch

- lib/fetch/file.js
- test/fetch/file.js
`File` ignored the `byteOffset` and `byteLength` properties of typed arrays, meaning the entire backing `ArrayBuffer` was included. Notably, this caused issues when passing `Buffer`s to the `File` constructor.
```js
import { File } from "undici";
const arrayBuffer = new TextEncoder().encode("abcdef").buffer;
const array = new Uint8Array(arrayBuffer, 1, 3);
const arrayFile = new File([array], "file.txt");
console.log(await arrayFile.text()); // expected "bcd", got "abcdef"
const buffer = Buffer.from("test");
const bufferFile = new File([buffer], "file.txt");
console.log(await bufferFile.text()); // expected "test", got garbage
```
> fix(File): respect typed array `byteOffset` and `byteLength`

- lib/fetch/request.js
- test/fetch/abort.js
The PR closes #1605.
A test case is added to ensure it is the `DOMException` being thrown, not `TypeError`.
cc @mcollina @KhafraDev
> fix(fetch): allow custom implementation of AbortSignal

- lib/mock/mock-utils.js
- test/mock-client.js
Proposed solution to #1600 
--- 
- Added test for mis-ordered keys, verified failure against current functionality
- Added parsing for path comparison
Background: intercept does not match requests with query parameters if the keys are in a different order. From an http-standpoint query parameter key ordering does not matter. This causes some confusion if the intercept doesn't work for someone using the library.
Proposed solution: Sort the keys to build a "safeUrl" to prepare a comparable value using URLSearchParams.
Based on Matteo's feedback we may also want to introduce some diagnostic hooks if requests are missed. I'll follow up with another PR.
> fix: make mock intercept agnostic to query key ordering

- lib/fetch/body.js
- test/node-fetch/main.js
- test/node-fetch/request.js
- test/node-fetch/response.js
Implementation-wise, do we really need to make a copy?
> fix: support `ArrayBufferView` and `ArrayBuffer` as body

- lib/fetch/request.js
- test/fetch/request.js
Complements #1608 (totally fixes #1605)
When better checks are performed in the `interfaceConverter` function, this partial revert will be more useful. From my comment in #1608: `Of course the webidl interface converter could also be improved such that when passing a strict: false option, it would check the object's Symbol.toStringTag/constructor name [instead of allowing any value].`
> fix: allow third party AbortControllers

- lib/fetch/index.js
- lib/fetch/util.js
- test/fetch/integrity.js
Fixes #1612 
Bugs fixed:
- Disabled when nodejs is not built with openssl (see issue above)
- Disallows algorithms outside of the ones listed in the spec (sha256, sha384, sha512)
- Checks are ignored if an invalid hash/algorithm are provided (Firefox follows the spec; Chrome throws an error. Left a comment about this behavior.)
- Checks if the algorithms are supported by the user's node.
Tests were added in #1596 but I could add more if needed.
> feat(fetch): implement spec compliant integrity checks

- index-fetch.js
- index.js
- test/client-error-stack-trace.js
- test/fetch/client-error-stack-trace.js
Resolves: #1599
**Checklist**:
> feat: capture error stack traces

- lib/fetch/index.js
- test/fetch/client-fetch.js
We found out that `fetch()` hangs when consuming the stream body of a redirect, when `{ redirect: 'manual' }` is set.
Full discussion: https://github.com/nodejs/undici/discussions/1618
It's covered with unit test: `npm run test:fetch`
Without the fix, you'll see a new test failing like this:
```shell
FAIL  test/fetch/client-fetch.js
✖ terminated
fetchParams.controller.controller.error(
new TypeError('terminated', {
----------^
cause: isErrorLike(reason) ? reason : undefined
})
test: redirect with stream
stack: |
Fetch.onAborted (lib/fetch/index.js:1913:11)
Fetch.terminate (lib/fetch/index.js:83:10)
Object.onError (lib/fetch/index.js:2061:36)
Request.onError (lib/core/request.js:265:27)
errorRequest (lib/client.js:1722:13)
Object.abort (lib/client.js:1335:7)
Object.destroy …
```
> fix(fetch): hangs on a stream response with manual redirect

- lib/fetch/index.js
- test/fetch/client-fetch.js
Recent changes in #1554 cause the response body to not be decoded when a `Location` header is set and the request's `redirect` option is set to `follow`.
For us this caused a few problems because we set the `Location` header on 201 responses to reference the location of the created resource. When looking at the spec, I don't think we're doing anything wrong on our end here. 
> For [201 (Created)](https://www.rfc-editor.org/rfc/rfc9110.html#status.201) responses, the Location value refers to the primary resource created by the request. For [3xx (Redirection)](https://www.rfc-editor.org/rfc/rfc9110.html#status.3xx) responses, the Location value refers to the preferred target resource for automatically redirecting the request.
>
> https://www.rfc-editor.org/rfc/rfc9110.html#name-location
I …
> fix(fetch): decode response body when Location is set on non-3xx response

- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/util.js
Fixes #1629 
Not the greatest solution & no tests. This might not even be a problem - undici correctly lazily loads `File` in fetch's utils already, and pnpm only gives a *warning*. However it was easy enough to make a PR and see.
> fix: circular dependencies in fetch

- README.md
- index.d.ts
- index.js
- lib/fetch/global.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/relative-url.js
- types/global-origin.d.ts
Notes:
1. ~~Will not work between different undici versions (as `setGlobalDispatcher`/`getGlobalDispatcher` do), because of https://github.com/nodejs/node/issues/43157.~~
2. Only allows `http:` or `https:` urls.
3. Allows strings, URL objects, or undefined, as ts lists all of them as a second parameter for the URL constructor.
4. Setting undefined resets the base url (relative paths will throw again).
5. No way to set for individual `fetch` calls. This could come later, but I'd rather not add a million undici-only keys to RequestInit.
Usage:
```js
import { setGlobalOrigin, getGlobalOrigin } from 'undici'
getGlobalOrigin() // undefined
setGlobalOrigin('http://localhost:3000')
getGlobalOrigin() // equal to new URL('http://localhost:3000')
```
> feat(fetch): allow setting base urls

- index-fetch.js
- index.js
- lib/fetch/index.js
These fetch utils are required for a spec-compliant version of XMLHttpRequest.
I'd like to make https://github.com/khafradev/undici/tree/xmlhttprequest into its own package and exporting these would allow me to do so. 😄
> feat: export some fetch utilities

- lib/mock/mock-utils.js
You learn something new exists everyday.
> mock: use http.STATUS_CODES

- lib/fetch/response.js
- test/fetch/request.js
- test/fetch/response.js
`webidl.converters.XMLHttpRequestBodyInit` rejected third-party `FormData`/`Blob`s, meaning they were passed through `webidl.converters.DOMString`. This meant `Request`/`Response`s constructed with third-party `FormData`/`Blob` bodies ended up with a plain-text `[object FormData]`/`[object Blob]` body.
Undici has code for extracting a body from [third-party `Blob`s](https://github.com/nodejs/undici/blob/0862fba5406ff7d45e3b80cd0aaea952098b5a6c/lib/fetch/body.js#L121) and [`FormData`s](https://github.com/nodejs/undici/blob/0862fba5406ff7d45e3b80cd0aaea952098b5a6c/lib/fetch/body.js#L70). This was just being called after [Web IDL](https://github.com/nodejs/undici/blob/0862fba5406ff7d45e3b80cd0aaea952098b5a6c/lib/fetch/request.js#L52-L53) …
> fix(fetch): allow third-party `FormData`/`Blob` bodies

- docs/api/MockPool.md
> fix(docs): `MockPoolInterceptOptions.method` is optional

- README.md
The readme examples were all stylistically a little different, this PR makes them more uniform. About 1 in 4 applicable lines used semis, so I opted to remove them. One example intermixed double and single quotes, the rest were single, so I opted for that too.
> docs: make examples uniform

- .github/workflows/nodejs.yml
- package.json
- test/request-timeout.js
> ci: re-enable testing in Node.js 12

- lib/fetch/body.js
- test/fetch/client-fetch.js
Fixes #1653
The error messages are closer to chrome/firefox now. I don't think they need to be super descriptive.
edit: I considered adding the error header (ie. `Response.text`) but it would be relatively annoying to add the message to `.json()` as it just calls `.text()`, or the message would be completely wrong.
> feat(fetch): better errors messages for body-mixin methods

- index.d.ts
- test/types/index.test-d.ts
The default export was removed in 9c04cfa349998dba72117a05fe0c720416196fbc
> types: remove old signature

- package.json
- test/wpt/runner/fetch/api/body/mime-type.any.js
- test/wpt/runner/resources/testharness.cjs
- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/worker.mjs
- test/wpt/runner/start.mjs
- test/wpt/server/server.mjs
Implements a *very* basic WPT runner that should allow every test to run (theoretically - this PR only enables a single test to ensure that the runner is working).
The implementation is taken from https://github.com/KhafraDev/node-xmlhttprequest/tree/main/tests with some minor adjustments (setting exitCode on test failure, exiting if there are no tests to run).
1. Uses the WPT test harness, unlike node's builtin wpt runner. See https://github.com/nodejs/node/blob/098eac7f272f5e720c9aff8b232501928a88b82a/test/common/wpt.js#L12-L14.
2. Each test runs in its own context, and the tests are run in a Worker. The environment these tests run in should be identical to an actual node.js runtime, so hopefully there won't be any unexpected jest-like issues.
3. Has a built-in server that allows …
> feat: WPT runner

- lib/proxy-agent.js
- test/proxy-agent.js
> Passing correct host header to proxy in ProxyAgent

- lib/fetch/body.js
- package.json
- test/fetch/client-fetch.js
- Add support for multipart/form-data
Closes https://github.com/nodejs/undici/issues/974
> feat: add support for multipart/form-data

- lib/fetch/util.js
- test/fetch/util.js
> feat(fetch#Request): Implements `determineRequestReferrer`

- benchmarks/benchmark.js
Referencing https://github.com/nodejs/undici/pull/1673, this pull request adds `query` as a parameter to benchmarks.
> perf: add query parameter to benchmark

- lib/fetch/webidl.js
- test/webidl/converters.js
- test/wpt/tests/fetch/api/body/formdata.any.js
- test/wpt/tests/fetch/api/headers/headers-basic.any.js
- test/wpt/tests/fetch/api/headers/headers-casing.any.js
- test/wpt/tests/fetch/api/headers/headers-combine.any.js
- test/wpt/tests/fetch/api/headers/headers-errors.any.js
- test/wpt/tests/fetch/api/headers/headers-normalize.any.js
- test/wpt/tests/fetch/api/headers/headers-record.any.js
- test/wpt/tests/fetch/api/headers/headers-structure.any.js
- Updates `webidl.recordConverter` to match the spec (handle proxies).
- Add a space between "at" and "index" in an error message.
Excludes 3 test files:
- COR checks (undici doesn't filter headers)
- One that requires XMLHttpRequest
- One mentioned in #1680 
598 to 660 tests total
> feat: add in Header WPTs

- lib/fetch/body.js
- lib/fetch/headers.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/util.mjs
- test/wpt/runner/runner/worker.mjs
- test/wpt/server/server.mjs
- test/wpt/status/fetch.status.json
- test/wpt/tests/fetch/api/idlharness.any.js
- test/wpt/tests/interfaces/dom.idl
- test/wpt/tests/interfaces/fetch.idl
- test/wpt/tests/interfaces/html.idl
- test/wpt/tests/interfaces/referrer-policy.idl
- test/wpt/tests/resources/WebIDLParser.js
- test/wpt/tests/resources/idlharness.js
- test/wpt/tests/resources/webidl2/lib/webidl2.js
Fixes ~20 'bugs' in fetch. Note that every change was done for a reason and I could explain why if you'd like.
---
1 failed test. I could easily fix it but the test itself makes no sense (`Response.json.length` should be 0). This test also fails in chrome and Deno (only other environments that implement Response.json that I bothered checking).
However node now passes more of fetch's idlharness tests than any other platform, so that's cool.
> feat(WPTs): add in idlharness.any.js test

- benchmarks/benchmark.js
- benchmarks/server.js
- lib/api/api-stream.js
Just a couple of typos fixed in comments. No logic changes.
> chore: fixed typos

- lib/fetch/body.js
- lib/fetch/dataURL.js
- test/fetch/client-fetch.js
- test/fetch/data-uri.js
- test/fetch/response.js
- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/util.mjs
- test/wpt/status/fetch.status.json
- test/wpt/tests/resources/WebIDLParser.js
Improves performance of `.text()`, `.arrayBuffer()`, `.json()`, and `.blob()` by 60%.
The next step is to introduce a synchronous FormData parser - similar to what every other runtime has. It doesn't make sense to asynchronously parse the FormData if all of the bytes are in memory.
If a library needs asynchronous parsing:
```js
const response = new Response(fd, { headers: [['content-type', 'multipart/formdata']] })
for await (const chunk of response.body) {
// write chunk to busboy, for example
}
```
As mentioned in the issue implementing `.formData`, it's very inefficient and should never be used on the server.
Firefox - https://github.com/mozilla/gecko-dev/blob/7f3ff3f4d34e7d234da4f5f5b345d2add7f30e95/dom/base/BodyUtil.cpp#L67
Chromium - …
> feat: implement spec-compliant body mixins

- lib/fetch/body.js
- lib/fetch/constants.js
- test/fetch/response.js
- test/wpt/status/fetch.status.json
- test/wpt/tests/fetch/api/response/response-clone.any.js
Refs: https://github.com/nodejs/undici/issues/1666#issuecomment-1275142274
Enables the following WPTs (only Safari currently passes these tests, and the same 2 tests fail here):
https://wpt.fyi/results/fetch/api/response/response-clone.any.html?label=master&label=experimental&aligned&view=subtest
---
The spec does tell implementations to clone the stream, but you have to go down a few layers:
1. Let « out1, out2 » be the result of [teeing](https://streams.spec.whatwg.org/#readablestream-tee) body’s [stream](https://fetch.spec.whatwg.org/#concept-body-stream).
2. To tee a [ReadableStream](https://streams.spec.whatwg.org/#readablestream) stream, return ? [ReadableStreamTee](https://streams.spec.whatwg.org/#readable-stream-tee)(stream, true).
3. ReadableStreamTee(stream, cloneForBranch2) …
> fix(fetch): use structuredClone in clone body steps

- lib/fetch/body.js
- lib/fetch/index.js
- test/wpt/status/fetch.status.json
- test/wpt/tests/fetch/api/basic/stream-safe-creation.any.js
Unfortunately 4 tests still fail.
This puts us behind every other platform [currently](https://wpt.fyi/results/fetch/api/basic/stream-safe-creation.any.html?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=safari&product=deno&aligned&view=subtest&q=%2Ffetch%2Fapi%2Fbasic%2Fstream-safe-creation.any.html), but 20 cases have been fixed.
- The `size` option defaults to [`() => 1`](https://github.com/nodejs/node/blob/b126f396d54589b875999050e17d528969d2486a/lib/internal/webstreams/util.js#L78)
- The `highWaterMark` option defaults to [1](https://github.com/nodejs/node/blob/main/lib/internal/webstreams/readablestream.js#L257)
> feat: add stream-safe-creation.any.js WPT

- lib/fetch/body.js
- lib/fetch/dataURL.js
- package.json
- test/wpt/runner/runner/runner.mjs
- test/wpt/server/server.mjs
- test/wpt/start-mimesniff.mjs
- test/wpt/status/mimesniff.status.json
- test/wpt/tests/mimesniff/mime-types/parsing.any.js
- test/wpt/tests/mimesniff/mime-types/resources/generated-mime-types.json
- test/wpt/tests/mimesniff/mime-types/resources/mime-types.json
Undici implements a subset of the [mimesniff](https://mimesniff.spec.whatwg.org/) spec for data URLs.
Currently passes 909 tests and fails 989. This might seem pretty bad, but undici currently passes more of these tests than Chrome and Safari ([results](https://wpt.fyi/results/mimesniff/mime-types/parsing.any.html?label=master&label=experimental&aligned&view=subtest)). There's likely more we can do, but most of the failures are caused by node's mimetype parser (or whatever is used in Blob).
> feat: add minesniff WPTs

- lib/fetch/file.js
- test/wpt/status/FileAPI.status.json
This might be a bad change because, although the spec says to make `type` a "parseable MIME type", browsers have seemingly ignored this for years (see: https://github.com/nodejs/node/issues/45008#issuecomment-1279557343).
Not only this, it
1. causes more tests to fail (as Blob's attribute is still 'compliant' with browsers I guess?)
2. requires us to implement our own `type` getter, rather than using Blob's.
3. causes a FileAPI test to fail. I don't think it was meant to pass, as it is literally named "nonparseable" though.
With this change, if you remove the Blob tests from the parsing.any.js test, ~400 more tests succeed. This is because the `File` and `Blob` tests are grouped together and failing an assert causes the File test not to run. 😞
> feat: make File's `type` more strict

- lib/fetch/formdata.js
- lib/fetch/headers.js
- lib/fetch/util.js
- test/fetch/headers.js
- test/wpt/tests/fetch/api/headers/headers-basic.any.js
Adds new WPTs from https://github.com/web-platform-tests/wpt/commit/a31d3ba53a79412793642366f3816c9a63f0cf57
Fixes 2 per-existing tests that were incorrect - I've confirmed that the behavior now matches Firefox.
Expect iterators for FormData and Headers to be much slower, as the optimizations undici did were incorrect.
From the PR itself:
```
In practice, this means that every iteration step needs to be performed on a Headers' sorted-and-combined headers list that should not be cached. Gecko seems to be the only engine doing this right, as both WebKit and Blink appear to carry out the entire iteration on a cached copy of the header list.
```
> fix(fetch): re-calculate iterator after each iteration

- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/util.mjs
- test/wpt/status/fetch.status.json
- test/wpt/tests/fetch/api/basic/scheme-blob.sub.any.js
- Adds in the ability for the WPT runner to handle [pipes](https://web-platform-tests.org/writing-tests/server-pipes.html?highlight=sub#built-in-pipes)/subs.
- Adds in `scheme-blob.sub.any.js` test to ensure this works (file names with `.sub` in them have substitutions in them).
Two tests fail out of 17. One of the tests is entirely... wrong/broken, and the other is illogical. We pass more tests than Chrome/Firefox and the same 2 tests fail on Safari (see: [results](https://wpt.fyi/results/fetch/api/basic/scheme-blob.sub.any.html?label=experimental&label=master&aligned)).
> wpt: add `scheme-blob.sub.any.js`

- docs/api/ProxyAgent.md
- lib/proxy-agent.js
- test/proxy-agent.js
- test/types/proxy-agent.test-d.ts
- types/proxy-agent.d.ts
Implements: add parameter to ProxyAgent options
Benefits: ProxyAgent can use a variety of authentication types.
Also see: About this issue https://github.com/nodejs/undici/issues/1704
> feat: add parameter to ProxyAgent options, which is type of authentication

- lib/client.js
- lib/core/connect.js
- lib/core/symbols.js
- package.json
- test/client-errors.js
- test/diagnostics-channel/connect-error.js
- test/diagnostics-channel/get.js
- test/diagnostics-channel/post-stream.js
- test/diagnostics-channel/post.js
- #1578
- feat: add support for localaddress
- Adds support for `localAddress` by forwarding the option to the `net.Socket#connect`  method.
> feat: add support for localaddress

- test/wpt/runner/runner/runner.mjs
Before:
```
> time npm run test:wpt
[fetch]: Completed: 1283, failed: 140, success: 1143, expected failures: 140, unexpected failures: 0
[FileAPI]: Completed: 234, failed: 19, success: 215, expected failures: 19, unexpected failures: 0
[mimesniff]: Completed: 1898, failed: 1008, success: 890, expected failures: 1008, unexpected failures: 0
real    0m26.233s
user    0m12.328s
sys     0m4.500s
```
After:
```
> time npm run test:wpt
[fetch]: Completed: 1283, failed: 140, success: 1143, expected failures: 140, unexpected failures: 0
[FileAPI]: Completed: 234, failed: 19, success: 215, expected failures: 19, unexpected failures: 0
[mimesniff]: Completed: 1898, failed: 1008, success: 890, expected failures: 1008, unexpected failures: 0
real    0m10.181s
user    0m13.641s
sys     0m8.031s
```
> wpt: run tests in parallel (2.5x speed improvement)

- lib/fetch/body.js
- lib/fetch/index.js
- lib/fetch/util.js
Implements
1. https://github.com/whatwg/fetch/commit/813788a7d7b4bfba9d4398efd22fdae13125ee8a
2. https://github.com/whatwg/fetch/commit/4cd70cf5aecf777a9f6d451c6381423153913da9
3. https://github.com/whatwg/fetch/commit/4a7bf3536c4bd4cd30aedba5d0a2ba865c587699
> fetch: implement new spec changes

- lib/handler/RedirectHandler.js
- test/redirect-request.js
- test/utils/redirecting-servers.js
Ignore query option on redirection, please check https://github.com/nodejs/undici/issues/1691 for more information.
The issue can be reproduced with a simple node/express server:
```javascript
app.get('/', (req, res) => { res.send('Hello world');});
app.get('/endpoint', (req, res) => { res.redirect('/redirection?param1=first');});
app.get('/redirection', (req, res) => { res.redirect('/');});
app.listen(4000, () => {})
```
Then we can call it with undici:
```javascript
undici.request(
'http://localhost:4000/endpoint',
{
maxRedirection: 4,
query: { param: 'test' }
}
).then(res => console.log('Good')).catch(err => console.log(err));
```
The code snippet will produce an error as described in the issue.
Solution: Remove query from options after redirection
> fix(redirect): Ignore query config after redirection

- lib/client.js
- test/content-length.js
- test/issue-1670.js
Fixes: https://github.com/nodejs/undici/issues/1670
> fix: accept close as message complete

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
The name of the default branch of the admin repo has been changed from master to main.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
> docs: change master to main for links in the nodejs org

- lib/fetch/index.js
Disclaimer: this is a pretty terrible solution, but I couldn't find another way of fixing this.
Fixes #1711 
- The listener gets added here
https://github.com/nodejs/undici/blob/7102eb0b7f544cee7669aaf06eb94f38b22aba86/lib/fetch/index.js#L1813
- This is where it should be removed (& onError). If we remove it here it doesn't work, my best guess is that it gets gc'ed? I can't move `onAborted` outside of this scope as it relies on `response`, and if we use a closure (etc.) the same problem would happen.
https://github.com/nodejs/undici/blob/7102eb0b7f544cee7669aaf06eb94f38b22aba86/lib/fetch/index.js#L2028
If you have any idea of how to fix this, please let me know. I spent maybe 45 minutes trying anything I could think of.
Also not sure how I would add tests for this.
> fix(fetch): remove terminated event listener on redirect

- test/wpt/runner/runner/runner.mjs
- test/wpt/status/FileAPI.status.json
- test/wpt/status/fetch.status.json
The runner will now fail if a test that is marked as an expected failure doesn't fail.
The way I did this is either ingenious or horrible, depending on how you look at it. It maps tests that failed to an object and then compares that object to a slightly modified version of the status file (without including other flags or flaky tests).
`assert` gives a very nice error message with exactly which test(s) did not fail (ie. tests that were not in both objects)
I should also add that the order in which tests fail in is entirely deterministic such that the order in which tests fail in will never differ. The failures are mapped by the name of the file itself, similarly to the status files.
> wpt: fail runner if expected failures don't fail

- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/headers.js
- lib/fetch/request.js
- lib/fetch/response.js
- test/fetch/general.js
See: https://webidl.spec.whatwg.org/#ecmascript-binding
"If an object has a [class string](https://webidl.spec.whatwg.org/#dfn-class-string) classString, then the object must, at the time it is created, have a property whose name is the [@@toStringTag](https://tc39.es/ecma262/#sec-well-known-symbols) symbol with PropertyDescriptor{[[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true, [[Value]]: classString}."
---
Also removes a hack that was added in d023b2d8
> fix(fetch): set Symbol.toStringTag properly on classes

- lib/fetch/index.js
- lib/fetch/response.js
- lib/fetch/util.js
> fetch: implement isomorphic encoding

- lib/fetch/dataURL.js
- lib/fetch/util.js
No new failing or passing tests but this way avoids TextDecoder and removes a useless decodeURIComponent so it's probably considerably faster.
> fetch: implement isomorphic decoding

- lib/fetch/constants.js
- lib/fetch/request.js
- Removes checks that are already handled in webidl (the checks were added before webidl was added)
- Uses the already existing valid enum values from constants, instead of duplicating them.
Tests already exist that check that invalid values throw an error.
> fetch: remove duplicate checks

- lib/fetch/body.js
- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/headers.js
- lib/fetch/request.js
- lib/fetch/response.js
- lib/fetch/webidl.js
- lib/fileapi/filereader.js
- lib/fileapi/progressevent.js
- types/webidl.d.ts
*No behavior changes*
1. Add `webidl.brandCheck` which performs:
```js
if (!(x instanceof Y)) {
throw new TypeError('Illegal invocation')
}
```
2. Add typescript types which make working with webidl nicer. These types aren't exported and are only used for dev UX. Next step: add types for converters added outside of the webidl file.
3. Throw errors outside of the webidl error utilities.
> webidl: small changes

- lib/fetch/file.js
- lib/fetch/formdata.js
- lib/fetch/headers.js
- lib/fetch/index.js
- lib/fetch/request.js
- lib/fetch/response.js
- lib/fetch/webidl.js
- lib/fileapi/filereader.js
- types/webidl.d.ts
No behavior changes
Adds `webidl.argumentLengthCheck(arguments, min, ...)` check which performs
```js
const { length } = arguments
if (length < min) {
throw new TypeError('...')
}
```
Also checks for -0 using `x === 0` in some cases which removes some Object.is calls.
> webidl: add `argumentLengthCheck` guard

- lib/mock/mock-utils.js
- test/jest/issue-1757.test.js
- test/mock-agent.js
Fixes #1757
Not the cleanest solution ever, but one that involves no breaking changes.
In the future it would probably be a good idea to switch everything to async so all mock functions can be asynchronous (option matchers, reply callback, etc) without needing ugly workarounds. Didn't feel like making such a breaking change today, though.
> feat(MockInterceptor): allow async reply callbacks

- package.json
- types/filereader.d.ts
- types/patch.d.ts
This has got to be the worst fix of ever, but it works. 😂 
The types technically aren't correct either, but I doubt many people are accessing FileReader's `__proto__`.
Fixes #1740 
Confirmed it fixes the issue with:
- Follow instructions from [here](https://github.com/nodejs/undici/issues/1740#issuecomment-1294740460) but install undici with `npm install "https://github.com/KhafraDev/undici.git#fix-filereader-types" --save`
- `npx tsc -p ./`
> Fix filereader types

- .gitignore
- index.d.ts
- package.json
- test/imports/undici-import.ts
- test/types/dispatcher.events.test-d.ts
- test/types/errors.test-d.ts
- test/types/formdata.test-d.ts
- test/types/interceptor.test-d.ts
- test/types/readable.test-d.ts
- types/agent.d.ts
- types/api.d.ts
- types/balanced-pool.d.ts
- types/client.d.ts
- types/connector.d.ts
- types/diagnostics-channel.d.ts
- types/dispatcher.d.ts
- types/errors.d.ts
- types/fetch.d.ts
- types/global-dispatcher.d.ts
- types/interceptors.d.ts
- types/mock-agent.d.ts
- types/mock-client.d.ts
- types/mock-errors.d.ts
- types/mock-interceptor.d.ts
- types/mock-pool.d.ts
- types/pool-stats.d.ts
- types/pool.d.ts
- types/proxy-agent.d.ts
- types/readable.d.ts
fixes #1727
From my understanding, this shouldn't be a semver major, as public types should stay the same.
> types: Refine internal TS export/imports to be more robust

- lib/fetch/headers.js
Line 135: `this.contains(name)` already runs `name.toLowerCase()` there is no need to run it twice.
> fix: remove unnecessary toLowerCase

- lib/fetch/util.js
`isValidHTTPToken` already checks character by character. There is no need for the additional for loop.
> perf: simplify isValidHeaderName

- lib/fetch/request.js
Uses headersList where the spec says to do "... [if] this’s headers’s header list does not contain..."
> fix(fetch): match spec text

- lib/fetch/dataURL.js
- test/fetch/data-uri.js
- test/node-fetch/main.js
There is no need for the `URLSerializer` since we already have a reference to the `URL` object. `url.toString()` produces the same result
> perf(fetch): simplify url serializer

- README.md
update doc for fetch duplex based on discussions https://github.com/nodejs/undici/discussions/1760
> chore(doc/fetch) update doc for fetch duplex (#1760)

- lib/fetch/body.js
- test/fetch/client-fetch.js
https://www.rfc-editor.org/rfc/rfc7578#section-5.1.1
>If non-ASCII field names are unavoidable, form or application
>   creators SHOULD use UTF-8 uniformly.  This will minimize
>   interoperability problems.
Reproduce:
```js
const formData = new FormData();
formData.append('fiŝo', 'value1');
const request = new Request('http://localhost', {
method: 'POST',
body: formData
});
console.log(...await request.formData());
```
undici
```js
// [ 'fiÅ\x9Do', 'value1' ]
```
Chromium
```js
// ['fiŝo', 'value1']
```
Firefox
```js
// Array [ "fiŝo", "value1" ]
```
> fix(fetch): parse multipart/form-data non-ascii filed names

- lib/fetch/index.js
- lib/fetch/response.js
- test/fetch/redirect.js
Fixes #1776 
https://github.com/nodejs/undici/blob/bb84264639df423fd66dc8b5e03773002c71ddaa/lib/fetch/index.js#L1071-L1073
Since the connection is destroyed on redirect, fetchParams was being marked as cancelled incorrectly due to a check added in https://github.com/nodejs/undici/commit/6883ba5e6ab27eec82dc55eda20438ca50f8e383.
This also fixes an issue where `fetchParams.controller.terminated.reason` doesn't exist, and would throw a TypeError.
> fix(fetch): connection is cancelled when redirecting

- docs/api/Connector.md
- test/types/connector.test-d.ts
- types/connector.d.ts
This PR fixes `buildConnector.Options` issues:
* The `port` property passed from `URL.port` is a string.
* Missing `localAddress` and `httpSocket`.
> fix: connect option types

- lib/fetch/body.js
- lib/fetch/index.js
- lib/fetch/request.js
ReadableStream and TransformStream were added as globals in v18, this PR uses them if available, and falls back to lazy loading them. This pattern is already used elsewhere in the code:
https://github.com/nodejs/undici/blob/232905f476913da9c73df03bac41a0a96d48b128/lib/fetch/util.js#L853
> fetch: prefer global over lazy loading

- lib/fetch/body.js
This pull request includes 2 changes around improving the performance:
1. Each `Buffer.byteLength` makes a C++ call. If we concat them and then calculate pass it to ByteLength, it is faster.
2. `toLowerCase()` is a slow method. That's why I divided the if statement into 2 parts.
> perf: reduce number of native calls from fetch.body

- lib/fileapi/filereader.js
- lib/fileapi/util.js
I discovered this while working on WebSocket support.
This replaces the previous custom `on[name]` event handlers with the correct way.
> More correct filereader event firing

- docs/api/Fetch.md
- docsify/sidebar.md
Closes #1803
Fixes #940 
Fixes #1799 
Co-authored-by: vedanth bora <75097551+VedanthB@users.noreply.github.com>
> docs: add basic fetch & company docs

- lib/fetch/body.js
with this changes you only have to encode the formdata once. 
it also creates an array of blob parts to make it immutable so that it can't be changed afterwards
This basically solves the following problem:
```js
const fd = new FormData()
fd.set('foo', 'bar')
const res = new Response(fd)
fd.set('foo', 'foo')
// fd.set('foo', 'foooo') could also set the field to a other size making req content-length invalid.
const fd2 = await res.formData()
fd2.get('foo')
```
reason why i didn't just do `action = new Blob(parts)` was due to 3rd party files that can be backed up by fs
> make formdata body immutable and encode it only once

- lib/websocket/constants.js
- lib/websocket/receiver.js
- lib/websocket/websocket.js
Refs: #1811 
Before, for every parsing stage, we would concatenate every buffer, even if we only needed to read the first few bytes (for most cases). Now, we can consume `n` bytes from the buffers, removing them & handling the total length. This simplifies the logic quite a bit and should improve performance (although there aren't any benchmarks to confirm this).
ws implements something similar:
https://github.com/websockets/ws/blob/fb1dfd217861757d60c1d02c6e66b4da3630cc93/lib/receiver.js#L94-L131
> feat(websocket): only consume necessary bytes

- lib/core/symbols.js
Refs: https://github.com/nodejs/node/pull/45671
> Use nodejs.stream.destroyed symbol

- lib/core/request.js
- test/headers-as-array.js
- test/node-fetch/main.js
> fix(request): request headers array

- lib/websocket/receiver.js
Refs: #1811
Unsure if I can add a test case, but I've confirmed that this patch fixes the following repro:
```mjs
import assert from 'assert'
import { WebSocketServer } from 'ws'
import { WebSocket } from './index.js'
const helloFrame = Buffer.from([0x81, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f])
// largest body size that is divisible by the frame length
const buffer = Buffer.allocUnsafe(2 ** 31 - 2).fill(helloFrame)
const server = new WebSocketServer({ port: 0 })
server.on('connection', (ws) => {
ws._socket.write(buffer)
})
const ws = new WebSocket(`ws://localhost:${server.address().port}`)
ws.addEventListener('message', ({ data }) => {
assert.equal(data, 'Hello')
})
```
Before, a RangeError would be thrown; now, it succeeds. The problem is that the test takes forever to complete because it's …
> fix(websocket): run parser in loop, instead of recursively

- test/websocket/diagnostics-channel.js
- test/websocket/opening-handshake.js
Should be close to 100% coverage for [`/lib/websocket/connection.js`](https://github.com/nodejs/undici/blob/main/lib/websocket/connection.js) barring 1 or 2 branches which aren't yet possible to reach (no websocket extension support).
> websocket: add tests for opening handshake

- lib/websocket/websocket.js
- test/websocket/close.js
- test/websocket/constructor.js
- test/websocket/send.js
Should cover most branches in the constructor, WebSocket.send, and WebSocket.close.
Fixes 1 small bug when setting protocols to an empty string.
> websocket: add tests for constructor, close, and send

- lib/websocket/events.js
- test/websocket/close.js
- test/websocket/constructor.js
- test/websocket/events.js
- test/websocket/receive.js
- test/websocket/send.js
Fixes 3 bugs regarding Events.
> websocket: more test coverage

- test/wpt/runner/runner/runner.mjs
- test/wpt/server/server.mjs
- test/wpt/status/fetch.status.json
Fixes #1834 
Merry Christmas! 🎅
The flaky WPT on Windows should now be fixed. I detailed the cause/fix for this in the issue above. Testing locally (on windows), this fixed the issue for me.
Also, tests which timeout in the future will now be logged. Should help discover any issues in the runner.
> fix(WPTs): flaky abort test

- lib/fetch/body.js
- lib/fetch/util.js
https://github.com/whatwg/fetch/commit/464326e8eb6a602122c030cd40042480a3c0e265
The changes to the spec above *massively* cleaned up body consume methods and made it much more straightforward.
> fetch: update body consume to match spec

- docs/api/Cookies.md
- docsify/sidebar.md
- index.js
- package.json
Since the cookie handling uses some stuff from the fetch spec, it can only be exposed in node v16+.
> fix(cookie): add docs & expose in node v16

- docs/api/Dispatcher.md
Adjusting statement to avoid confusion about the behavior of the `reset` flag.
- Ref: https://github.com/nodejs/undici/pull/1829#discussion_r1064062294
> docs(Dispatcher): adjust documentation for reset flag

- lib/websocket/websocket.js
... duh, really weird "solution" I came up with, I guess.
> fix(websocket): simplify typedarray copying

- lib/fetch/formdata.js
- test/wpt/runner/runner/worker.mjs
- test/wpt/status/FileAPI.status.json
Refs: https://github.com/nodejs/undici/pull/1858#issuecomment-1385018002
The actual issue is that node v18.13.0 introduces buffer.File and undici's File isn't an instanceof the native File implementation. Really easy fix at least!
> fix: wpts on node v18.13.0+

- lib/client.js
- lib/core/request.js
- test/client-head-reset-override.js
One of the performance bottlenecks we have is that we don't allow keep-alive for HEAD requests due to common server-side  implementation problems where we can't reliably detect if the server is properly ending the HEAD request. However, in the cases where we know the target server it would be nice to be able to explicitly allow this.
> perf: allow keep alive for HEAD requests

- test/fetch/abort.js
Refs: #1862 (the issue should stay open because most of the abort tests are flaky in some capacity)
This is a really simple fix where the server never ends the request, so the request can only be aborted.
> fix: flaky abort test

- lib/fetch/index.js
The WebSockets implementation is included in the bundle for Node.js even though it isn't used, the [esbuld bundle analyser](https://esbuild.github.io/analyze/) explains why it's included:
```
lib/websocket/websocket.js
This file is included in the bundle because:
Entry point index-fetch.js contains:
require("./lib/fetch");
Required file lib/fetch/index.js contains:
require("../../index");
Required file index.js contains:
require("./lib/websocket/websocket");
So required file lib/websocket/websocket.js is included in the bundle.
```
Ref https://github.com/nodejs/undici/pull/1868#issuecomment-1397711309
> fix: don't include websockets in node bundle

- lib/fetch/dataURL.js
While working on [Performance#38](https://github.com/nodejs/performance/issues/38), I decided to use it as starting point Undici for experimenting with possible performance improvements, as Undici has a greatly clean implementation of the WHATWG for parsing a MIMEType.
While experimenting I was able to notice substantial performance improvements while changing smaller pieces, while trying to respect them as much as possible the spec.
Was able to obtain a substantial ~48% improvement compared to the current implementation.
The PR as always is just a suggestion as pointed out in the performance thread, in Undici this is not one of the biggest worries as it is used only while parsing `data:` strings 🙂
Feel free to close it if there's no value added.
```
Hardware Overview:
Model Name: MacBook …
```
> chore(performance#38): Performance improvements

- lib/core/util.js
- package.json
- test/fetch/formdata.js
This PR would implement #1872.
Actually, the `FormData` class needs the following declaration to work:
```js
class FormData {
constructor () {}
append () {}
delete () {}
get () {}
getAll () {}
has () {}
set () {}
entries () {}
keys () {}
values () {}
forEach () {}
}
```
The `isFormDataLike` method was improved by checking the `constructor.name` and the declaration of those methods. This makes that control more strict and flexible. The check would be linear, there is no way to guess what API is requested by the `chunk`. This check allows **third-party libraries** to be compatible with this control.
The tests were updated by adding some cases where the check should return false or true.
> perf(util): improve isFormDataLike checks

- lib/proxy-agent.js
- test/proxy-agent.js
- types/proxy-agent.d.ts
This adds a custom headers option in the ProxyAgent params, which allows specifying arbitrary headers. These will only provided in the initial CONNECT request to the proxy and never to the tunneled requests (they get their own headers specified in the request()).
Fixes #1876.
> Add feature to specify custom headers for proxies

- test/wpt/runner/runner/worker.mjs
refs: https://github.com/nodejs/undici/pull/1879#issuecomment-1401966074
I already knew the bug would occur, just forgot about it honestly.
> fix(wpts): Blob is a global getter in >=v19.x.x

- package.json
- test/wpt/runner/runner/runner.mjs
- test/wpt/server/server.mjs
- test/wpt/start-FileAPI.mjs
- test/wpt/start-fetch.mjs
- test/wpt/start-mimesniff.mjs
- test/wpt/start-websockets.mjs
I have no idea if any of these changes will have an effect, but hopefully they will help on windows.
- Hide experimental warnings from websocket tests
- Limit number of workers to the number of cpus available (about 2-3 seconds slower locally, but less resource intensive)
- If a message can't be sent to a child process, exit the process rather than doing nothing (this *might* be the hanging issue)
- detect when to shutdown using a more reliable system (listening to the exit event on the child process and exiting once the subprocess exited)
> wpt: make runner more resilient

- .github/workflows/nodejs.yml
- test/balanced-pool.js
- test/fetch/abort.js
> Make test pass in v19.x

- lib/fetch/dataURL.js
This implements a faster way of collecting strings up to a certain character.
Performance is either equal/slightly faster or faster in every use-case I tried.
<details>
<summary>String with one unquoted param</summary>
```mjs
import { parseMIMEType } from './lib/fetch/dataURL.js'
import { MIMEType } from 'util'
import cronometro from 'cronometro'
import { parseMIMEType as parseMIMEType2 } from 'undici/lib/fetch/dataURL.js'
const type = 'application'//.repeat(100)
const subtype = 'json'//.repeat(100)
const essence = `${type}/${subtype}`
cronometro({
'undici - new' () {
return parseMIMEType(`${essence}; a=bcdefg`)
},
'undici - old' () {
return parseMIMEType2(`${essence}; a=bcdefg`)
},
'node' () {
return new MIMEType(`${essence}; a=bcdefg`)
}
})
```
``` …
```
> perf(content-type parser): faster string collector

- docs/api/ContentType.md
- docsify/sidebar.md
- index.d.ts
- index.js
- types/content-type.d.ts
Closes #1891
Exposes parse and stringify utility functions for content-type parsing. It's only exposed in v16+ because it relies on fetch utils (which imports `util/types` which wasn't added until v15.3.0).
> feat: expose content-type parser

- types/dispatcher.d.ts
> fix(types): Update DispatchOptions type for missing "blocking"

- test/types/errors.test-d.ts
- types/errors.d.ts
This PR adds missing type definitions for errors and removes others that were no longer in use. It also makes sure all `name`s and `code`s match the JS implementations.
Fixes #1883
> fix(types): update error type definitions

- lib/core/request.js
If content-type header value is not a string we should throw.
> fix: throw if invalid content-type header

- lib/fetch/headers.js
- test/fetch/cookies.js
Fixes #1905 
In browsers, the cookie header is filtered out so there's no mention of special handling. While technically being compliant, will lead to incorrect parsing on the receiving side (from the issue). Deno matches this behavior - delimiting cookie headers with a semicolon rather than a comma, and I believe node core does similar.
> fix(fetch): use semicolon for Cookie header delimiter

- lib/client.js
- lib/timers.js
- test/client-keep-alive.js
- test/client-reconnect.js
- test/client-timeout.js
- test/fetch/fetch-timeouts.js
- test/request-timeout.js
- test/socket-timeout.js
Another major bottleneck I found is the constant refreshing of timers, in particular the body timeout timer which is refresh every time we get a packet.
Our current use of timers is that we have a very few timers which we update frequently where high accuracy is not required. This PR tries to implement that.
> use faster timers

- lib/core/request.js
- test/client-dispatch.js
I don't think it's something else than a string in any of the branches but the check should still be correct.
> fix: ensure header value is a string

- lib/fetch/request.js
- test/fetch/issue-node-46525.js
Fixes https://github.com/nodejs/node/issues/46525
Refs https://github.com/nodejs/undici/issues/939#issuecomment-1419471112
> fix(fetch): raise AbortSignal max event listeners

- lib/client.js
- lib/core/util.js
- lib/mock/mock-utils.js
- test/issue-1903.js
Fixes #1903 
I am not sure if it is good to mutate in `onHeaderValue`.
But I found it should be the most optimal place to do it.
Trans-code the header value in other place would result in heavy boating code.
For example, it would duplicate the logic if modify in `parseHeaders`.
https://github.com/nodejs/undici/blob/7827031d2a7fd99f8ab9d5eddce127c6f700dd35/lib/core/util.js#L212-L235
> fix: content-disposition header parsing

- lib/cookies/index.js
- lib/fetch/headers.js
- test/wpt/status/fetch.status.json
- test/wpt/tests/fetch/api/headers/header-setcookie.any.js
Implements https://github.com/whatwg/fetch/commit/e4d3480e72da5c19c7938a3261a23e5b4b346b49
It got merged finally!
> feat: add Headers.prototype.getSetCookie

- docs/api/MockPool.md
https://github.com/nodejs/undici/pull/1211 introduced a way to dynamically mock all the reply options, including the `statusCode`, which is very handy.
However, despite this behaviour [being presented in the doc](https://undici.nodejs.org/#/docs/api/MockPool?id=example-mocked-request-using-reply-options-callback), the [API method specification](https://undici.nodejs.org/#/docs/api/MockPool?id=return-mockinterceptor) does not take it into account which is confusing.
I am not sure about the wording here - happy to take any suggestions.
> doc(mock): update out-of-date reply documentation

- test/types/connector.test-d.ts
- types/connector.d.ts
Add missing `keepAlive*` params that are present were added in #1904 [docs](https://undici.nodejs.org/#/docs/api/Client?id=parameter-connectoptions) and [code](https://github.com/nodejs/undici/blob/main/lib/core/connect.js#L124), but missing in typings.
> fix(types): add missing keepAlive params

- test/fetch/abort.js
> Make the fetch() abort test pass locally, on Linux and Mac, Node 18/19.

- lib/cookies/parse.js
- lib/fetch/dataURL.js
> perf: improve cookie parsing performance

- test/wpt/runner/runner/runner.mjs
- test/wpt/start-websockets.mjs
Refs: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
Also adds an AbortSignal to the `once` handler to debug
> fix: disable websocket wpts in ci :(

- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/util.mjs
- test/wpt/start-websockets.mjs
I think it's fine to merge, can't run the WPT runner on the windows 19 CI because it keeps failing before then.
> test: more logs in wpt runner

- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/util.mjs
This updates the WPTRunner to respect and individually execute the test variants indicated by META
> test(wpt): respect variants

- test/fetch/data-uri.js
Happened in https://github.com/nodejs/undici/actions/runs/4237639232/jobs/7363840543 and a few other places.
```
1..1
not ok 1 - should be equal
---
compare: ===
at:
line: 185
column: 5
file: test/fetch/data-uri.js
type: Test
stack: |
Test.<anonymous> (test/fetch/data-uri.js:185:5)
source: |2
const serialized = URLSerializer(new URL(domain))
t.equal(serialized, domain)
----^
})
diff: |
--- expected
+++ actual
@@ -1,1 +1,1 @@
-https://domain.com/#
+https://domain.com/
...
not ok 7 - https://domain.com/\# # time=23.051ms
1..1
not ok 1 - should be equal
---
compare: ===
at:
line: 192
column: 5
file: test/fetch/data-uri.js
type: Test
stack: |
Test.<anonymous> (test/fetch/data-uri.js:192:5)
source: |2
const serialized = URLSerializer(new URL(domain))
t.equal(serialized, domain)
----^
})
diff: …
```
> fix: flaky fetch tests

- test/types/balanced-pool.test-d.ts
- types/balanced-pool.d.ts
* Updated `BalancedPool` constructor to account for `URL[]`
* Updated `BalancedPool`'s `addUpstream` to account for `URL`
* Updated `BalancedPool`'s `removeUpstream` to account for `URL`
🏁 Closes: #1948
This is more an fyi or could be a me issue. The `tsc test/imports/undici-import.ts` fails for me due to
```
node_modules/@types/eslint/index.d.ts:451:42 - error TS2724: '"/undici/node_modules/@types/estree/index"' has no exported member named 'ChainExpression'. Did you mean 'Expression'?
451         ChainExpression?: ((node: ESTree.ChainExpression & NodeParentExtension) => void) | undefined;
~~~~~~~~~~~~~~~
```
Looks `@types/eslint` is being used by
```
└─┬ tsd@0.25.0
└─┬ eslint-formatter-pretty@4.1.0
└── @types/eslint@7.29.0
```
Passing `--skipLibCheck` allowed me to run the `tsc …
> fix: 🐛 add URL upstream variations in BalancedPool types

- test/wpt/runner/runner/runner.mjs
- test/wpt/runner/runner/worker.mjs
- test/wpt/tests/fetch/api/abort/general.any.js
Fixes #1963 (...hopefully)
I can't repro the abort test failing locally, but when an uncatchable error is thrown the runner won't crash. This makes us more like browsers where we ignore errors and keep on running smoothly, lol
```js
// META: timeout=long
// META: global=window,worker
promise_test(async t => {
queueMicrotask(() => {
throw new TypeError('missing option')
})
}, "this is test");
promise_test(async t => {
assert_equals(1, 1)
}, "not a test");
```
Before (hard crash):
```
undefined:0
TypeError [Error]: missing option
at evalmachine.<anonymous>:6:11
at node:internal/process/task_queues:140:7
at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```
after:
```js …
```
> test(wpt): handle uncaught exceptions

- lib/fileapi/encoding.js
- test/wpt/status/fetch.status.json
fixes 1 bug in FileReader, everything else is expected/not a bug we can fix
> Fix failing wpts

- test/wpt/runner/runner/runner.mjs
- test/wpt/start-fetch.mjs
- test/wpt/start-mimesniff.mjs
- test/wpt/start-xhr.mjs
I wish to extend the [daily Node.js WPT Report](https://github.com/nodejs/node/blob/main/.github/workflows/daily-wpt-fyi.yml) with your WPTs.
I plan to extend the workflow file with roughly the following
```
UNDICI_VERSION = cat deps/undici/src/package.json | jq -r '.version'
if (UNDICI_VERSION_INCLUDES_THIS_CHANGE(UNDICI_VERSION))
actions/checkout nodejs/undici at $UNDICI_VERSION tag
WPT_REPORT=$(pwd)/out/wpt/wptreport.json npm run test:wpt
```
In order for the WPTs to be comparable with other wpt.fyi results they must respect the variants (1st commit), must sanitize the subtest names and messages the same (part of the 2nd commit).
NB: per commit no whitespace review recommended
> test(wpt): add results to an existing WPT Report

- lib/fetch/request.js
- lib/fetch/util.js
Fixes #1958 or at least the issue described there. There might be other bugs regarding this section of the code, as a bunch of WPTs in this section are still failing (which is why they are still being skipped).
> fix: implement basic policy container

- README.md
Screenshot taken from master branch [readme](https://github.com/nodejs/undici#workarounds):
> README: h3 not showing ### as a header

- test/wpt/runner/runner/worker.mjs
some tests rely on this https://github.com/nodejs/undici/blob/49c6b48fe67c5c11d6693e3a8f8618dd269e26d5/test/wpt/tests/common/gc.js#L16
> wptrunner: expose gc

- lib/client.js
Ensures that headers and chunk len + body can be passed in same packet.
Fixes: https://github.com/nodejs/undici/issues/1981
> perf: cork socket before writing

- lib/timers.js
When there is significant event loop lag timers can prematurely expire.
Fixes: https://github.com/nodejs/undici/issues/1976
> fix: fast timers and event loop lag

- lib/fetch/index.js
- test/fetch/resource-timing.js
`duration` for PerformanceResourceTiming` entries is always zero, which causes all resource timing durations to be negative.
example:
```
{
// ...
entryType: 'resource',
startTime: 70.6499160528183,
duration: -70.6499160528183,
},
```
**root cause**
`duration` is computed from `response.timingInfo.endTime`. `response.timingInfo.endTime` is [computed correctly](https://github.com/nodejs/undici/tree/main#L300) but its value is discarded when [`response.timingInfo` is reassigned](https://github.com/nodejs/undici/tree/main#L303). this causes `createOpaqueTimingInfo`'s [endTime of 0 to be used](https://github.com/nodejs/undici/blob/main/lib/fetch/util.js#L324).
> fix: correctly calculate resource timing duration

- lib/fetch/request.js
It's sufficient that the finalizer removes the closure.
Fixes: https://github.com/nodejs/undici/issues/1926
> fix: remove unnecessary WeakRef

- types/websocket.d.ts
Added a missing import statement at the top of the file.
> Fix: websocket.d.ts - error TS2304: Cannot find name 'MessagePort'

- lib/api/readable.js
- lib/core/util.js
- test/client-request.js
Attempt to implement body.dump({ abort });
fixes: https://github.com/nodejs/undici/issues/1978
> feat: add abort signal to body.dump()

- docs/api/ProxyAgent.md
- lib/proxy-agent.js
- test/proxy-agent.js
- test/types/proxy-agent.test-d.ts
- types/proxy-agent.d.ts
The default use of a Client means that HTTP CONNECT requests to the Proxy will block successive requests. Giving consumers the option to use a Pool ensures that these requests will not block.
fixes: #2001
https://github.com/nodejs/undici/issues/2001
> Add clientFactory option to ProxyAgent

- lib/core/symbols.js
Noticed this while diving through the code, thought i'd put up a quick fix.
> Fix typo in kPipelining symbol

- lib/fetch/response.js
We have checked on the line before that `isError` is falsy, so the cause is always set to `undefined`, which is not very useful.
> fix(fetch): remove `undefined` error cause

- lib/fetch/index.js
- test/fetch/issue-2009.js
Fixes #2009
It ended up being basically exactly what they said in the issue, the body was being canceled with a string, which wasn't getting caught by the isError check. Also a race condition.
> fix: issue 2009

- lib/core/util.js
- test/client-errors.js
Added more descriptive error messages for the URL parser function.
fixes: https://github.com/nodejs/undici/issues/1986
> added descriptive error messages for URL parser

- lib/fetch/constants.js
- test/fetch/issue-2021.js
Fixes https://github.com/nodejs/undici/issues/2021
> fix(fetch): remove content-length header on redirect

- test/fetch/client-fetch.js
Refs: https://github.com/nodejs/node/issues/47301
The test from #2020 still fails so CI won't be green.. yet.
> fix: skip failing test in node >= v19.8

- lib/fetch/index.js
- test/fetch/encoding.js
RFC 7231 says that content-condings should be treated as case-insensitive.
I also removed x-deflate support because it doesn't seem to be an official content-coding, feel free to correct me if I'm wrong.
Also removes the regexes that would match invalid codings such as `agzip` etc., although I think this was caught elsewhere as the bodies weren't being decompressed from my testing.
> fetch: treat content-encoding as case-insensitive & remove x-deflate

- lib/fetch/index.js
- lib/fetch/util.js
tests already extensively cover these areas
> perf(fetch): use string comparisons for url schemes

- types/websocket.d.ts
This stops TypeScript from complaining:
```
error TS2304: Cannot find name 'Blob'.
```
> fix(types): Add missing Blob import

- lib/fetch/request.js
- test/fetch/407-statuscode-window-null.js
The line above we check that it's either null (only valid option) or undefined (missing), so for it to exist, it must be `null` here.
> fix: set window option properly

- lib/core/util.js
- test/issue-1903.js
Closes #2020 
This also matches the behavior of content-disposition parsing with node (https://github.com/nodejs/undici/issues/2020#issuecomment-1484618508): "...if there is explicit content-lenght, the content-disposition header is encoded in latin1..."
> Content disposition parsing

- package.json
The test wasn't running in the CI and has been broken for a while now because of an issue with eslint's types.
> test: add typescript import test back

- docs/api/CacheStorage.md
- docs/api/Fetch.md
- docsify/sidebar.md
- index.d.ts
- index.js
- lib/cache/cache.js
- lib/cache/cachestorage.js
- test/types/cache-storage.test-d.ts
- test/wpt/status/service-workers/cache-storage.status.json
- types/cache.d.ts
- adds docs
- exports types & adds tests for types
- adds `CacheStorage.prototype.match` (all WPTs for it pass)
- exposes it as `caches`, similar to browsers' [`globalThis.caches`](https://developer.mozilla.org/en-US/docs/Web/API/caches)
Test status:
```
[service-workers/cache-storage]: Completed: 103, failed: 13, success: 90, expected failures: 13, unexpected failures: 0, skipped: 2
```
> Cache storage cleanup

- lib/cache/cache.js
- lib/cache/cachestorage.js
- test/wpt/runner/worker.mjs
- test/wpt/server/server.mjs
- test/wpt/status/fetch.status.json
- test/wpt/status/service-workers/cache-storage.status.json
fixes a cachestorage WPT and fixes the tests on linux
> Cache storage fixes

- test/websocket/events.js
takes tests from the WPT repo that can't/aren't being run for whatever reason (being in an html file, being part of a spec undici doesn't implement, whatever) and ports them to tap. As expected there weren't any new bugs found in either of them.
> test: improve test coverage for ErrorEvent and MessageEvent

- docs/api/WebSocket.md
- lib/websocket/connection.js
- lib/websocket/websocket.js
- test/websocket/websocketinit.js
- types/websocket.d.ts
Refs: https://github.com/nodejs/undici/issues/1811#issuecomment-1518940816
This allows someone to supply an options bag to the WebSocket constructor :
```js
const ws = new WebSocket('ws://whatever', {
dispatcher: new MyCustomDispatcher(),
protocols: ['chat', 'echo']
})
```
Allowing it as the second param matches Bun and a proposal by a Deno maintainer (not implemented in Deno to my knowledge). Browsers (specifically Chrome) have no interest in expanding the spec to allow an options bag so this is the only way one will be added. The spec is unfortunately very limited, for both browser & server environments, so we do need to add this for any chance of having a useful WebSocket implementation.
> websocket: add websocketinit

- lib/websocket/connection.js
- lib/websocket/websocket.js
- test/websocket/custom-headers.js
- types/websocket.d.ts
Refs: https://bun.sh/docs/api/websockets#connect-to-a-websocket-server
This is easier than intercepting headers via dispatcher. Also matches bun's api.
> feat(websocket): allow setting custom headers

- lib/fetch/index.js
- test/autoselectfamily.js
- test/balanced-pool.js
- test/fetch/resource-timing.js
Fixes or skips (as a last resort) tests that consistently fail on v20, none of the flaky ones.
edit: windows 20 passed and ubuntu got stuck on the node-fetch tests (happens occasionally)
> test: fix tests failing only on node v20

- lib/fetch/body.js
- test/issue-2065.js
https://github.com/nodejs/undici/pull/2066/files#r1174932605
> fix: skip set content-length when FormData value is stream

- CONTRIBUTING.md
llhttp no longer has `npm run build:wasm`
https://github.com/nodejs/llhttp/blob/c0f4e754b75c033fd3bd2018c8f3ffb673d43d90/package.json#L16
> doc: update outdated command in contributing.md

- lib/cache/cache.js
- test/wpt/status/service-workers/cache-storage.status.json
Before:
```
[service-workers/cache-storage]: Completed: 103, failed: 11, success: 92, expected failures: 11, unexpected failures: 0, skipped: 2
```
After:
```
[service-workers/cache-storage]: Completed: 103, failed: 3, success: 100, expected failures: 3, unexpected failures: 0, skipped: 2
```
You would not believe how many hours this took 😭
The spec doesn't mention that the URLs need to be copied, even though they might be mutated...
> cache: fix most failing WPTs

- build/Dockerfile
- build/wasm.js
- package.json
Fixes: https://github.com/nodejs/undici/issues/2101
Apply this fix https://github.com/nodejs/llhttp/pull/215/files
> feat: allow build:wasm to auto detect platform

- lib/fetch/dataURL.js
- lib/fetch/response.js
- test/wpt/runner/runner.mjs
Before, after
```
[mimesniff]: Completed: 1898, failed: 989, success: 909, expected failures: 989, unexpected failures: 0, skipped: 0
[mimesniff]: Completed: 1898, failed: 872, success: 1026, expected failures: 872, unexpected failures: 0, skipped: 0
```
+117 tests passing.
https://wpt.fyi/results/mimesniff/mime-types/parsing.any.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=deno&product=node.js&aligned
> mimesniff: fix many broken tests

- package.json
- test/agent.js
- test/connect-timeout.js
- test/fetch/client-fetch.js
- test/fetch/jsdom-abortcontroller-1910-1464495619.js
- test/fetch/request.js
- test/proxy-agent.js
- test/redirect-request.js
- test/redirect-stream.js
- test/tls-session-reuse.js
The tests aren't failing according to the CI, they're just timing out. Not sure if this will fix them because they don't timeout locally for me 🤷.
> test: fix failing tests

- lib/websocket/frame.js
- test/websocket/frame.js
I was just bitten by this issue.
Because `buffer` could be a [subarray](https://nodejs.org/api/buffer.html#bufsubarraystart-end), the `byteOffset` and `byteLength` arguments to `new DataView()` are required, otherwise the `bodyLength` value may be written at the wrong offset.
Alternatively, it looks like it would be simpler (and I've tested it works fine) to replace the patched line with `buffer.writeUInt16BE(bodyLength, 2)`.
> Fix bug in 16-bit frame length when buffer is a subarray

- lib/client.js
Not sure how this can occur. I'm guessing if 'finished' and 'drain' are both queued then onDrain will be invoked even though event listeners have been removed.
Fixes: https://github.com/nodejs/undici/issues/2109
> fix: make assertion a noop

- lib/fetch/index.js
- test/node-fetch/main.js
> fix: support truncated gzip

- lib/fetch/index.js
- test/fetch/encoding.js
#2158 
It fixes #2158
I'v reversed the order decompressors that get applied to response body
N/A
fixes #2158
No breaking changes 
> fix: reverse decompression order of "Content-Encoding" encodings (fixes #2158)

- test/wpt/runner/runner.mjs
Refs: https://github.com/nodejs/node/actions/runs/5295407475/jobs/9585718577#step:16:390
@panva told me about this.
(also fixes a small memory leak when a test times out)
> fix: keep running WPTs if a test times out

- lib/fetch/index.js
- test/fetch/issue-2171.js
Fixes https://github.com/nodejs/undici/issues/2171
> fix: forward error reason to fetch controller

- test/types/dispatcher.test-d.ts
- test/types/readable.test-d.ts
- types/dispatcher.d.ts
- types/readable.d.ts
When we first added types for these methods, I thought it would have been best to follow the official DOM types. Since then, I learned that the DOM types are garbage, and that using unknown would have been the better choice. When types were added for fetch (or soon thereafter), `.json()` was changed to use unknown instead of any, providing much better type safety.
IMO this is not a major change, ignoring that it is a types-only change, and someone can revert to using the old `any` behavior very easily:
```diff
- const value = await body.json()
+ const value: any = await body.json()
```
> stricter types for bodymixin.json

- .github/workflows/nodejs.yml
- test/autoselectfamily.js
* #2096 - See 
`autoSelectFamily` issues should have been fixed in Node 20.3.0 and 20.4.0 so it makes sense to reenable tests.
In `test/autoselectfamily.js`:
* All tests are enabled by default.
* The entire file is skipped if the Node version does not supported `autoSelectFamily`.
* All tests specified `autoSelectFamily` property explicitly to avoid incompatibilities between Node release lines.
N/A
N/A
N/A
- [] In review
> chore: Renable autoSelectFamily tests.

- lib/fetch/index.js
- test/fetch/resource-timing.js
The performance resource timings api expects the name parameter to be a string. Undici's fetch implementation is currently passing a URL object when calling `markResourceTiming`. This is outside the spec and makes it impossible to call `getEntriesByName(name)` to find the performance entry for a given url.
The fix is simple and I added a test to verify `getEntriesByName` can find the performance entries created by undici.
References:
- https://nodejs.org/docs/latest-v18.x/api/perf_hooks.html#performancemarkresourcetimingtiminginfo-requestedurl-initiatortype-global-cachemode - `requestedUrl` should be a `string`
- https://w3c.github.io/resource-timing/#dfn-requested-url - `A PerformanceResourceTiming has an associated DOMString requested URL.`
- …
> fix: fetch resource timing performance entry names should be strings

- test/autoselectfamily.js
On Linux with `CONFIG_IPV6` not set it errors with `-EAFNOSUPPORT`.
> test: fix `autoselectfamily` on platforms without IPv6 support

- lib/fetch/body.js
- test/client-request.js
Stringifying `Math.random()` value directly sometimes produces very short boundary string.
Also there is an extreme corner case of it returning exactly `0.0`.
> fix: make multipart/form-data boundary string more consistent

- lib/api/abort-signal.js
- lib/api/readable.js
- lib/core/util.js
- lib/fetch/index.js
- lib/fetch/request.js
> feat: make use of `addAbortListener` where applicable

- lib/cache/cache.js
- lib/fetch/body.js
- lib/fetch/util.js
fixes #2212 
I'm not totally thrilled with the solution, but it does fix the issue.
old stack trace is in the issue
new
```
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
at JSON.parse (<anonymous>)
at parseJSONFromBytes (\undici\lib\fetch\body.js:580:15)
at successSteps (\undici\lib\fetch\body.js:520:23)
at successSteps (\undici\lib\fetch\util.js:821:35)
at fullyReadBody (\undici\lib\fetch\util.js:843:5)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async specConsumeBody (\undici\lib\fetch\body.js:535:3)
at async /undici/test.mjs:3:1
```
> better stack trace for body.json

- lib/fetch/body.js
- test/fetch/client-fetch.js
> fix: preserve file path when parsing formdata

- lib/core/util.js
Node v20.6.0 added `ReadableStream.from()` and we broke.
> Fix fetch in node v20.6.0

- README.md
N/A
Tables are displayed incorrectly in the [README](https://github.com/nodejs/undici/blob/932e5f6/README.md#benchmarks). https://github.com/nodejs/undici/pull/2250
- Replace `│` (`U+2502` / Box Drawings Light Vertical) by `|` (`U+007C` / Vertical Line).
- Replace `─` (`U+2500` / Box Drawings Light Horizontal) by `-` (`U+002D` / Hyphen-Minus).
N/A
N/A
N/A
> docs: fix tables in README

- test/fetch/http2.js
- test/redirect-request.js
- test/utils/redirecting-servers.js
> Fix http2 fetch test

- lib/client.js
- lib/core/request.js
- H2 Support #2061
- Fixes #2257
- Fix H2 connection with empty body.
A method such as `GET` or `HEAD` is not meant to expect a body to be sent. For instance, the `writable` side of the duplex stream can be closed by default.
Not doing so, hangs the request as the server is expecting to finish delivering a body for the request that was not meant to be delivered in the first place.
> fix: h2 without body

- .github/workflows/nodejs.yml
- Duplicated CI runs
I've noticed that the CI runs twice for each PR. Once following the `push` event and once following the `pull_request` event. We can scope the `push` to only `main`, `next`, and `v*` branches, meanwhile keeping `pull_request` events open.
- Remove duplicated CI triggers
> ci: remove duplicated runs

- docs/api/Client.md
- docs/api/Connector.md
- docs/api/Dispatcher.md
- types/client.d.ts
- types/dispatcher.d.ts
Its currently not always clear if the timeouts are set in seconds or milliseconds and further the defaults are written in seconds, which adds to the confusion
Added 'in milliseconds' in lots of places
N/A
N/A
N/A
> improve documentation of timeouts by making the units clear in all places

- index-fetch.js
> expose websocket in node bundle

- test/fetch/http2.js
- HTTP2 support on Undici
- Possible flaky tests for H2
> test: fix Fetch/HTTP2 tests

- lib/client.js
Refs: https://github.com/nodejs/node/pull/49559#issuecomment-1712238921
tested and confirmed undici can be required
> fix undici when node is built with --without-ssl

- lib/pool.js
- test/http2.js
Fixes https://github.com/nodejs/undici/issues/2257
> Fix http2 agent

- lib/core/util.js
- test/content-length.js
In the stream Readable.from(buf) state, the length of 1 refers to the number of objects, not the length of buf. Therefore, when the stream mode is set to 'object,' should not use the length from the state.
In the stream Readable.from(buf) state, the length
of 1 refers to the number of objects, not the length of
buf. Therefore, when the stream mode is set to 'object,'
should not use the length from the state.
> fix: fix request with readable mode is object

- lib/websocket/connection.js
- lib/websocket/frame.js
I didn't catch this in my other PR because the main entry point (index.js) only exports WebSocket if crypto is available. The fetch bundle doesn't do this, which causes issues when node tries to require undici in an environment that doesn't have crypto.
Refs: https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_withoutssl_x64/39416/
> fix loading websockets when node is built w/ --without-ssl

- .husky/pre-commit
This PR will remove `npm run test` from pre-commit hook as per https://github.com/nodejs/undici/issues/2274
> remove npm run test from pre-commit hook

- lib/compat/dispatcher-weakref.js
See https://github.com/nodejs/node/issues/49344#issuecomment-1741776308 for more details, this has been the source of some of the flakiness we have seen.
> Disable finalizationregistry if node code cov

- .github/workflows/publish-undici-types.yml
Didn't realize we didn't have a lock file. `npm ci` only works when we have a lock file.
> use npm install instead of npm ci

- lib/client.js
- package.json
- test/http2.js
Issue https://github.com/nodejs/undici/issues/2307
This PR addresses the issue with pseudo headers order. Some servers (e.g. ClourFlare) in order to prevent DDoS-attacks are very strict about the incoming requests.
- Added `:scheme` pseudo-header
- Changed the order of pseudo-headers to `:authority :method :path :scheme`
- Removing `:path` pseudo-header and adding `:method` pseudo-header from/to `CONNECT` requests following the spec - https://datatracker.ietf.org/doc/html/rfc7540#section-8.3
N/A
N/A
N/A
- [-] Benchmarked (**optional**)
- [-] Documented
> chore: change order of the pseudo-headers

- lib/client.js
- test/fetch/http2.js
> fix(#2311): End stream after body sent

- lib/fetch/index.js
- test/fetch/issue-2318.js
> disallow setting host header in fetch

- lib/client.js
- test/http2.js
Fixes #2335
- Fix stuck when using http2 POST Buffer
> Fix stuck when using http2 POST Buffer

- lib/core/request.js
- test/http2.js
Fixes #2329
- Fix process http2 headers
> fix: 🐛 fix process http2 header

- .github/workflows/publish-undici-types.yml
Apologies for the churn on this, GitHub actions is just my favorite thing to work with. 
I tested this manually here: https://github.com/nodejs/undici/actions/runs/6484620059 so I think we are finally all good after this merges.
> Fix publish undici-types once and for all!

- lib/fetch/index.js
- package.json
- scripts/esbuild-build.mjs
I confirmed tests pass and it works in node.
> Fix node detection omfg

- lib/client.js
Fix #2345
/usr/src/app/node_modules/undici/lib/client.js:1073
parser.readMore()
^
TypeError: Cannot read properties of undefined (reading 'readMore')
at TLSSocket.onSocketReadable (/usr/src/app/node_modules/undici/lib/client.js:1073:10)
at TLSSocket.emit (node:events:514:28)
at emitReadable_ (node:internal/streams/readable:590:12)
at onEofChunk (node:internal/streams/readable:568:5)
at readableAddChunk (node:internal/streams/readable:275:5)
at Readable.push (node:internal/streams/readable:234:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:232:12)
Avoid to call the method is parser is not defined or null
> fix: skip readMore call if parser is null or undefined

- package.json
- test/wpt/start-websockets.mjs
This makes the inclusion of WebSocket in the daily WPT Report uploaded depend on whether it has landed in the respective tested release line or not (or whether it's already made global by default).
[Currently](https://wpt.fyi/results/websockets?run_id=6203937658503168&run_id=5195270930825216&run_id=5093410379137024) it's reported even for releases where the experimental flag is not available (yet).
> test: only include WebSocket in WPT Report where it's landed

- lib/api/api-stream.js
- test/issue-2349.js
Fixes #2349 
Now if `factory` is null, it will not be called. This also implies that `StreamHandler.res` may be null in places it was not before, so I also added a couple of checks for that.
N/A
#2349 
N/A
> fix: Avoid error for stream() being aborted

- test/connect-timeout.js
Ref https://github.com/nodejs/citgm/pull/982#issuecomment-1770497952
> Drop race condition in connect-timeout test

- index-fetch.js
- lib/fetch/index.js
Returning promise from async function causes new promise to become created. This saves few promises in happy paths. No idea if this results in any measurable improvements.
Replace a couple of hot path async functions with sync functions with promise passthrough + Promise.resolve
N/A
N/A
Should be non-breaking
> Remove a couple of unnecessary async functions

- test/types/index.test-d.ts
- types/index.d.ts
Now that 16 is EOL I think it is okay to update our default types to include the Fetch related exports. 
Corresponds to the exports in `index.js`.
> Update namespace type with Fetch exports

- lib/fetch/body.js
- lib/fetch/constants.js
- lib/fetch/file.js
- lib/fetch/index.js
- lib/fetch/request.js
- lib/fetch/response.js
- lib/fetch/util.js
Minor perf improvements
* Use sets over array.indexOf (seems to be consistently faster even for small datasets, see https://www.measurethat.net/Benchmarks/Show/28018/0/sethas-vs-arrayincludes-vs-arrayindexof-small-set-of-st)
* Do not instantiate TextDecoder and TextEncoder over and over
N/A
N/A
No breaking changes
> Use sets and reusable TextEncoder/TextDecoder instances

- lib/core/request.js
- test/client-dispatch.js
Refs: https://github.com/nxtedition/nxt-undici/pull/1
> feat: forward onRequestSent to handler

- package.json
- test/wpt/start-websockets.mjs
> fix windows CI

- lib/pool.js
In Pool() constructor there is unnecessary check `connectTimeout == null ? 10e3 : connectTimeout`
```javascript
class Pool extends PoolBase {
constructor (origin, {
connections,
factory = defaultFactory,
connect,
connectTimeout,
tls,
maxCachedSessions,
socketPath,
autoSelectFamily,
autoSelectFamilyAttemptTimeout,
allowH2,
...options
} = {}) {
super()
//.........
if (typeof connect !== 'function') {
connect = buildConnector({
...tls,
maxCachedSessions,
allowH2,
socketPath,
timeout: connectTimeout == null ? 10e3 : connectTimeout,
...(util.nodeHasAutoSelectFamily && autoSelectFamily ? { autoSelectFamily, autoSelectFamilyAttemptTimeout } : undefined),
...connect
})
}
// ...............
}
```
It is unnecessary because buildConnector already has it:
```javascript
function buildConnector ({ …
```
> refactor: removed unnecessary default

- lib/api/readable.js
- lib/core/util.js
> perf: optimize Readable.dump

- lib/fetch/headers.js
- lib/fetch/webidl.js
This eliminates the `Headers` performance bottleneck.
- `for...of` is slower than `for(;;)`.
- `Object.entries` is slower than  `Object.keys`.
- Reduced the number of variables in the function `ByteString`.
- When trimming `HTTP whitespace`, using RegExp is slow, so change to using `charCodeAt` instead.
N/A
N/A
N/A
```js
// bench.js
const Headers = require("./lib/fetch/headers.js").Headers;
const benchmark = require("benchmark");
const suite = new benchmark.Suite();
const headers = {
"Content-Type": "application/json",
"X-Content-Type": "application/json",
Date: "Wed, 01 Nov 2023 00:00:00 GMT",
"X-NodeJS-Version": "v21.1.0",
"Powered-By": "NodeJS",
"Content-Encoding": "gzip",
"Set-Cookie": "__Secure-ID=123; Secure; Domain=example.com",
"Content-Length": "150",
Vary: "Accept-Encoding, …
```
> perf(headers): Improve Headers

- lib/client.js
Some legacy streams will incorrectly emit 'close' before 'end' in the successfull case.
> fix: delay abort on 'close'

- lib/fetch/headers.js
Reducing the number of calls `String#toLowerCase` showed a 2-fold improvement over main.
However, if no value is present, it will be slightly slower.
See Benchmark
N/A
N/A
N/A
```js
// bench.js
const { Headers } = require("./lib/fetch/headers.js");
const { kHeadersList } = require("./lib/core/symbols.js");
const benchmark = require("benchmark");
const suite = new benchmark.Suite();
const headers = new Headers({ "Accept-Encoding": "gzip" });
const headersList = headers[kHeadersList];
suite.add("HeadersList.get - Existing", () => {
headersList.get("Accept-Encoding");
});
suite.add("HeadersList.get - non Existing", () => {
headersList.get("Accept-Language");
});
suite.add("Headers.get - Existing", () => {
headers.get("Accept-Encoding");
});
suite.add("Headers.get - non Existing", () => { …
```
> perf: optimize HeadersList.get

- lib/fetch/index.js
- test/fetch/http2.js
partially fixes #2415
see my comment for the justification: https://github.com/nodejs/undici/issues/2415#issuecomment-1806453011
(this is honestly one of my favorite issues in quite a long time)
> properly handle pseudo-headers in fetch

- lib/fetch/headers.js
If the guard is immutable, it cannot be deleted or added, so it can be safely cached.
It is also a 1.5x performance improvement over *main*.
This change speeds up the header loop of the fetch response.
> perf(headers): if the guard is immutable

- lib/fetch/headers.js
- test/fetch/headers.js
> fix: implement `Headers#set` correctly

- lib/fetch/headers.js
- test/fetch/headers.js
> fix: implement `Headers#delete` correctly

- lib/client.js
> fix: type comment position

- lib/client.js
- test/fetch/http2.js
- test/http2.js
A much simpler alternative to #2415.
> remove http2 status pseudo header from headers
